version: '3.8'
services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=flowspy 
            - POSTGRES_USER=fod
            - POSTGRES_PASSWORD=heix6ieG
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
             - 5432:5432
    web:
        build: .
        command: >
            sh -c "
            python3.8 manage.py wait_for_db &&
            python3.8 manage.py makemigrations &&
            python3.8 manage.py migrate &&
            python3.8 manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./:/srv/redifod/
        environment:
            - DB_HOST=db
            - DB_NAME=flowspy
            - DB_USER=fod
            - DB_PASS=heix6ieG 
        depends_on: 
            - db
        ports:
            - 22:22
            - 8000:8000
            - 6379:6379  
        restart: always
    
    redis:
        image: redis:alpine
        restart: always
        depends_on:
            - db
            - web
        
    worker:
        build: .
        command: "celery -A flowspy worker --pool=gevent --concurrency=4 --autoscale=10,4 -E -l INFO --logfile=/var/log/fod/celery_jobs.log"

        restart: always
        depends_on: 
            - redis
            - db
        environment:
            - DB_HOST=db
            - DB_NAME=flowspy
            - DB_USER=fod
            - DB_PASS=heix6ieG 
        volumes: 
            - ./:/srv/redifod/
        links:
            - redis  
    beat:
        build: .
        command: "celery -A flowspy beat -l INFO"
        depends_on: 
            - redis
        volumes: 
            - ./:/srv/redifod/
        links:
            - redis        
networks:
    default:
        name: redifod_network
        driver: bridge
    