# Generated by Django 3.1 on 2021-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookmessage',
            name='message',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='webhookmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
