# Generated by Django 3.2 on 2022-10-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flowspec.models


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0002_auto_20210603_1642'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowspec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, unique=True, verbose_name='Name')),
                ('source', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Source Address')),
                ('sourceport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Source Port')),
                ('destination', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Destination Address')),
                ('destinationport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Destination Port')),
                ('port', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Port')),
                ('icmpcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Code')),
                ('icmptype', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Type')),
                ('packetlength', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Packet Length')),
                ('tcpflag', models.CharField(blank=True, choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag')),
                ('filed', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires', models.DateField(blank=True, default=flowspec.models.days_offset, null=True, verbose_name='Expires')),
                ('response', models.CharField(blank=True, max_length=512, null=True, verbose_name='Response')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('requesters_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status')),
                ('is_proposed', models.BooleanField(default=False)),
                ('applier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dscp', models.ManyToManyField(blank=True, to='flowspec.MatchDscp', verbose_name='DSCP')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer')),
                ('protocol', models.ManyToManyField(blank=True, to='flowspec.MatchProtocol', verbose_name='Protocol')),
                ('then', models.ManyToManyField(to='flowspec.ThenAction', verbose_name='Then')),
            ],
            options={
                'verbose_name': 'Rule PUNCH',
                'verbose_name_plural': 'Rules PUNCH',
                'db_table': 'route_punch',
            },
        ),
    ]
