# Generated by Django 3.2 on 2022-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0002_route_punch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thenaction',
            name='action',
            field=models.CharField(choices=[('accept', 'Accept'), ('discard', 'Discard'), ('community', 'Community'), ('next-term', 'Next term'), ('routing-instance', 'Routing Instance'), ('rate-limit', 'Rate limit'), ('sample', 'Sample')], default='discard', max_length=60, verbose_name='Action'),
        ),
    ]
