# Generated by Django 2.2 on 2021-05-31 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0002_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
