# Generated by Django 3.1 on 2021-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0002_auto_20211027_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeniEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.JSONField(null=True)),
            ],
        ),
    ]
