# Generated by Django 2.2 on 2021-06-01 13:09

from django.db import migrations, models
import flowspec.models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0003_validation_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='fragmenttype',
        ),
        migrations.AlterField(
            model_name='route',
            name='expires',
            field=models.DateField(blank=True, default=flowspec.models.days_offset, null=True, verbose_name='Expires'),
        ),
    ]
