# Generated by Django 3.2 on 2022-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0003_alter_thenaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_ceu',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_punch',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_rem',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='then',
            field=models.ManyToManyField(default='discard', to='flowspec.ThenAction', verbose_name='Then'),
        ),
    ]
