# Generated by Django 3.1 on 2021-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0003_genievents'),
    ]

    operations = [
        migrations.AddField(
            model_name='genievents',
            name='network_characteristics',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='genievents',
            name='traffic_characteristics',
            field=models.JSONField(null=True),
        ),
    ]
