# Generated by Django 3.2 on 2024-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0003_auto_20221121_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_ceu',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_punch',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_rem',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='expires',
            field=models.DateField(blank=True, null=True, verbose_name='Expires'),
        ),
    ]
