# Generated by Django 3.2 on 2022-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0004_auto_20221013_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_ceu',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_punch',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_rem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
    ]
