# Generated by Django 3.1 on 2021-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0004_auto_20211125_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackEvent',
            fields=[
                ('id_attack', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_attack', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=35)),
                ('max_value', models.CharField(max_length=50)),
                ('threshold_value', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=35)),
                ('traffic_characteristics', models.JSONField(null=True)),
                ('network_characteristics', models.JSONField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
