# Generated by Django 3.2 on 2024-07-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0002_auto_20210603_1642'),
        ('flowspec', '0004_auto_20240604_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_ceu',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_punch',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_rem',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
    ]
