# Generated by Django 2.2 on 2021-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0005_auto_20210602_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='packetlength',
            field=models.CharField(blank=True, max_length=65535, null=True, verbose_name='Packet Length'),
        ),
    ]
