# Generated by Django 3.1 on 2021-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0005_attackevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackevent',
            name='institution_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attackevent',
            name='ip_attacked',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attackevent',
            name='severity',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
