# Generated by Django 3.1 on 2021-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0006_auto_20210609_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zabbix_graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.CharField(max_length=30)),
                ('prev_value', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
