# Generated by Django 3.2 on 2022-11-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0006_historicalroute_ceu_historicalroute_cib_historicalroute_csic_historicalroute_cunef_historicalroute_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTcpFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcpflag', models.CharField(choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=20)),
            ],
        ),
    ]
