# Generated by Django 3.2 on 2022-11-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0007_matchtcpflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchTcpFlag',
        ),
        migrations.AlterField(
            model_name='historicalroute_ceu',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cib',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_csic',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cunef',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cv',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_imdea',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_imdeanet',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_punch',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_rem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uah',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uam',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uc3m',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_ucm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uned',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_upm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='historicalroute_urjc',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_ceu',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_punch',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_rem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='tcpflag',
            field=models.CharField(choices=[('ack', 'ack'), ('rst', 'rst'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
    ]
