# Generated by Django 3.1 on 2021-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0007_zabbix_graphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbix_graphs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
