# Generated by Django 3.1 on 2021-12-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0007_auto_20211213_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='tcpflag',
        ),
        migrations.AddField(
            model_name='route',
            name='tcpflag',
            field=models.CharField(blank=True, choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag'),
        ),
        migrations.DeleteModel(
            name='TCPFlags',
        ),
    ]
