# Generated by Django 3.1 on 2021-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0008_auto_20211215_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
