# Generated by Django 3.1 on 2021-07-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0008_auto_20210713_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zabbix_graphs',
            new_name='Graphs',
        ),
    ]
