# Generated by Django 3.1 on 2021-07-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0009_auto_20210713_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graphs',
        ),
    ]
