# Generated by Django 3.1 on 2022-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0009_backup_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(help_text='Usar la notación CIDR', max_length=32, verbose_name='Destination Address'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(help_text='Usar la notación CIDR', max_length=32, verbose_name='Source Address'),
        ),
    ]
