# Generated by Django 3.1 on 2022-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0010_auto_20220118_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Destination Address'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Source Address'),
        ),
    ]
