# Generated by Django 3.1 on 2021-07-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0010_delete_graphs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FW_Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_img', models.ImageField(upload_to='media/')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowspec.route')),
            ],
        ),
    ]
