# Generated by Django 3.1 on 2021-07-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0011_fw_graph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FW_Graph',
            new_name='Graph',
        ),
    ]
