# Generated by Django 3.1 on 2022-02-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0011_auto_20220215_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttackEvent',
        ),
        migrations.DeleteModel(
            name='GeniEvents',
        ),
        migrations.DeleteModel(
            name='WebhookMessage',
        ),
    ]
