# Generated by Django 3.1 on 2021-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0012_auto_20210722_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_img',
            field=models.ImageField(max_length=200, upload_to='media/'),
        ),
    ]
