# Generated by Django 3.1 on 2022-02-28 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flowspec.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowspec', '0013_historicalroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_IMDEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, verbose_name='Name')),
                ('source', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Source Address')),
                ('sourceport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Source Port')),
                ('destination', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Destination Address')),
                ('destinationport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Destination Port')),
                ('port', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Port')),
                ('icmpcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Code')),
                ('icmptype', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Type')),
                ('packetlength', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Packet Length')),
                ('tcpflag', models.CharField(blank=True, choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag')),
                ('filed', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires', models.DateField(blank=True, default=flowspec.models.days_offset, null=True, verbose_name='Expires')),
                ('response', models.CharField(blank=True, max_length=512, null=True, verbose_name='Response')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('requesters_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE')], default='PENDING', max_length=20, null=True, verbose_name='Status')),
                ('applier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dscp', models.ManyToManyField(blank=True, to='flowspec.MatchDscp', verbose_name='DSCP')),
                ('protocol', models.ManyToManyField(blank=True, to='flowspec.MatchProtocol', verbose_name='Protocol')),
                ('then', models.ManyToManyField(to='flowspec.ThenAction', verbose_name='Then')),
            ],
            options={
                'verbose_name': 'Rule IMDEA',
                'verbose_name_plural': 'Rules IMDEA',
                'db_table': 'route_imdea',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoute_IMDEA',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, verbose_name='Name')),
                ('source', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Source Address')),
                ('sourceport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Source Port')),
                ('destination', models.CharField(blank=True, help_text='Usar la notación CIDR', max_length=32, null=True, verbose_name='Destination Address')),
                ('destinationport', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Destination Port')),
                ('port', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Port')),
                ('icmpcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Code')),
                ('icmptype', models.CharField(blank=True, max_length=32, null=True, verbose_name='ICMP-Type')),
                ('packetlength', models.CharField(blank=True, max_length=65535, null=True, verbose_name='Packet Length')),
                ('tcpflag', models.CharField(blank=True, choices=[('ack', 'ACK'), ('rst', 'RST'), ('fin', 'FIN'), ('push', 'PUSH'), ('urgent', 'URGENT'), ('syn', 'SYN')], max_length=50, null=True, verbose_name='TCP flag')),
                ('filed', models.DateTimeField(blank=True, editable=False)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('expires', models.DateField(blank=True, default=flowspec.models.days_offset, null=True, verbose_name='Expires')),
                ('response', models.CharField(blank=True, max_length=512, null=True, verbose_name='Response')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('requesters_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE')], default='PENDING', max_length=20, null=True, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rule IMDEA',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
