# Generated by Django 3.1 on 2021-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0014_route_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status'),
        ),
    ]
