# Generated by Django 3.1 on 2022-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0015_auto_20220302_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_ceu',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
