# Generated by Django 3.1 on 2022-04-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0002_auto_20210603_1642'),
        ('flowspec', '0016_auto_20220307_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_ceu',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_cib',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_csic',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_cunef',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_cv',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_imdea',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_imdeanet',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_uah',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_uam',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_uc3m',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_ucm',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_uem',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_uned',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_upm',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalroute_urjc',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_ceu',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_cib',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_csic',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_cunef',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_cv',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_imdea',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_imdeanet',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_uah',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_uam',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_uc3m',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_ucm',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_uem',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_uned',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_upm',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.AddField(
            model_name='route_urjc',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
    ]
