# Generated by Django 3.1 on 2022-09-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0017_auto_20220406_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_ceu',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_cib',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_csic',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_cunef',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_cv',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_imdea',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_imdeanet',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_uah',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_uam',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_uc3m',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_ucm',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_uem',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_uned',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_upm',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalroute_urjc',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_ceu',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_cib',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_csic',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_cunef',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_cv',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_imdea',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_imdeanet',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_uah',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_uam',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_uc3m',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_ucm',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_uem',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_uned',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_upm',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_urjc',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_ceu',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cib',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_csic',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cunef',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_cv',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_imdea',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_imdeanet',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uah',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uam',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uc3m',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_ucm',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uem',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_uned',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_upm',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroute_urjc',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_ceu',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_cib',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_csic',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_cunef',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_cv',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_imdea',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_imdeanet',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_uah',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_uam',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_uc3m',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_ucm',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_uem',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_uned',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_upm',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route_urjc',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR'), ('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING'), ('OUTOFSYNC', 'OUTOFSYNC'), ('INACTIVE', 'INACTIVE'), ('ADMININACTIVE', 'ADMININACTIVE'), ('PROPOSED', 'PROPOSED')], default='PENDING', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
