# Generated by Django 2.2 on 2021-04-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('peer_id', models.AutoField(primary_key=True, serialize=False)),
                ('peer_name', models.CharField(max_length=128)),
                ('peer_as', models.IntegerField(blank=True, null=True)),
                ('peer_tag', models.CharField(max_length=64)),
                ('domain_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'peer',
                'ordering': ['peer_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeerRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'peer_range',
                'ordering': ['network'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TechcEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='email', max_length=352)),
            ],
            options={
                'db_table': 'techc_email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeerNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_activation_notified', models.BooleanField(default=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peers.Peer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='peer',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='networks', to='peers.PeerRange'),
        ),
        migrations.AddField(
            model_name='peer',
            name='techc_emails',
            field=models.ManyToManyField(blank=True, to='peers.TechcEmail'),
        ),
    ]
