# Generated by Django 2.2 on 2021-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='networks',
            field=models.ManyToManyField(related_name='networks', to='peers.PeerRange'),
        ),
    ]
