# Generated by Django 3.2 on 2022-10-10 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peers', '0002_auto_20210603_1642'),
        ('flowspec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGolemAttack',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_name', models.CharField(db_index=True, max_length=50)),
                ('ip_src', models.GenericIPAddressField(default='0.0.0.0')),
                ('ip_dest', models.GenericIPAddressField(default='0.0.0.0')),
                ('src_port', models.CharField(blank=True, max_length=65535, null=True)),
                ('dest_port', models.CharField(blank=True, max_length=65535, null=True)),
                ('port', models.CharField(blank=True, max_length=65535, null=True)),
                ('tcpflag', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('max_value', models.FloatField(blank=True, max_length=500, null=True)),
                ('threshold_value', models.FloatField(blank=True, max_length=500, null=True)),
                ('typeof_value', models.CharField(blank=True, max_length=200, null=True)),
                ('received_at', models.DateTimeField(blank=True, editable=False)),
                ('ends_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('nameof_attack', models.CharField(blank=True, max_length=200, null=True)),
                ('typeof_attack', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer')),
            ],
            options={
                'verbose_name': 'historical golem attack',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GolemAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=50, unique=True)),
                ('ip_src', models.GenericIPAddressField(default='0.0.0.0')),
                ('ip_dest', models.GenericIPAddressField(default='0.0.0.0')),
                ('src_port', models.CharField(blank=True, max_length=65535, null=True)),
                ('dest_port', models.CharField(blank=True, max_length=65535, null=True)),
                ('port', models.CharField(blank=True, max_length=65535, null=True)),
                ('tcpflag', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('max_value', models.FloatField(blank=True, max_length=500, null=True)),
                ('threshold_value', models.FloatField(blank=True, max_length=500, null=True)),
                ('typeof_value', models.CharField(blank=True, max_length=200, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('nameof_attack', models.CharField(blank=True, max_length=200, null=True)),
                ('typeof_attack', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer')),
                ('protocol', models.ManyToManyField(blank=True, to='flowspec.MatchProtocol')),
            ],
        ),
    ]
