# Generated by Django 3.1 on 2022-02-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peers', '0002_auto_20210603_1642'),
        ('flowspec', '0011_auto_20220215_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGolemAttack',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_name', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(max_length=50)),
                ('max_value', models.CharField(max_length=100)),
                ('threshold_value', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer')),
                ('route', models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route')),
            ],
            options={
                'verbose_name': 'historical golem attack',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GolemAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(max_length=50)),
                ('max_value', models.CharField(max_length=100)),
                ('threshold_value', models.CharField(max_length=100)),
                ('peer', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer')),
                ('route', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route')),
            ],
        ),
    ]
