# Generated by Django 3.2 on 2022-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0001_initial'),
        ('golem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='route_ceu',
            field=models.ManyToManyField(blank=True, related_name='route_ceu', to='flowspec.Route_CEU'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cib',
            field=models.ManyToManyField(blank=True, related_name='route_cib', to='flowspec.Route_CIB'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_csic',
            field=models.ManyToManyField(blank=True, related_name='route_csic', to='flowspec.Route_CSIC'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cunef',
            field=models.ManyToManyField(blank=True, related_name='route_cunef', to='flowspec.Route_CUNEF'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cv',
            field=models.ManyToManyField(blank=True, related_name='route_cv', to='flowspec.Route_CV'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdea',
            field=models.ManyToManyField(blank=True, related_name='route_imdea', to='flowspec.Route_IMDEA'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdeanet',
            field=models.ManyToManyField(blank=True, related_name='route_imdeanet', to='flowspec.Route_IMDEANET'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_rem',
            field=models.ManyToManyField(blank=True, related_name='route_rem', to='flowspec.Route_REM'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uah',
            field=models.ManyToManyField(blank=True, related_name='route_uah', to='flowspec.Route_UAH'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uam',
            field=models.ManyToManyField(blank=True, related_name='route_uam', to='flowspec.Route_UAM'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uc3m',
            field=models.ManyToManyField(blank=True, related_name='route_uc3m', to='flowspec.Route_UC3M'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_ucm',
            field=models.ManyToManyField(blank=True, related_name='route_ucm', to='flowspec.Route_UCM'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uem',
            field=models.ManyToManyField(blank=True, related_name='route_uem', to='flowspec.Route_UEM'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uned',
            field=models.ManyToManyField(blank=True, related_name='route_uned', to='flowspec.Route_UNED'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_upm',
            field=models.ManyToManyField(blank=True, related_name='route_upm', to='flowspec.Route_UPM'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_urjc',
            field=models.ManyToManyField(blank=True, related_name='route_urjc', to='flowspec.Route_URJC'),
        ),
    ]
