# Generated by Django 3.2 on 2022-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0002_auto_20221107_1303'),
        ('golem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='tcpflag',
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='tcpflag',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='tcpflag',
            field=models.ManyToManyField(blank=True, to='flowspec.TcpFlag', verbose_name='TCP Flag'),
        ),
    ]
