# Generated by Django 3.1 on 2022-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0002_auto_20220224_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='received_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
