# Generated by Django 3.1 on 2022-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0015_auto_20220302_1153'),
        ('golem', '0003_auto_20220225_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golemattack',
            old_name='source',
            new_name='ip_dest',
        ),
        migrations.RenameField(
            model_name='historicalgolemattack',
            old_name='source',
            new_name='ip_dest',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='dest_port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='ip_src',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='protocol',
            field=models.ManyToManyField(blank=True, to='flowspec.MatchProtocol'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='src_port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='tcpflag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='dest_port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='ip_src',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='src_port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='tcpflag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
