# Generated by Django 3.1 on 2022-03-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0016_auto_20220307_1155'),
        ('peers', '0002_auto_20210603_1642'),
        ('golem', '0006_auto_20220315_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalgolemattack',
            name='peer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='peers.peer'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='peer',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peers.peer'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route'),
        ),
    ]
