# Generated by Django 3.1 on 2022-03-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0016_auto_20220307_1155'),
        ('golem', '0007_auto_20220315_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='route_ceu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_ceu'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_cib'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_csic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_csic'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cunef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_cunef'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_cv'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_imdea'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdeanet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_imdeanet'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_uah'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_uam'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uc3m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_uc3m'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_ucm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_ucm'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_uem'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_uned'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_upm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_upm'),
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_urjc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowspec.route_urjc'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_ceu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_ceu'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_cib',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_cib'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_csic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_csic'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_cunef',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_cunef'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_cv',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_cv'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_imdea',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_imdea'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_imdeanet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_imdeanet'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_uah',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_uah'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_uam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_uam'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_uc3m',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_uc3m'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_ucm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_ucm'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_uem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_uem'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_uned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_uned'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_upm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_upm'),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='route_urjc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowspec.route_urjc'),
        ),
    ]
