# Generated by Django 3.1 on 2022-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0016_auto_20220307_1155'),
        ('golem', '0009_auto_20220321_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_ceu',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_cib',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_csic',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_cunef',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_cv',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_imdea',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_imdeanet',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_uah',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_uam',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_uc3m',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_ucm',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_uem',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_uned',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_upm',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='route_urjc',
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_ceu',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_ceu',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_CEU'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_cib',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cib',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_CIB'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_csic',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_csic',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_CSIC'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_cunef',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cunef',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_CUNEF'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_cv',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_cv',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_CV'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_imdea',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdea',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_IMDEA'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_imdeanet',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_imdeanet',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_IMDEANET'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_uah',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uah',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UAH'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_uam',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uam',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UAM'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_uc3m',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uc3m',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UC3M'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_ucm',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_ucm',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UCM'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_uem',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uem',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UEM'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_uned',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_uned',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UNED'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_upm',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_upm',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_UPM'),
        ),
        migrations.RemoveField(
            model_name='golemattack',
            name='route_urjc',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='route_urjc',
            field=models.ManyToManyField(blank=True, null=True, to='flowspec.Route_URJC'),
        ),
    ]
