# Generated by Django 3.1 on 2022-03-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0011_auto_20220328_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='port',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
