# Generated by Django 3.1 on 2022-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0012_auto_20220329_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
