# Generated by Django 3.1 on 2022-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0013_auto_20220510_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemattack',
            name='id_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgolemattack',
            name='id_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
