# Generated by Django 3.1 on 2022-09-08 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0014_auto_20220613_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemattack',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalgolemattack',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
