# Generated by Django 3.1 on 2022-09-15 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0015_auto_20220908_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
