# Generated by Django 3.1 on 2022-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0016_auto_20220915_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemattack',
            name='finished_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalgolemattack',
            name='finished_at',
            field=models.DateTimeField(default=None),
        ),
    ]
