# Generated by Django 3.1 on 2022-09-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0017_auto_20220915_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golemattack',
            old_name='finished_at',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='historicalgolemattack',
            old_name='finished_at',
            new_name='duration',
        ),
    ]
