# Generated by Django 3.1 on 2022-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0018_auto_20220915_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golemattack',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='duration',
        ),
    ]
