# Generated by Django 3.1 on 2022-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0020_auto_20220915_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='nameof_attack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='nameof_attack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
