# Generated by Django 3.1 on 2022-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0021_auto_20220915_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golemattack',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicalgolemattack',
            name='duration',
        ),
        migrations.AddField(
            model_name='golemattack',
            name='ends_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='ends_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
