# Generated by Django 3.1 on 2022-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0023_auto_20220921_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemattack',
            name='ends_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgolemattack',
            name='ends_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
