# Generated by Django 3.1 on 2022-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0024_auto_20220921_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemattack',
            name='ends_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgolemattack',
            name='ends_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
