# Generated by Django 3.2 on 2022-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golem', '0025_auto_20220922_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='golemattack',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgolemattack',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
