--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4 (Debian 13.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.0 (Debian 14.0-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id;
DROP INDEX public.socialaccount_socialtoken_app_id_636a42d7;
DROP INDEX public.socialaccount_socialtoken_account_id_951f210e;
DROP INDEX public.socialaccount_socialapp_sites_socialapp_id_97fb6e7d;
DROP INDEX public.socialaccount_socialapp_sites_site_id_2579dee5;
DROP INDEX public.socialaccount_socialaccount_user_id_8146e70c;
DROP INDEX public.route_then_thenaction_id_584c41c9;
DROP INDEX public.route_then_route_id_9ffa5b34;
DROP INDEX public.route_protocol_route_id_de983cfe;
DROP INDEX public.route_protocol_matchprotocol_id_da93afcc;
DROP INDEX public.route_name_d990cc6c_like;
DROP INDEX public.route_name_d990cc6c;
DROP INDEX public.route_dscp_route_id_3c9f515e;
DROP INDEX public.route_dscp_matchdscp_id_f3e2c070;
DROP INDEX public.route_applier_id_51f87ff7;
DROP INDEX public.peers_peernotify_user_id_0f09946d;
DROP INDEX public.peers_peernotify_peer_id_b87bf62e;
DROP INDEX public.peer_techc_emails_techcemail_id_a0dac283;
DROP INDEX public.peer_techc_emails_peer_id_3c925438;
DROP INDEX public.peer_networks_peerrange_id_2647ea6f;
DROP INDEX public.peer_networks_peer_id_9b1e48f9;
DROP INDEX public.match_protocol_protocol_6d7860e7_like;
DROP INDEX public.match_port_port_9d50baf9_like;
DROP INDEX public.flowspec_validation_user_id_68741edf;
DROP INDEX public.flowspec_graph_route_id_3841b1c2;
DROP INDEX public.django_site_domain_a2e37b91_like;
DROP INDEX public.django_session_session_key_c0390e0f_like;
DROP INDEX public.django_session_expire_date_a5c62663;
DROP INDEX public.django_flatpage_url_41612362_like;
DROP INDEX public.django_flatpage_url_41612362;
DROP INDEX public.django_flatpage_sites_site_id_bfd8ea84;
DROP INDEX public.django_flatpage_sites_flatpage_id_078bbc8b;
DROP INDEX public.django_admin_log_user_id_c564eba6;
DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX public.authtoken_token_key_10f0b77e_like;
DROP INDEX public.auth_user_username_6821ab7c_like;
DROP INDEX public.auth_user_user_permissions_user_id_a95ead1b;
DROP INDEX public.auth_user_user_permissions_permission_id_1fbb5f2c;
DROP INDEX public.auth_user_groups_user_id_6a12ed8b;
DROP INDEX public.auth_user_groups_group_id_97559544;
DROP INDEX public.auth_permission_content_type_id_2f476e4b;
DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX public.auth_group_name_a6ea08ec_like;
DROP INDEX public.accounts_userprofile_peers_userprofile_id_2159c80a;
DROP INDEX public.accounts_userprofile_peers_peer_id_84acb941;
DROP INDEX public.account_emailconfirmation_key_f43612bd_like;
DROP INDEX public.account_emailconfirmation_email_address_id_5b7f8c58;
DROP INDEX public.account_emailaddress_user_id_2c513194;
DROP INDEX public.account_emailaddress_email_03be32b2_like;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_pkey;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_action_action_value_2bfee264_uniq;
ALTER TABLE ONLY public.techc_email DROP CONSTRAINT techc_email_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp_sites_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp DROP CONSTRAINT socialaccount_socialapp_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_pkey;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_pkey;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_pkey;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_pkey;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_pkey;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq;
ALTER TABLE ONLY public.peer_range DROP CONSTRAINT peer_range_pkey;
ALTER TABLE ONLY public.peer DROP CONSTRAINT peer_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_protocol_key;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_pkey;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_port_key;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_pkey;
ALTER TABLE ONLY public.match_dscp DROP CONSTRAINT match_dscp_pkey;
ALTER TABLE ONLY public.flowspec_webhookmessage DROP CONSTRAINT flowspec_webhookmessage_pkey;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_pkey;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_pkey;
ALTER TABLE ONLY public.flowspec_fragmenttype DROP CONSTRAINT flowspec_fragmenttype_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_domain_a2e37b91_uniq;
ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq;
ALTER TABLE ONLY public.django_flatpage DROP CONSTRAINT django_flatpage_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_key;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_username_key;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_pkey;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_pkey;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_key_key;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_pkey;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_email_key;
ALTER TABLE public.then_action ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.techc_email ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_then ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peers_peernotify ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_techc_emails ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_range ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_networks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer ALTER COLUMN peer_id DROP DEFAULT;
ALTER TABLE public.match_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_port ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_webhookmessage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_validation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_graph ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_fragmenttype ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_site ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_migrations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_content_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_admin_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_permission ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile_peers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailconfirmation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailaddress ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.then_action_id_seq;
DROP TABLE public.then_action;
DROP SEQUENCE public.techc_email_id_seq;
DROP TABLE public.techc_email;
DROP SEQUENCE public.socialaccount_socialtoken_id_seq;
DROP TABLE public.socialaccount_socialtoken;
DROP SEQUENCE public.socialaccount_socialapp_sites_id_seq;
DROP TABLE public.socialaccount_socialapp_sites;
DROP SEQUENCE public.socialaccount_socialapp_id_seq;
DROP TABLE public.socialaccount_socialapp;
DROP SEQUENCE public.socialaccount_socialaccount_id_seq;
DROP TABLE public.socialaccount_socialaccount;
DROP SEQUENCE public.route_then_id_seq;
DROP TABLE public.route_then;
DROP SEQUENCE public.route_protocol_id_seq;
DROP TABLE public.route_protocol;
DROP SEQUENCE public.route_id_seq;
DROP SEQUENCE public.route_dscp_id_seq;
DROP TABLE public.route_dscp;
DROP TABLE public.route;
DROP SEQUENCE public.peers_peernotify_id_seq;
DROP TABLE public.peers_peernotify;
DROP SEQUENCE public.peer_techc_emails_id_seq;
DROP TABLE public.peer_techc_emails;
DROP SEQUENCE public.peer_range_id_seq;
DROP TABLE public.peer_range;
DROP SEQUENCE public.peer_peer_id_seq;
DROP SEQUENCE public.peer_networks_id_seq;
DROP TABLE public.peer_networks;
DROP TABLE public.peer;
DROP SEQUENCE public.match_protocol_id_seq;
DROP TABLE public.match_protocol;
DROP SEQUENCE public.match_port_id_seq;
DROP TABLE public.match_port;
DROP SEQUENCE public.match_dscp_id_seq;
DROP TABLE public.match_dscp;
DROP SEQUENCE public.flowspec_webhookmessage_id_seq;
DROP TABLE public.flowspec_webhookmessage;
DROP SEQUENCE public.flowspec_validation_id_seq;
DROP TABLE public.flowspec_validation;
DROP SEQUENCE public.flowspec_graph_id_seq;
DROP TABLE public.flowspec_graph;
DROP SEQUENCE public.flowspec_fragmenttype_id_seq;
DROP TABLE public.flowspec_fragmenttype;
DROP SEQUENCE public.django_site_id_seq;
DROP TABLE public.django_site;
DROP TABLE public.django_session;
DROP SEQUENCE public.django_migrations_id_seq;
DROP TABLE public.django_migrations;
DROP SEQUENCE public.django_flatpage_sites_id_seq;
DROP TABLE public.django_flatpage_sites;
DROP SEQUENCE public.django_flatpage_id_seq;
DROP TABLE public.django_flatpage;
DROP SEQUENCE public.django_content_type_id_seq;
DROP TABLE public.django_content_type;
DROP SEQUENCE public.django_admin_log_id_seq;
DROP TABLE public.django_admin_log;
DROP TABLE public.authtoken_token;
DROP SEQUENCE public.auth_user_user_permissions_id_seq;
DROP TABLE public.auth_user_user_permissions;
DROP SEQUENCE public.auth_user_id_seq;
DROP SEQUENCE public.auth_user_groups_id_seq;
DROP TABLE public.auth_user_groups;
DROP TABLE public.auth_user;
DROP SEQUENCE public.auth_permission_id_seq;
DROP TABLE public.auth_permission;
DROP SEQUENCE public.auth_group_permissions_id_seq;
DROP TABLE public.auth_group_permissions;
DROP SEQUENCE public.auth_group_id_seq;
DROP TABLE public.auth_group;
DROP SEQUENCE public.accounts_userprofile_peers_id_seq;
DROP TABLE public.accounts_userprofile_peers;
DROP SEQUENCE public.accounts_userprofile_id_seq;
DROP TABLE public.accounts_userprofile;
DROP SEQUENCE public.account_emailconfirmation_id_seq;
DROP TABLE public.account_emailconfirmation;
DROP SEQUENCE public.account_emailaddress_id_seq;
DROP TABLE public.account_emailaddress;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailaddress_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailaddress_id_seq OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailaddress_id_seq OWNED BY public.account_emailaddress.id;


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailconfirmation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailconfirmation_id_seq OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailconfirmation_id_seq OWNED BY public.account_emailconfirmation.id;


--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile (
    id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_id_seq OWNED BY public.accounts_userprofile.id;


--
-- Name: accounts_userprofile_peers; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile_peers (
    id integer NOT NULL,
    userprofile_id integer NOT NULL,
    peer_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile_peers OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_peers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_peers_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_peers_id_seq OWNED BY public.accounts_userprofile_peers.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(255) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO fod;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_groups_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_groups_id_seq OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_groups_id_seq OWNED BY public.auth_user_groups.id;


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_id_seq OWNER TO fod;

--
-- Name: auth_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_id_seq OWNED BY public.auth_user.id;


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_user_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_user_permissions_id_seq OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_user_permissions_id_seq OWNED BY public.auth_user_user_permissions.id;


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO fod;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_admin_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_content_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_flatpage; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage (
    id integer NOT NULL,
    url character varying(100) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    enable_comments boolean NOT NULL,
    template_name character varying(70) NOT NULL,
    registration_required boolean NOT NULL
);


ALTER TABLE public.django_flatpage OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_id_seq OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_id_seq OWNED BY public.django_flatpage.id;


--
-- Name: django_flatpage_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage_sites (
    id integer NOT NULL,
    flatpage_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.django_flatpage_sites OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_sites_id_seq OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_sites_id_seq OWNED BY public.django_flatpage_sites.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fod;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_site_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_site_id_seq OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_site_id_seq OWNED BY public.django_site.id;


--
-- Name: flowspec_fragmenttype; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_fragmenttype (
    id integer NOT NULL,
    fragmenttype character varying(20) NOT NULL
);


ALTER TABLE public.flowspec_fragmenttype OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_fragmenttype_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_fragmenttype_id_seq OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_fragmenttype_id_seq OWNED BY public.flowspec_fragmenttype.id;


--
-- Name: flowspec_graph; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_graph (
    id integer NOT NULL,
    graph_img character varying(200) NOT NULL,
    route_id integer NOT NULL
);


ALTER TABLE public.flowspec_graph OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_graph_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_graph_id_seq OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_graph_id_seq OWNED BY public.flowspec_graph.id;


--
-- Name: flowspec_validation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_validation (
    id integer NOT NULL,
    value character varying(10) NOT NULL,
    created_date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.flowspec_validation OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_validation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_validation_id_seq OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_validation_id_seq OWNED BY public.flowspec_validation.id;


--
-- Name: flowspec_webhookmessage; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_webhookmessage (
    id integer NOT NULL,
    received_at timestamp with time zone NOT NULL,
    message jsonb
);


ALTER TABLE public.flowspec_webhookmessage OWNER TO fod;

--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_webhookmessage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_webhookmessage_id_seq OWNER TO fod;

--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_webhookmessage_id_seq OWNED BY public.flowspec_webhookmessage.id;


--
-- Name: match_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_dscp (
    id integer NOT NULL,
    dscp character varying(24) NOT NULL
);


ALTER TABLE public.match_dscp OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_dscp_id_seq OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_dscp_id_seq OWNED BY public.match_dscp.id;


--
-- Name: match_port; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_port (
    id integer NOT NULL,
    port character varying(24)
);


ALTER TABLE public.match_port OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_port_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_port_id_seq OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_port_id_seq OWNED BY public.match_port.id;


--
-- Name: match_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_protocol (
    id integer NOT NULL,
    protocol character varying(24) NOT NULL
);


ALTER TABLE public.match_protocol OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_protocol_id_seq OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_protocol_id_seq OWNED BY public.match_protocol.id;


--
-- Name: peer; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer (
    peer_id integer NOT NULL,
    peer_name character varying(128) NOT NULL,
    peer_as integer,
    peer_tag character varying(64) NOT NULL,
    domain_name character varying(128)
);


ALTER TABLE public.peer OWNER TO fod;

--
-- Name: peer_networks; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_networks (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    peerrange_id integer NOT NULL
);


ALTER TABLE public.peer_networks OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_networks_id_seq OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_networks_id_seq OWNED BY public.peer_networks.id;


--
-- Name: peer_peer_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_peer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_peer_id_seq OWNER TO fod;

--
-- Name: peer_peer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_peer_id_seq OWNED BY public.peer.peer_id;


--
-- Name: peer_range; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_range (
    id integer NOT NULL,
    network character varying(128) NOT NULL
);


ALTER TABLE public.peer_range OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_range_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_range_id_seq OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_range_id_seq OWNED BY public.peer_range.id;


--
-- Name: peer_techc_emails; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_techc_emails (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    techcemail_id integer NOT NULL
);


ALTER TABLE public.peer_techc_emails OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_techc_emails_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_techc_emails_id_seq OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_techc_emails_id_seq OWNED BY public.peer_techc_emails.id;


--
-- Name: peers_peernotify; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peers_peernotify (
    id integer NOT NULL,
    peer_activation_notified boolean NOT NULL,
    peer_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.peers_peernotify OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peers_peernotify_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peers_peernotify_id_seq OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peers_peernotify_id_seq OWNED BY public.peers_peernotify.id;


--
-- Name: route; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32) NOT NULL,
    sourceport character varying(65535),
    destination character varying(32) NOT NULL,
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    tcpflag character varying(128),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    applier_id integer
);


ALTER TABLE public.route OWNER TO fod;

--
-- Name: route_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_dscp (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchdscp_id integer NOT NULL
);


ALTER TABLE public.route_dscp OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_dscp_id_seq OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_dscp_id_seq OWNED BY public.route_dscp.id;


--
-- Name: route_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_id_seq OWNER TO fod;

--
-- Name: route_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_id_seq OWNED BY public.route.id;


--
-- Name: route_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_protocol (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchprotocol_id integer NOT NULL
);


ALTER TABLE public.route_protocol OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_protocol_id_seq OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_protocol_id_seq OWNED BY public.route_protocol.id;


--
-- Name: route_then; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_then (
    id integer NOT NULL,
    route_id integer NOT NULL,
    thenaction_id integer NOT NULL
);


ALTER TABLE public.route_then OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_then_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_then_id_seq OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_then_id_seq OWNED BY public.route_then.id;


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialaccount_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialaccount_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialaccount_id_seq OWNED BY public.socialaccount_socialaccount.id;


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_id_seq OWNED BY public.socialaccount_socialapp.id;


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id integer NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_sites_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_sites_id_seq OWNED BY public.socialaccount_socialapp_sites.id;


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialtoken_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialtoken_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialtoken_id_seq OWNED BY public.socialaccount_socialtoken.id;


--
-- Name: techc_email; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.techc_email (
    id integer NOT NULL,
    email character varying(352) NOT NULL
);


ALTER TABLE public.techc_email OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.techc_email_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.techc_email_id_seq OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.techc_email_id_seq OWNED BY public.techc_email.id;


--
-- Name: then_action; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.then_action (
    id integer NOT NULL,
    action character varying(60) NOT NULL,
    action_value character varying(255)
);


ALTER TABLE public.then_action OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.then_action_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.then_action_id_seq OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.then_action_id_seq OWNED BY public.then_action.id;


--
-- Name: account_emailaddress id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress ALTER COLUMN id SET DEFAULT nextval('public.account_emailaddress_id_seq'::regclass);


--
-- Name: account_emailconfirmation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation ALTER COLUMN id SET DEFAULT nextval('public.account_emailconfirmation_id_seq'::regclass);


--
-- Name: accounts_userprofile id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_id_seq'::regclass);


--
-- Name: accounts_userprofile_peers id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_peers_id_seq'::regclass);


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: auth_user id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user ALTER COLUMN id SET DEFAULT nextval('public.auth_user_id_seq'::regclass);


--
-- Name: auth_user_groups id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups ALTER COLUMN id SET DEFAULT nextval('public.auth_user_groups_id_seq'::regclass);


--
-- Name: auth_user_user_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_user_user_permissions_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_flatpage id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_id_seq'::regclass);


--
-- Name: django_flatpage_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_sites_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: django_site id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site ALTER COLUMN id SET DEFAULT nextval('public.django_site_id_seq'::regclass);


--
-- Name: flowspec_fragmenttype id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype ALTER COLUMN id SET DEFAULT nextval('public.flowspec_fragmenttype_id_seq'::regclass);


--
-- Name: flowspec_graph id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph ALTER COLUMN id SET DEFAULT nextval('public.flowspec_graph_id_seq'::regclass);


--
-- Name: flowspec_validation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation ALTER COLUMN id SET DEFAULT nextval('public.flowspec_validation_id_seq'::regclass);


--
-- Name: flowspec_webhookmessage id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_webhookmessage ALTER COLUMN id SET DEFAULT nextval('public.flowspec_webhookmessage_id_seq'::regclass);


--
-- Name: match_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp ALTER COLUMN id SET DEFAULT nextval('public.match_dscp_id_seq'::regclass);


--
-- Name: match_port id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port ALTER COLUMN id SET DEFAULT nextval('public.match_port_id_seq'::regclass);


--
-- Name: match_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol ALTER COLUMN id SET DEFAULT nextval('public.match_protocol_id_seq'::regclass);


--
-- Name: peer peer_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer ALTER COLUMN peer_id SET DEFAULT nextval('public.peer_peer_id_seq'::regclass);


--
-- Name: peer_networks id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks ALTER COLUMN id SET DEFAULT nextval('public.peer_networks_id_seq'::regclass);


--
-- Name: peer_range id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range ALTER COLUMN id SET DEFAULT nextval('public.peer_range_id_seq'::regclass);


--
-- Name: peer_techc_emails id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails ALTER COLUMN id SET DEFAULT nextval('public.peer_techc_emails_id_seq'::regclass);


--
-- Name: peers_peernotify id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify ALTER COLUMN id SET DEFAULT nextval('public.peers_peernotify_id_seq'::regclass);


--
-- Name: route id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route ALTER COLUMN id SET DEFAULT nextval('public.route_id_seq'::regclass);


--
-- Name: route_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp ALTER COLUMN id SET DEFAULT nextval('public.route_dscp_id_seq'::regclass);


--
-- Name: route_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol ALTER COLUMN id SET DEFAULT nextval('public.route_protocol_id_seq'::regclass);


--
-- Name: route_then id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then ALTER COLUMN id SET DEFAULT nextval('public.route_then_id_seq'::regclass);


--
-- Name: socialaccount_socialaccount id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialaccount_id_seq'::regclass);


--
-- Name: socialaccount_socialapp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_id_seq'::regclass);


--
-- Name: socialaccount_socialapp_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_sites_id_seq'::regclass);


--
-- Name: socialaccount_socialtoken id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialtoken_id_seq'::regclass);


--
-- Name: techc_email id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email ALTER COLUMN id SET DEFAULT nextval('public.techc_email_id_seq'::regclass);


--
-- Name: then_action id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action ALTER COLUMN id SET DEFAULT nextval('public.then_action_id_seq'::regclass);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
1	admin@admin.com	t	f	1
2	alicarsan@gmail.com	t	f	3
3	alicia.cardenosa@imdea.org	t	t	2
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile (id, user_id) FROM stdin;
1	1
2	2
3	3
\.


--
-- Data for Name: accounts_userprofile_peers; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile_peers (id, userprofile_id, peer_id) FROM stdin;
1	1	1
2	2	1
3	3	2
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add log entry	7	add_logentry
26	Can change log entry	7	change_logentry
27	Can delete log entry	7	delete_logentry
28	Can view log entry	7	view_logentry
29	Can add flat page	8	add_flatpage
30	Can change flat page	8	change_flatpage
31	Can delete flat page	8	delete_flatpage
32	Can view flat page	8	view_flatpage
33	Can add Token	9	add_token
34	Can change Token	9	change_token
35	Can delete Token	9	delete_token
36	Can view Token	9	view_token
37	Can add token	10	add_tokenproxy
38	Can change token	10	change_tokenproxy
39	Can delete token	10	delete_tokenproxy
40	Can view token	10	view_tokenproxy
41	Can add fragment type	11	add_fragmenttype
42	Can change fragment type	11	change_fragmenttype
43	Can delete fragment type	11	delete_fragmenttype
44	Can view fragment type	11	view_fragmenttype
45	Can add match dscp	12	add_matchdscp
46	Can change match dscp	12	change_matchdscp
47	Can delete match dscp	12	delete_matchdscp
48	Can view match dscp	12	view_matchdscp
49	Can add match port	13	add_matchport
50	Can change match port	13	change_matchport
51	Can delete match port	13	delete_matchport
52	Can view match port	13	view_matchport
53	Can add match protocol	14	add_matchprotocol
54	Can change match protocol	14	change_matchprotocol
55	Can delete match protocol	14	delete_matchprotocol
56	Can view match protocol	14	view_matchprotocol
57	Can add webhook message	15	add_webhookmessage
58	Can change webhook message	15	change_webhookmessage
59	Can delete webhook message	15	delete_webhookmessage
60	Can view webhook message	15	view_webhookmessage
61	Can add validation	16	add_validation
62	Can change validation	16	change_validation
63	Can delete validation	16	delete_validation
64	Can view validation	16	view_validation
65	Can add then action	17	add_thenaction
66	Can change then action	17	change_thenaction
67	Can delete then action	17	delete_thenaction
68	Can view then action	17	view_thenaction
69	Can add Rule	18	add_route
70	Can change Rule	18	change_route
71	Can delete Rule	18	delete_route
72	Can view Rule	18	view_route
73	Can add graph	19	add_graph
74	Can change graph	19	change_graph
75	Can delete graph	19	delete_graph
76	Can view graph	19	view_graph
77	Can add peer	20	add_peer
78	Can change peer	20	change_peer
79	Can delete peer	20	delete_peer
80	Can view peer	20	view_peer
81	Can add peer range	21	add_peerrange
82	Can change peer range	21	change_peerrange
83	Can delete peer range	21	delete_peerrange
84	Can view peer range	21	view_peerrange
85	Can add techc email	22	add_techcemail
86	Can change techc email	22	change_techcemail
87	Can delete techc email	22	delete_techcemail
88	Can view techc email	22	view_techcemail
89	Can add peer notify	23	add_peernotify
90	Can change peer notify	23	change_peernotify
91	Can delete peer notify	23	delete_peernotify
92	Can view peer notify	23	view_peernotify
93	Can add user profile	24	add_userprofile
94	Can change user profile	24	change_userprofile
95	Can delete user profile	24	delete_userprofile
96	Can view user profile	24	view_userprofile
97	Can see registered users and rules	24	overview
98	Can add email address	25	add_emailaddress
99	Can change email address	25	change_emailaddress
100	Can delete email address	25	delete_emailaddress
101	Can view email address	25	view_emailaddress
102	Can add email confirmation	26	add_emailconfirmation
103	Can change email confirmation	26	change_emailconfirmation
104	Can delete email confirmation	26	delete_emailconfirmation
105	Can view email confirmation	26	view_emailconfirmation
106	Can add social account	27	add_socialaccount
107	Can change social account	27	change_socialaccount
108	Can delete social account	27	delete_socialaccount
109	Can view social account	27	view_socialaccount
110	Can add social application	28	add_socialapp
111	Can change social application	28	change_socialapp
112	Can delete social application	28	delete_socialapp
113	Can view social application	28	view_socialapp
114	Can add social application token	29	add_socialtoken
115	Can change social application token	29	change_socialtoken
116	Can delete social application token	29	delete_socialtoken
117	Can view social application token	29	view_socialtoken
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	pbkdf2_sha256$216000$b9Ui0lvDqZ2I$hqND8vZOj7aSRceMrufpR2hrTGXOyc7475KqERrOYtA=	\N	f	tecnico	Jorge		alicarsan@gmail.com	t	t	2021-10-27 10:25:30+00
2	pbkdf2_sha256$216000$CaRPGDD2GmPR$RTG258V8T2NHEC7IymqcCgtsbi8Z7KkWvEto7UNOA3g=	2021-10-27 10:56:31.361726+00	f	Alicia			alicia.cardenosa@imdea.org	t	t	2021-10-27 10:25:03+00
1	pbkdf2_sha256$216000$rELYV9b62Hpv$LhU9jPzEuDzhcxg3fb29RvFJ0RE+H0BVWuoRfqyRQQc=	2021-10-27 10:56:42.52598+00	t	admin			admin@admin.com	t	t	2021-10-27 09:40:54.31323+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2021-10-27 09:41:23.304063+00	1	admin@admin.com	2	[{"changed": {"fields": ["Verified"]}}]	25	1
2	2021-10-27 09:41:45.679815+00	1	1.1.1.1/32	1	[{"added": {}}]	21	1
3	2021-10-27 09:41:48.644378+00	2	2.2.2.2/32	1	[{"added": {}}]	21	1
4	2021-10-27 09:41:54.654123+00	1	tcp	1	[{"added": {}}]	14	1
5	2021-10-27 09:41:58.202581+00	2	udp	1	[{"added": {}}]	14	1
6	2021-10-27 09:42:01.651576+00	3	icmp	1	[{"added": {}}]	14	1
7	2021-10-27 09:42:14.396176+00	1	accept	1	[{"added": {}}]	17	1
8	2021-10-27 09:42:22.38368+00	2	rate-limit:1G	1	[{"added": {}}]	17	1
9	2021-10-27 09:42:38.31212+00	1	IMDEA	1	[{"added": {}}]	20	1
10	2021-10-27 09:42:48.32605+00	2	UAH	1	[{"added": {}}]	20	1
11	2021-10-27 09:43:42.77124+00	1	redifod.redimadrid.es	2	[{"changed": {"fields": ["Domain name", "Display name"]}}]	6	1
12	2021-10-27 09:43:58.843235+00	1	admin	1	[{"added": {}}]	24	1
13	2021-10-27 10:25:03.980301+00	2	Alicia	1	[{"added": {}}, {"added": {"name": "user profile", "object": "Alicia"}}]	3	1
14	2021-10-27 10:25:12.667973+00	2	Alicia	2	[{"changed": {"fields": ["Email address", "Staff status"]}}]	3	1
15	2021-10-27 10:25:19.416972+00	2	Alicia	2	[]	3	1
16	2021-10-27 10:25:31.022927+00	3	tecnico	1	[{"added": {}}, {"added": {"name": "user profile", "object": "tecnico"}}]	3	1
17	2021-10-27 10:25:45.709607+00	3	tecnico	2	[{"changed": {"fields": ["First name", "Email address", "Staff status"]}}]	3	1
18	2021-10-27 10:31:34.220263+00	2	alicarsan@gmail.com	2	[{"changed": {"fields": ["Verified"]}}]	25	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	admin	logentry
8	flatpages	flatpage
9	authtoken	token
10	authtoken	tokenproxy
11	flowspec	fragmenttype
12	flowspec	matchdscp
13	flowspec	matchport
14	flowspec	matchprotocol
15	flowspec	webhookmessage
16	flowspec	validation
17	flowspec	thenaction
18	flowspec	route
19	flowspec	graph
20	peers	peer
21	peers	peerrange
22	peers	techcemail
23	peers	peernotify
24	accounts	userprofile
25	account	emailaddress
26	account	emailconfirmation
27	socialaccount	socialaccount
28	socialaccount	socialapp
29	socialaccount	socialtoken
\.


--
-- Data for Name: django_flatpage; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage (id, url, title, content, enable_comments, template_name, registration_required) FROM stdin;
\.


--
-- Data for Name: django_flatpage_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage_sites (id, flatpage_id, site_id) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2021-10-27 09:33:17.383824+00
2	auth	0001_initial	2021-10-27 09:33:19.827985+00
3	account	0001_initial	2021-10-27 09:33:25.615347+00
4	account	0002_email_max_length	2021-10-27 09:33:26.4478+00
5	peers	0001_initial	2021-10-27 09:33:28.320801+00
6	accounts	0001_initial	2021-10-27 09:33:31.948181+00
7	admin	0001_initial	2021-10-27 09:33:33.509976+00
8	admin	0002_logentry_remove_auto_add	2021-10-27 09:33:34.649358+00
9	admin	0003_logentry_add_action_flag_choices	2021-10-27 09:33:34.746124+00
10	contenttypes	0002_remove_content_type_name	2021-10-27 09:33:34.859284+00
11	auth	0002_alter_permission_name_max_length	2021-10-27 09:33:34.969292+00
12	auth	0003_alter_user_email_max_length	2021-10-27 09:33:35.08164+00
13	auth	0004_alter_user_username_opts	2021-10-27 09:33:35.490584+00
14	auth	0005_alter_user_last_login_null	2021-10-27 09:33:35.52895+00
15	auth	0006_require_contenttypes_0002	2021-10-27 09:33:35.694031+00
16	auth	0007_alter_validators_add_error_messages	2021-10-27 09:33:35.719275+00
17	auth	0008_alter_user_username_max_length	2021-10-27 09:33:36.121703+00
18	auth	0009_alter_user_last_name_max_length	2021-10-27 09:33:36.237083+00
19	auth	0010_alter_group_name_max_length	2021-10-27 09:33:36.263404+00
20	auth	0011_update_proxy_permissions	2021-10-27 09:33:36.367399+00
21	auth	0012_alter_user_first_name_max_length	2021-10-27 09:33:36.393245+00
22	auth	0013_auto_20211027_1033	2021-10-27 09:33:36.50426+00
23	authtoken	0001_initial	2021-10-27 09:33:36.946967+00
24	authtoken	0002_auto_20160226_1747	2021-10-27 09:33:37.383684+00
25	authtoken	0003_tokenproxy	2021-10-27 09:33:37.398692+00
26	sites	0001_initial	2021-10-27 09:33:37.748979+00
27	flatpages	0001_initial	2021-10-27 09:33:38.77295+00
28	flowspec	0001_initial	2021-10-27 09:33:45.195458+00
29	longerusername	0001_initial	2021-10-27 09:33:49.607729+00
30	peers	0002_auto_20210603_1642	2021-10-27 09:33:49.74349+00
31	sessions	0001_initial	2021-10-27 09:33:50.343583+00
32	sites	0002_alter_domain_unique	2021-10-27 09:33:51.800251+00
33	socialaccount	0001_initial	2021-10-27 09:33:53.930729+00
34	socialaccount	0002_token_max_lengths	2021-10-27 09:33:56.120124+00
35	socialaccount	0003_extra_data_default_dict	2021-10-27 09:33:56.203556+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
02sykjfb5gmo5s8x3836if7bsyk51bgn	.eJxVjc0OgjAQhN-lZ9NsfyjFo3efoVm6i1RNaygkGuO7CwkHvc43881bBFzmMSyVp5BIHIUSh9-sx3jjvAG6Yr4UGUuep9TLrSJ3WuW5EN9Pe_dPMGId17XRVmsLAyi24FrvLXQqDk1setTOO0-kreksgWFkbn0EUIbZE7bri9uklWtNJQd-PtL0Ekf4fAFNnz6i:1mfgbq:IDTBknsgj1yt7_nCU0MyWAst6GFIFyj8rGhtAfil-ZQ	2021-11-10 10:56:42.542001+00
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_site (id, domain, name) FROM stdin;
1	redifod.redimadrid.es	redifod.redimadrid
\.


--
-- Data for Name: flowspec_fragmenttype; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_fragmenttype (id, fragmenttype) FROM stdin;
\.


--
-- Data for Name: flowspec_graph; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_graph (id, graph_img, route_id) FROM stdin;
1	186441.png	2
\.


--
-- Data for Name: flowspec_validation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_validation (id, value, created_date, user_id) FROM stdin;
1	BNoNSB	2021-10-27	1
2	Ka0gZI	2021-10-27	1
3	J78bU7	2021-10-27	1
\.


--
-- Data for Name: flowspec_webhookmessage; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_webhookmessage (id, received_at, message) FROM stdin;
\.


--
-- Data for Name: match_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_dscp (id, dscp) FROM stdin;
\.


--
-- Data for Name: match_port; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_port (id, port) FROM stdin;
\.


--
-- Data for Name: match_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_protocol (id, protocol) FROM stdin;
1	tcp
2	udp
3	icmp
\.


--
-- Data for Name: peer; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer (peer_id, peer_name, peer_as, peer_tag, domain_name) FROM stdin;
1	IMDEA	\N	Imdea Test	\N
2	UAH	\N	Universidad de Alcalá de Henares	\N
\.


--
-- Data for Name: peer_networks; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_networks (id, peer_id, peerrange_id) FROM stdin;
1	1	1
2	1	2
3	2	1
4	2	2
\.


--
-- Data for Name: peer_range; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_range (id, network) FROM stdin;
1	1.1.1.1/32
2	2.2.2.2/32
\.


--
-- Data for Name: peer_techc_emails; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_techc_emails (id, peer_id, techcemail_id) FROM stdin;
\.


--
-- Data for Name: peers_peernotify; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peers_peernotify (id, peer_activation_notified, peer_id, user_id) FROM stdin;
\.


--
-- Data for Name: route; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, tcpflag, filed, last_updated, expires, response, comments, requesters_address, status, applier_id) FROM stdin;
2	ntprueba_IMDEA	2.2.2.2/32	80	1.1.1.1/32	80	\N	\N	\N	850	\N	2021-10-27 09:44:12.661026+00	2021-10-27 11:02:55.089252+00	2021-11-25	Successfully committed		unknown	ACTIVE	2
1	ntpattack_IMDEA	1.1.1.1/32	80	2.2.2.2/32	8080	\N	\N	\N	806	45	2021-10-27 09:44:12.181187+00	2021-10-27 11:05:18.480753+00	2021-11-25	Successfully committed		unknown	ACTIVE	3
\.


--
-- Data for Name: route_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_dscp (id, route_id, matchdscp_id) FROM stdin;
\.


--
-- Data for Name: route_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_protocol (id, route_id, matchprotocol_id) FROM stdin;
1	1	1
2	2	1
\.


--
-- Data for Name: route_then; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_then (id, route_id, thenaction_id) FROM stdin;
1	1	3
2	2	3
\.


--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- Data for Name: techc_email; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.techc_email (id, email) FROM stdin;
\.


--
-- Data for Name: then_action; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.then_action (id, action, action_value) FROM stdin;
1	accept	\N
2	rate-limit	1G
3	discard	\N
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 3, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 3, true);


--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_peers_id_seq', 3, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 117, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 18, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 29, true);


--
-- Name: django_flatpage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_id_seq', 1, false);


--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_sites_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 35, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_fragmenttype_id_seq', 1, false);


--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_graph_id_seq', 1, true);


--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_validation_id_seq', 3, true);


--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_webhookmessage_id_seq', 1, false);


--
-- Name: match_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_dscp_id_seq', 1, false);


--
-- Name: match_port_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_port_id_seq', 1, false);


--
-- Name: match_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_protocol_id_seq', 3, true);


--
-- Name: peer_networks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_networks_id_seq', 4, true);


--
-- Name: peer_peer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_peer_id_seq', 2, true);


--
-- Name: peer_range_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_range_id_seq', 2, true);


--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_techc_emails_id_seq', 1, false);


--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peers_peernotify_id_seq', 1, false);


--
-- Name: route_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_dscp_id_seq', 1, false);


--
-- Name: route_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_id_seq', 2, true);


--
-- Name: route_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_protocol_id_seq', 2, true);


--
-- Name: route_then_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_then_id_seq', 2, true);


--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_sites_id_seq', 1, false);


--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- Name: techc_email_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.techc_email_id_seq', 1, false);


--
-- Name: then_action_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.then_action_id_seq', 3, true);


--
-- Name: account_emailaddress account_emailaddress_email_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_email_key UNIQUE (email);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq UNIQUE (userprofile_id, peer_id);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage django_flatpage_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage
    ADD CONSTRAINT django_flatpage_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage_sites django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq UNIQUE (flatpage_id, site_id);


--
-- Name: django_flatpage_sites django_flatpage_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: flowspec_fragmenttype flowspec_fragmenttype_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype
    ADD CONSTRAINT flowspec_fragmenttype_pkey PRIMARY KEY (id);


--
-- Name: flowspec_graph flowspec_graph_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_pkey PRIMARY KEY (id);


--
-- Name: flowspec_validation flowspec_validation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_pkey PRIMARY KEY (id);


--
-- Name: flowspec_webhookmessage flowspec_webhookmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_webhookmessage
    ADD CONSTRAINT flowspec_webhookmessage_pkey PRIMARY KEY (id);


--
-- Name: match_dscp match_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp
    ADD CONSTRAINT match_dscp_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_port_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_port_key UNIQUE (port);


--
-- Name: match_protocol match_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_pkey PRIMARY KEY (id);


--
-- Name: match_protocol match_protocol_protocol_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_protocol_key UNIQUE (protocol);


--
-- Name: peer_networks peer_networks_peer_id_peerrange_id_1404e3fe_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq UNIQUE (peer_id, peerrange_id);


--
-- Name: peer_networks peer_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_pkey PRIMARY KEY (id);


--
-- Name: peer peer_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer
    ADD CONSTRAINT peer_pkey PRIMARY KEY (peer_id);


--
-- Name: peer_range peer_range_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range
    ADD CONSTRAINT peer_range_pkey PRIMARY KEY (id);


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq UNIQUE (peer_id, techcemail_id);


--
-- Name: peer_techc_emails peer_techc_emails_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_pkey PRIMARY KEY (id);


--
-- Name: peers_peernotify peers_peernotify_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_route_id_matchdscp_id_bbb43797_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq UNIQUE (route_id, matchdscp_id);


--
-- Name: route route_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_route_id_matchprotocol_id_85c69018_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq UNIQUE (route_id, matchprotocol_id);


--
-- Name: route_then route_then_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_pkey PRIMARY KEY (id);


--
-- Name: route_then route_then_route_id_thenaction_id_82a54a0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq UNIQUE (route_id, thenaction_id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: techc_email techc_email_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email
    ADD CONSTRAINT techc_email_pkey PRIMARY KEY (id);


--
-- Name: then_action then_action_action_action_value_2bfee264_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_action_action_value_2bfee264_uniq UNIQUE (action, action_value);


--
-- Name: then_action then_action_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: accounts_userprofile_peers_peer_id_84acb941; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_peer_id_84acb941 ON public.accounts_userprofile_peers USING btree (peer_id);


--
-- Name: accounts_userprofile_peers_userprofile_id_2159c80a; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_userprofile_id_2159c80a ON public.accounts_userprofile_peers USING btree (userprofile_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_flatpage_sites_flatpage_id_078bbc8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_flatpage_id_078bbc8b ON public.django_flatpage_sites USING btree (flatpage_id);


--
-- Name: django_flatpage_sites_site_id_bfd8ea84; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_site_id_bfd8ea84 ON public.django_flatpage_sites USING btree (site_id);


--
-- Name: django_flatpage_url_41612362; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362 ON public.django_flatpage USING btree (url);


--
-- Name: django_flatpage_url_41612362_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362_like ON public.django_flatpage USING btree (url varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: flowspec_graph_route_id_3841b1c2; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_graph_route_id_3841b1c2 ON public.flowspec_graph USING btree (route_id);


--
-- Name: flowspec_validation_user_id_68741edf; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_validation_user_id_68741edf ON public.flowspec_validation USING btree (user_id);


--
-- Name: match_port_port_9d50baf9_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_port_port_9d50baf9_like ON public.match_port USING btree (port varchar_pattern_ops);


--
-- Name: match_protocol_protocol_6d7860e7_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_protocol_protocol_6d7860e7_like ON public.match_protocol USING btree (protocol varchar_pattern_ops);


--
-- Name: peer_networks_peer_id_9b1e48f9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peer_id_9b1e48f9 ON public.peer_networks USING btree (peer_id);


--
-- Name: peer_networks_peerrange_id_2647ea6f; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peerrange_id_2647ea6f ON public.peer_networks USING btree (peerrange_id);


--
-- Name: peer_techc_emails_peer_id_3c925438; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_peer_id_3c925438 ON public.peer_techc_emails USING btree (peer_id);


--
-- Name: peer_techc_emails_techcemail_id_a0dac283; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_techcemail_id_a0dac283 ON public.peer_techc_emails USING btree (techcemail_id);


--
-- Name: peers_peernotify_peer_id_b87bf62e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_peer_id_b87bf62e ON public.peers_peernotify USING btree (peer_id);


--
-- Name: peers_peernotify_user_id_0f09946d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_user_id_0f09946d ON public.peers_peernotify USING btree (user_id);


--
-- Name: route_applier_id_51f87ff7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_applier_id_51f87ff7 ON public.route USING btree (applier_id);


--
-- Name: route_dscp_matchdscp_id_f3e2c070; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_matchdscp_id_f3e2c070 ON public.route_dscp USING btree (matchdscp_id);


--
-- Name: route_dscp_route_id_3c9f515e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_route_id_3c9f515e ON public.route_dscp USING btree (route_id);


--
-- Name: route_name_d990cc6c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c ON public.route USING btree (name);


--
-- Name: route_name_d990cc6c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c_like ON public.route USING btree (name varchar_pattern_ops);


--
-- Name: route_protocol_matchprotocol_id_da93afcc; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_matchprotocol_id_da93afcc ON public.route_protocol USING btree (matchprotocol_id);


--
-- Name: route_protocol_route_id_de983cfe; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_route_id_de983cfe ON public.route_protocol USING btree (route_id);


--
-- Name: route_then_route_id_9ffa5b34; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_route_id_9ffa5b34 ON public.route_then USING btree (route_id);


--
-- Name: route_then_thenaction_id_584c41c9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_thenaction_id_584c41c9 ON public.route_then USING btree (thenaction_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_userprofile_id_2159c80a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_ FOREIGN KEY (userprofile_id) REFERENCES public.accounts_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl FOREIGN KEY (flatpage_id) REFERENCES public.django_flatpage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_graph flowspec_graph_route_id_3841b1c2_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_validation flowspec_validation_user_id_68741edf_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peer_id_9b1e48f9_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peerrange_id_2647ea6f_fk_peer_range_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id FOREIGN KEY (peerrange_id) REFERENCES public.peer_range(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_3c925438_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id FOREIGN KEY (techcemail_id) REFERENCES public.techc_email(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_user_id_0f09946d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route route_applier_id_51f87ff7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id FOREIGN KEY (applier_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id FOREIGN KEY (matchdscp_id) REFERENCES public.match_dscp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_route_id_3c9f515e_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id FOREIGN KEY (matchprotocol_id) REFERENCES public.match_protocol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_route_id_de983cfe_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_route_id_9ffa5b34_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_thenaction_id_584c41c9_fk_then_action_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id FOREIGN KEY (thenaction_id) REFERENCES public.then_action(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

