--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4 (Debian 13.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.2 (Debian 14.2-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id;
ALTER TABLE ONLY public.route_imdea_then DROP CONSTRAINT route_imdea_then_thenaction_id_443e7007_fk_then_action_id;
ALTER TABLE ONLY public.route_imdea_then DROP CONSTRAINT route_imdea_then_route_imdea_id_b8810d07_fk_route_imdea_id;
ALTER TABLE ONLY public.route_imdea_protocol DROP CONSTRAINT route_imdea_protocol_route_imdea_id_89f70c50_fk_route_imdea_id;
ALTER TABLE ONLY public.route_imdea_protocol DROP CONSTRAINT route_imdea_protocol_matchprotocol_id_19f5ad1c_fk_match_pro;
ALTER TABLE ONLY public.route_imdea_dscp DROP CONSTRAINT route_imdea_dscp_route_imdea_id_e6ca81f3_fk_route_imdea_id;
ALTER TABLE ONLY public.route_imdea_dscp DROP CONSTRAINT route_imdea_dscp_matchdscp_id_f600254f_fk_match_dscp_id;
ALTER TABLE ONLY public.route_imdea DROP CONSTRAINT route_imdea_applier_id_762f1ada_fk_auth_user_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id;
ALTER TABLE ONLY public.golem_historicalgolemattack DROP CONSTRAINT golem_historicalgole_history_user_id_f62e504e_fk_auth_user;
ALTER TABLE ONLY public.golem_golemattack DROP CONSTRAINT golem_golemattack_route_id_d40f292e_fk_route_id;
ALTER TABLE ONLY public.golem_golemattack DROP CONSTRAINT golem_golemattack_peer_id_f8a3a3d9_fk_peer_peer_id;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id;
ALTER TABLE ONLY public.flowspec_historicalroute_imdea DROP CONSTRAINT flowspec_historicalr_history_user_id_d81af5c3_fk_auth_user;
ALTER TABLE ONLY public.flowspec_historicalroute DROP CONSTRAINT flowspec_historicalr_history_user_id_07aaa509_fk_auth_user;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id;
DROP INDEX public.socialaccount_socialtoken_app_id_636a42d7;
DROP INDEX public.socialaccount_socialtoken_account_id_951f210e;
DROP INDEX public.socialaccount_socialapp_sites_socialapp_id_97fb6e7d;
DROP INDEX public.socialaccount_socialapp_sites_site_id_2579dee5;
DROP INDEX public.socialaccount_socialaccount_user_id_8146e70c;
DROP INDEX public.route_then_thenaction_id_584c41c9;
DROP INDEX public.route_then_route_id_9ffa5b34;
DROP INDEX public.route_protocol_route_id_de983cfe;
DROP INDEX public.route_protocol_matchprotocol_id_da93afcc;
DROP INDEX public.route_name_d990cc6c_like;
DROP INDEX public.route_name_d990cc6c;
DROP INDEX public.route_imdea_then_thenaction_id_443e7007;
DROP INDEX public.route_imdea_then_route_imdea_id_b8810d07;
DROP INDEX public.route_imdea_protocol_route_imdea_id_89f70c50;
DROP INDEX public.route_imdea_protocol_matchprotocol_id_19f5ad1c;
DROP INDEX public.route_imdea_name_a510b6c6_like;
DROP INDEX public.route_imdea_name_a510b6c6;
DROP INDEX public.route_imdea_dscp_route_imdea_id_e6ca81f3;
DROP INDEX public.route_imdea_dscp_matchdscp_id_f600254f;
DROP INDEX public.route_imdea_applier_id_762f1ada;
DROP INDEX public.route_dscp_route_id_3c9f515e;
DROP INDEX public.route_dscp_matchdscp_id_f3e2c070;
DROP INDEX public.route_applier_id_51f87ff7;
DROP INDEX public.peers_peernotify_user_id_0f09946d;
DROP INDEX public.peers_peernotify_peer_id_b87bf62e;
DROP INDEX public.peer_techc_emails_techcemail_id_a0dac283;
DROP INDEX public.peer_techc_emails_peer_id_3c925438;
DROP INDEX public.peer_networks_peerrange_id_2647ea6f;
DROP INDEX public.peer_networks_peer_id_9b1e48f9;
DROP INDEX public.match_protocol_protocol_6d7860e7_like;
DROP INDEX public.match_port_port_9d50baf9_like;
DROP INDEX public.golem_historicalgolemattack_route_id_adede7d0;
DROP INDEX public.golem_historicalgolemattack_peer_id_f90e24c5;
DROP INDEX public.golem_historicalgolemattack_id_ebdbd399;
DROP INDEX public.golem_historicalgolemattack_history_user_id_f62e504e;
DROP INDEX public.golem_golemattack_route_id_d40f292e;
DROP INDEX public.golem_golemattack_peer_id_f8a3a3d9;
DROP INDEX public.flowspec_validation_user_id_68741edf;
DROP INDEX public.flowspec_historicalroute_name_a3aeed1a_like;
DROP INDEX public.flowspec_historicalroute_name_a3aeed1a;
DROP INDEX public.flowspec_historicalroute_imdea_name_0a8da657_like;
DROP INDEX public.flowspec_historicalroute_imdea_name_0a8da657;
DROP INDEX public.flowspec_historicalroute_imdea_id_d97c965c;
DROP INDEX public.flowspec_historicalroute_imdea_history_user_id_d81af5c3;
DROP INDEX public.flowspec_historicalroute_imdea_applier_id_5ed5ad5e;
DROP INDEX public.flowspec_historicalroute_id_5d2f4a71;
DROP INDEX public.flowspec_historicalroute_history_user_id_07aaa509;
DROP INDEX public.flowspec_historicalroute_applier_id_f1af9f7f;
DROP INDEX public.flowspec_graph_route_id_3841b1c2;
DROP INDEX public.django_site_domain_a2e37b91_like;
DROP INDEX public.django_session_session_key_c0390e0f_like;
DROP INDEX public.django_session_expire_date_a5c62663;
DROP INDEX public.django_flatpage_url_41612362_like;
DROP INDEX public.django_flatpage_url_41612362;
DROP INDEX public.django_flatpage_sites_site_id_bfd8ea84;
DROP INDEX public.django_flatpage_sites_flatpage_id_078bbc8b;
DROP INDEX public.django_admin_log_user_id_c564eba6;
DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX public.authtoken_token_key_10f0b77e_like;
DROP INDEX public.auth_user_username_6821ab7c_like;
DROP INDEX public.auth_user_user_permissions_user_id_a95ead1b;
DROP INDEX public.auth_user_user_permissions_permission_id_1fbb5f2c;
DROP INDEX public.auth_user_groups_user_id_6a12ed8b;
DROP INDEX public.auth_user_groups_group_id_97559544;
DROP INDEX public.auth_permission_content_type_id_2f476e4b;
DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX public.auth_group_name_a6ea08ec_like;
DROP INDEX public.accounts_userprofile_peers_userprofile_id_2159c80a;
DROP INDEX public.accounts_userprofile_peers_peer_id_84acb941;
DROP INDEX public.account_emailconfirmation_key_f43612bd_like;
DROP INDEX public.account_emailconfirmation_email_address_id_5b7f8c58;
DROP INDEX public.account_emailaddress_user_id_2c513194;
DROP INDEX public.account_emailaddress_email_03be32b2_like;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_pkey;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_action_action_value_2bfee264_uniq;
ALTER TABLE ONLY public.techc_email DROP CONSTRAINT techc_email_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp_sites_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp DROP CONSTRAINT socialaccount_socialapp_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_pkey;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_pkey;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_pkey;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_pkey;
ALTER TABLE ONLY public.route_imdea_then DROP CONSTRAINT route_imdea_then_route_imdea_id_thenaction_id_6f2b3467_uniq;
ALTER TABLE ONLY public.route_imdea_then DROP CONSTRAINT route_imdea_then_pkey;
ALTER TABLE ONLY public.route_imdea_protocol DROP CONSTRAINT route_imdea_protocol_route_imdea_id_matchprot_3b559be5_uniq;
ALTER TABLE ONLY public.route_imdea_protocol DROP CONSTRAINT route_imdea_protocol_pkey;
ALTER TABLE ONLY public.route_imdea DROP CONSTRAINT route_imdea_pkey;
ALTER TABLE ONLY public.route_imdea_dscp DROP CONSTRAINT route_imdea_dscp_route_imdea_id_matchdscp_id_8ec26931_uniq;
ALTER TABLE ONLY public.route_imdea_dscp DROP CONSTRAINT route_imdea_dscp_pkey;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_pkey;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq;
ALTER TABLE ONLY public.peer_range DROP CONSTRAINT peer_range_pkey;
ALTER TABLE ONLY public.peer DROP CONSTRAINT peer_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_protocol_key;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_pkey;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_port_key;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_pkey;
ALTER TABLE ONLY public.match_dscp DROP CONSTRAINT match_dscp_pkey;
ALTER TABLE ONLY public.golem_historicalgolemattack DROP CONSTRAINT golem_historicalgolemattack_pkey;
ALTER TABLE ONLY public.golem_golemattack DROP CONSTRAINT golem_golemattack_pkey;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_pkey;
ALTER TABLE ONLY public.flowspec_historicalroute DROP CONSTRAINT flowspec_historicalroute_pkey;
ALTER TABLE ONLY public.flowspec_historicalroute_imdea DROP CONSTRAINT flowspec_historicalroute_imdea_pkey;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_pkey;
ALTER TABLE ONLY public.flowspec_fragmenttype DROP CONSTRAINT flowspec_fragmenttype_pkey;
ALTER TABLE ONLY public.flowspec_backup_signal DROP CONSTRAINT flowspec_backup_signal_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_domain_a2e37b91_uniq;
ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq;
ALTER TABLE ONLY public.django_flatpage DROP CONSTRAINT django_flatpage_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_key;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_username_key;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_pkey;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_pkey;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_key_key;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_pkey;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_email_key;
ALTER TABLE public.then_action ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.techc_email ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_then ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_imdea_then ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_imdea_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_imdea_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_imdea ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peers_peernotify ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_techc_emails ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_range ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_networks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer ALTER COLUMN peer_id DROP DEFAULT;
ALTER TABLE public.match_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_port ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.golem_historicalgolemattack ALTER COLUMN history_id DROP DEFAULT;
ALTER TABLE public.golem_golemattack ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_validation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_historicalroute_imdea ALTER COLUMN history_id DROP DEFAULT;
ALTER TABLE public.flowspec_historicalroute ALTER COLUMN history_id DROP DEFAULT;
ALTER TABLE public.flowspec_graph ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_fragmenttype ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_backup_signal ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_site ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_migrations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_content_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_admin_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_permission ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile_peers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailconfirmation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailaddress ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.then_action_id_seq;
DROP TABLE public.then_action;
DROP SEQUENCE public.techc_email_id_seq;
DROP TABLE public.techc_email;
DROP SEQUENCE public.socialaccount_socialtoken_id_seq;
DROP TABLE public.socialaccount_socialtoken;
DROP SEQUENCE public.socialaccount_socialapp_sites_id_seq;
DROP TABLE public.socialaccount_socialapp_sites;
DROP SEQUENCE public.socialaccount_socialapp_id_seq;
DROP TABLE public.socialaccount_socialapp;
DROP SEQUENCE public.socialaccount_socialaccount_id_seq;
DROP TABLE public.socialaccount_socialaccount;
DROP SEQUENCE public.route_then_id_seq;
DROP TABLE public.route_then;
DROP SEQUENCE public.route_protocol_id_seq;
DROP TABLE public.route_protocol;
DROP SEQUENCE public.route_imdea_then_id_seq;
DROP TABLE public.route_imdea_then;
DROP SEQUENCE public.route_imdea_protocol_id_seq;
DROP TABLE public.route_imdea_protocol;
DROP SEQUENCE public.route_imdea_id_seq;
DROP SEQUENCE public.route_imdea_dscp_id_seq;
DROP TABLE public.route_imdea_dscp;
DROP TABLE public.route_imdea;
DROP SEQUENCE public.route_id_seq;
DROP SEQUENCE public.route_dscp_id_seq;
DROP TABLE public.route_dscp;
DROP TABLE public.route;
DROP SEQUENCE public.peers_peernotify_id_seq;
DROP TABLE public.peers_peernotify;
DROP SEQUENCE public.peer_techc_emails_id_seq;
DROP TABLE public.peer_techc_emails;
DROP SEQUENCE public.peer_range_id_seq;
DROP TABLE public.peer_range;
DROP SEQUENCE public.peer_peer_id_seq;
DROP SEQUENCE public.peer_networks_id_seq;
DROP TABLE public.peer_networks;
DROP TABLE public.peer;
DROP SEQUENCE public.match_protocol_id_seq;
DROP TABLE public.match_protocol;
DROP SEQUENCE public.match_port_id_seq;
DROP TABLE public.match_port;
DROP SEQUENCE public.match_dscp_id_seq;
DROP TABLE public.match_dscp;
DROP SEQUENCE public.golem_historicalgolemattack_history_id_seq;
DROP TABLE public.golem_historicalgolemattack;
DROP SEQUENCE public.golem_golemattack_id_seq;
DROP TABLE public.golem_golemattack;
DROP SEQUENCE public.flowspec_validation_id_seq;
DROP TABLE public.flowspec_validation;
DROP SEQUENCE public.flowspec_historicalroute_imdea_history_id_seq;
DROP TABLE public.flowspec_historicalroute_imdea;
DROP SEQUENCE public.flowspec_historicalroute_history_id_seq;
DROP TABLE public.flowspec_historicalroute;
DROP SEQUENCE public.flowspec_graph_id_seq;
DROP TABLE public.flowspec_graph;
DROP SEQUENCE public.flowspec_fragmenttype_id_seq;
DROP TABLE public.flowspec_fragmenttype;
DROP SEQUENCE public.flowspec_backup_signal_id_seq;
DROP TABLE public.flowspec_backup_signal;
DROP SEQUENCE public.django_site_id_seq;
DROP TABLE public.django_site;
DROP TABLE public.django_session;
DROP SEQUENCE public.django_migrations_id_seq;
DROP TABLE public.django_migrations;
DROP SEQUENCE public.django_flatpage_sites_id_seq;
DROP TABLE public.django_flatpage_sites;
DROP SEQUENCE public.django_flatpage_id_seq;
DROP TABLE public.django_flatpage;
DROP SEQUENCE public.django_content_type_id_seq;
DROP TABLE public.django_content_type;
DROP SEQUENCE public.django_admin_log_id_seq;
DROP TABLE public.django_admin_log;
DROP TABLE public.authtoken_token;
DROP SEQUENCE public.auth_user_user_permissions_id_seq;
DROP TABLE public.auth_user_user_permissions;
DROP SEQUENCE public.auth_user_id_seq;
DROP SEQUENCE public.auth_user_groups_id_seq;
DROP TABLE public.auth_user_groups;
DROP TABLE public.auth_user;
DROP SEQUENCE public.auth_permission_id_seq;
DROP TABLE public.auth_permission;
DROP SEQUENCE public.auth_group_permissions_id_seq;
DROP TABLE public.auth_group_permissions;
DROP SEQUENCE public.auth_group_id_seq;
DROP TABLE public.auth_group;
DROP SEQUENCE public.accounts_userprofile_peers_id_seq;
DROP TABLE public.accounts_userprofile_peers;
DROP SEQUENCE public.accounts_userprofile_id_seq;
DROP TABLE public.accounts_userprofile;
DROP SEQUENCE public.account_emailconfirmation_id_seq;
DROP TABLE public.account_emailconfirmation;
DROP SEQUENCE public.account_emailaddress_id_seq;
DROP TABLE public.account_emailaddress;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailaddress_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailaddress_id_seq OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailaddress_id_seq OWNED BY public.account_emailaddress.id;


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailconfirmation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailconfirmation_id_seq OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailconfirmation_id_seq OWNED BY public.account_emailconfirmation.id;


--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile (
    id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_id_seq OWNED BY public.accounts_userprofile.id;


--
-- Name: accounts_userprofile_peers; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile_peers (
    id integer NOT NULL,
    userprofile_id integer NOT NULL,
    peer_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile_peers OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_peers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_peers_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_peers_id_seq OWNED BY public.accounts_userprofile_peers.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(255) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO fod;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_groups_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_groups_id_seq OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_groups_id_seq OWNED BY public.auth_user_groups.id;


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_id_seq OWNER TO fod;

--
-- Name: auth_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_id_seq OWNED BY public.auth_user.id;


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_user_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_user_permissions_id_seq OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_user_permissions_id_seq OWNED BY public.auth_user_user_permissions.id;


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO fod;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_admin_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_content_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_flatpage; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage (
    id integer NOT NULL,
    url character varying(100) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    enable_comments boolean NOT NULL,
    template_name character varying(70) NOT NULL,
    registration_required boolean NOT NULL
);


ALTER TABLE public.django_flatpage OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_id_seq OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_id_seq OWNED BY public.django_flatpage.id;


--
-- Name: django_flatpage_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage_sites (
    id integer NOT NULL,
    flatpage_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.django_flatpage_sites OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_sites_id_seq OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_sites_id_seq OWNED BY public.django_flatpage_sites.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fod;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_site_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_site_id_seq OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_site_id_seq OWNED BY public.django_site.id;


--
-- Name: flowspec_backup_signal; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_backup_signal (
    id integer NOT NULL,
    "boolean" boolean NOT NULL
);


ALTER TABLE public.flowspec_backup_signal OWNER TO fod;

--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_backup_signal_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_backup_signal_id_seq OWNER TO fod;

--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_backup_signal_id_seq OWNED BY public.flowspec_backup_signal.id;


--
-- Name: flowspec_fragmenttype; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_fragmenttype (
    id integer NOT NULL,
    fragmenttype character varying(20) NOT NULL
);


ALTER TABLE public.flowspec_fragmenttype OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_fragmenttype_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_fragmenttype_id_seq OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_fragmenttype_id_seq OWNED BY public.flowspec_fragmenttype.id;


--
-- Name: flowspec_graph; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_graph (
    id integer NOT NULL,
    graph_img character varying(200) NOT NULL,
    route_id integer NOT NULL
);


ALTER TABLE public.flowspec_graph OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_graph_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_graph_id_seq OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_graph_id_seq OWNED BY public.flowspec_graph.id;


--
-- Name: flowspec_historicalroute; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_historicalroute (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32),
    sourceport character varying(65535),
    destination character varying(32),
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    tcpflag character varying(50),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    applier_id integer,
    history_user_id integer
);


ALTER TABLE public.flowspec_historicalroute OWNER TO fod;

--
-- Name: flowspec_historicalroute_history_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_historicalroute_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_historicalroute_history_id_seq OWNER TO fod;

--
-- Name: flowspec_historicalroute_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_historicalroute_history_id_seq OWNED BY public.flowspec_historicalroute.history_id;


--
-- Name: flowspec_historicalroute_imdea; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_historicalroute_imdea (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32),
    sourceport character varying(65535),
    destination character varying(32),
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    tcpflag character varying(50),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    applier_id integer,
    history_user_id integer
);


ALTER TABLE public.flowspec_historicalroute_imdea OWNER TO fod;

--
-- Name: flowspec_historicalroute_imdea_history_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_historicalroute_imdea_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_historicalroute_imdea_history_id_seq OWNER TO fod;

--
-- Name: flowspec_historicalroute_imdea_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_historicalroute_imdea_history_id_seq OWNED BY public.flowspec_historicalroute_imdea.history_id;


--
-- Name: flowspec_validation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_validation (
    id integer NOT NULL,
    value character varying(10) NOT NULL,
    created_date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.flowspec_validation OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_validation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_validation_id_seq OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_validation_id_seq OWNED BY public.flowspec_validation.id;


--
-- Name: golem_golemattack; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.golem_golemattack (
    id integer NOT NULL,
    id_name character varying(50) NOT NULL,
    source inet NOT NULL,
    status character varying(50) NOT NULL,
    max_value double precision NOT NULL,
    threshold_value double precision NOT NULL,
    peer_id integer,
    route_id integer,
    received_at timestamp with time zone
);


ALTER TABLE public.golem_golemattack OWNER TO fod;

--
-- Name: golem_golemattack_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.golem_golemattack_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.golem_golemattack_id_seq OWNER TO fod;

--
-- Name: golem_golemattack_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.golem_golemattack_id_seq OWNED BY public.golem_golemattack.id;


--
-- Name: golem_historicalgolemattack; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.golem_historicalgolemattack (
    id integer NOT NULL,
    id_name character varying(50) NOT NULL,
    source inet NOT NULL,
    status character varying(50) NOT NULL,
    max_value double precision NOT NULL,
    threshold_value double precision NOT NULL,
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    history_user_id integer,
    peer_id integer,
    route_id integer,
    received_at timestamp with time zone
);


ALTER TABLE public.golem_historicalgolemattack OWNER TO fod;

--
-- Name: golem_historicalgolemattack_history_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.golem_historicalgolemattack_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.golem_historicalgolemattack_history_id_seq OWNER TO fod;

--
-- Name: golem_historicalgolemattack_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.golem_historicalgolemattack_history_id_seq OWNED BY public.golem_historicalgolemattack.history_id;


--
-- Name: match_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_dscp (
    id integer NOT NULL,
    dscp character varying(24) NOT NULL
);


ALTER TABLE public.match_dscp OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_dscp_id_seq OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_dscp_id_seq OWNED BY public.match_dscp.id;


--
-- Name: match_port; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_port (
    id integer NOT NULL,
    port character varying(24)
);


ALTER TABLE public.match_port OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_port_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_port_id_seq OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_port_id_seq OWNED BY public.match_port.id;


--
-- Name: match_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_protocol (
    id integer NOT NULL,
    protocol character varying(24) NOT NULL
);


ALTER TABLE public.match_protocol OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_protocol_id_seq OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_protocol_id_seq OWNED BY public.match_protocol.id;


--
-- Name: peer; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer (
    peer_id integer NOT NULL,
    peer_name character varying(128) NOT NULL,
    peer_as integer,
    peer_tag character varying(64) NOT NULL,
    domain_name character varying(128)
);


ALTER TABLE public.peer OWNER TO fod;

--
-- Name: peer_networks; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_networks (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    peerrange_id integer NOT NULL
);


ALTER TABLE public.peer_networks OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_networks_id_seq OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_networks_id_seq OWNED BY public.peer_networks.id;


--
-- Name: peer_peer_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_peer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_peer_id_seq OWNER TO fod;

--
-- Name: peer_peer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_peer_id_seq OWNED BY public.peer.peer_id;


--
-- Name: peer_range; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_range (
    id integer NOT NULL,
    network character varying(128) NOT NULL
);


ALTER TABLE public.peer_range OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_range_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_range_id_seq OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_range_id_seq OWNED BY public.peer_range.id;


--
-- Name: peer_techc_emails; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_techc_emails (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    techcemail_id integer NOT NULL
);


ALTER TABLE public.peer_techc_emails OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_techc_emails_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_techc_emails_id_seq OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_techc_emails_id_seq OWNED BY public.peer_techc_emails.id;


--
-- Name: peers_peernotify; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peers_peernotify (
    id integer NOT NULL,
    peer_activation_notified boolean NOT NULL,
    peer_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.peers_peernotify OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peers_peernotify_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peers_peernotify_id_seq OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peers_peernotify_id_seq OWNED BY public.peers_peernotify.id;


--
-- Name: route; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32),
    sourceport character varying(65535),
    destination character varying(32),
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    applier_id integer,
    tcpflag character varying(50)
);


ALTER TABLE public.route OWNER TO fod;

--
-- Name: route_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_dscp (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchdscp_id integer NOT NULL
);


ALTER TABLE public.route_dscp OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_dscp_id_seq OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_dscp_id_seq OWNED BY public.route_dscp.id;


--
-- Name: route_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_id_seq OWNER TO fod;

--
-- Name: route_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_id_seq OWNED BY public.route.id;


--
-- Name: route_imdea; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_imdea (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32),
    sourceport character varying(65535),
    destination character varying(32),
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    tcpflag character varying(50),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    applier_id integer
);


ALTER TABLE public.route_imdea OWNER TO fod;

--
-- Name: route_imdea_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_imdea_dscp (
    id integer NOT NULL,
    route_imdea_id integer NOT NULL,
    matchdscp_id integer NOT NULL
);


ALTER TABLE public.route_imdea_dscp OWNER TO fod;

--
-- Name: route_imdea_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_imdea_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_imdea_dscp_id_seq OWNER TO fod;

--
-- Name: route_imdea_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_imdea_dscp_id_seq OWNED BY public.route_imdea_dscp.id;


--
-- Name: route_imdea_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_imdea_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_imdea_id_seq OWNER TO fod;

--
-- Name: route_imdea_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_imdea_id_seq OWNED BY public.route_imdea.id;


--
-- Name: route_imdea_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_imdea_protocol (
    id integer NOT NULL,
    route_imdea_id integer NOT NULL,
    matchprotocol_id integer NOT NULL
);


ALTER TABLE public.route_imdea_protocol OWNER TO fod;

--
-- Name: route_imdea_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_imdea_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_imdea_protocol_id_seq OWNER TO fod;

--
-- Name: route_imdea_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_imdea_protocol_id_seq OWNED BY public.route_imdea_protocol.id;


--
-- Name: route_imdea_then; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_imdea_then (
    id integer NOT NULL,
    route_imdea_id integer NOT NULL,
    thenaction_id integer NOT NULL
);


ALTER TABLE public.route_imdea_then OWNER TO fod;

--
-- Name: route_imdea_then_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_imdea_then_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_imdea_then_id_seq OWNER TO fod;

--
-- Name: route_imdea_then_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_imdea_then_id_seq OWNED BY public.route_imdea_then.id;


--
-- Name: route_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_protocol (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchprotocol_id integer NOT NULL
);


ALTER TABLE public.route_protocol OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_protocol_id_seq OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_protocol_id_seq OWNED BY public.route_protocol.id;


--
-- Name: route_then; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_then (
    id integer NOT NULL,
    route_id integer NOT NULL,
    thenaction_id integer NOT NULL
);


ALTER TABLE public.route_then OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_then_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_then_id_seq OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_then_id_seq OWNED BY public.route_then.id;


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialaccount_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialaccount_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialaccount_id_seq OWNED BY public.socialaccount_socialaccount.id;


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_id_seq OWNED BY public.socialaccount_socialapp.id;


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id integer NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_sites_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_sites_id_seq OWNED BY public.socialaccount_socialapp_sites.id;


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialtoken_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialtoken_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialtoken_id_seq OWNED BY public.socialaccount_socialtoken.id;


--
-- Name: techc_email; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.techc_email (
    id integer NOT NULL,
    email character varying(352) NOT NULL
);


ALTER TABLE public.techc_email OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.techc_email_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.techc_email_id_seq OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.techc_email_id_seq OWNED BY public.techc_email.id;


--
-- Name: then_action; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.then_action (
    id integer NOT NULL,
    action character varying(60) NOT NULL,
    action_value character varying(255)
);


ALTER TABLE public.then_action OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.then_action_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.then_action_id_seq OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.then_action_id_seq OWNED BY public.then_action.id;


--
-- Name: account_emailaddress id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress ALTER COLUMN id SET DEFAULT nextval('public.account_emailaddress_id_seq'::regclass);


--
-- Name: account_emailconfirmation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation ALTER COLUMN id SET DEFAULT nextval('public.account_emailconfirmation_id_seq'::regclass);


--
-- Name: accounts_userprofile id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_id_seq'::regclass);


--
-- Name: accounts_userprofile_peers id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_peers_id_seq'::regclass);


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: auth_user id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user ALTER COLUMN id SET DEFAULT nextval('public.auth_user_id_seq'::regclass);


--
-- Name: auth_user_groups id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups ALTER COLUMN id SET DEFAULT nextval('public.auth_user_groups_id_seq'::regclass);


--
-- Name: auth_user_user_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_user_user_permissions_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_flatpage id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_id_seq'::regclass);


--
-- Name: django_flatpage_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_sites_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: django_site id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site ALTER COLUMN id SET DEFAULT nextval('public.django_site_id_seq'::regclass);


--
-- Name: flowspec_backup_signal id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_backup_signal ALTER COLUMN id SET DEFAULT nextval('public.flowspec_backup_signal_id_seq'::regclass);


--
-- Name: flowspec_fragmenttype id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype ALTER COLUMN id SET DEFAULT nextval('public.flowspec_fragmenttype_id_seq'::regclass);


--
-- Name: flowspec_graph id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph ALTER COLUMN id SET DEFAULT nextval('public.flowspec_graph_id_seq'::regclass);


--
-- Name: flowspec_historicalroute history_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute ALTER COLUMN history_id SET DEFAULT nextval('public.flowspec_historicalroute_history_id_seq'::regclass);


--
-- Name: flowspec_historicalroute_imdea history_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute_imdea ALTER COLUMN history_id SET DEFAULT nextval('public.flowspec_historicalroute_imdea_history_id_seq'::regclass);


--
-- Name: flowspec_validation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation ALTER COLUMN id SET DEFAULT nextval('public.flowspec_validation_id_seq'::regclass);


--
-- Name: golem_golemattack id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_golemattack ALTER COLUMN id SET DEFAULT nextval('public.golem_golemattack_id_seq'::regclass);


--
-- Name: golem_historicalgolemattack history_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_historicalgolemattack ALTER COLUMN history_id SET DEFAULT nextval('public.golem_historicalgolemattack_history_id_seq'::regclass);


--
-- Name: match_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp ALTER COLUMN id SET DEFAULT nextval('public.match_dscp_id_seq'::regclass);


--
-- Name: match_port id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port ALTER COLUMN id SET DEFAULT nextval('public.match_port_id_seq'::regclass);


--
-- Name: match_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol ALTER COLUMN id SET DEFAULT nextval('public.match_protocol_id_seq'::regclass);


--
-- Name: peer peer_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer ALTER COLUMN peer_id SET DEFAULT nextval('public.peer_peer_id_seq'::regclass);


--
-- Name: peer_networks id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks ALTER COLUMN id SET DEFAULT nextval('public.peer_networks_id_seq'::regclass);


--
-- Name: peer_range id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range ALTER COLUMN id SET DEFAULT nextval('public.peer_range_id_seq'::regclass);


--
-- Name: peer_techc_emails id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails ALTER COLUMN id SET DEFAULT nextval('public.peer_techc_emails_id_seq'::regclass);


--
-- Name: peers_peernotify id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify ALTER COLUMN id SET DEFAULT nextval('public.peers_peernotify_id_seq'::regclass);


--
-- Name: route id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route ALTER COLUMN id SET DEFAULT nextval('public.route_id_seq'::regclass);


--
-- Name: route_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp ALTER COLUMN id SET DEFAULT nextval('public.route_dscp_id_seq'::regclass);


--
-- Name: route_imdea id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea ALTER COLUMN id SET DEFAULT nextval('public.route_imdea_id_seq'::regclass);


--
-- Name: route_imdea_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_dscp ALTER COLUMN id SET DEFAULT nextval('public.route_imdea_dscp_id_seq'::regclass);


--
-- Name: route_imdea_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_protocol ALTER COLUMN id SET DEFAULT nextval('public.route_imdea_protocol_id_seq'::regclass);


--
-- Name: route_imdea_then id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_then ALTER COLUMN id SET DEFAULT nextval('public.route_imdea_then_id_seq'::regclass);


--
-- Name: route_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol ALTER COLUMN id SET DEFAULT nextval('public.route_protocol_id_seq'::regclass);


--
-- Name: route_then id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then ALTER COLUMN id SET DEFAULT nextval('public.route_then_id_seq'::regclass);


--
-- Name: socialaccount_socialaccount id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialaccount_id_seq'::regclass);


--
-- Name: socialaccount_socialapp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_id_seq'::regclass);


--
-- Name: socialaccount_socialapp_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_sites_id_seq'::regclass);


--
-- Name: socialaccount_socialtoken id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialtoken_id_seq'::regclass);


--
-- Name: techc_email id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email ALTER COLUMN id SET DEFAULT nextval('public.techc_email_id_seq'::regclass);


--
-- Name: then_action id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action ALTER COLUMN id SET DEFAULT nextval('public.then_action_id_seq'::regclass);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
2	root@root.com	t	f	2
3	alicarsan@gmail.com	t	t	3
4	david.rincon@imdea.org	t	f	4
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile (id, user_id) FROM stdin;
3	4
2	3
1	2
\.


--
-- Data for Name: accounts_userprofile_peers; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile_peers (id, userprofile_id, peer_id) FROM stdin;
4	2	1
7	3	4
8	1	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add log entry	7	add_logentry
26	Can change log entry	7	change_logentry
27	Can delete log entry	7	delete_logentry
28	Can view log entry	7	view_logentry
29	Can add flat page	8	add_flatpage
30	Can change flat page	8	change_flatpage
31	Can delete flat page	8	delete_flatpage
32	Can view flat page	8	view_flatpage
33	Can add Token	9	add_token
34	Can change Token	9	change_token
35	Can delete Token	9	delete_token
36	Can view Token	9	view_token
37	Can add token	10	add_tokenproxy
38	Can change token	10	change_tokenproxy
39	Can delete token	10	delete_tokenproxy
40	Can view token	10	view_tokenproxy
41	Can add fragment type	11	add_fragmenttype
42	Can change fragment type	11	change_fragmenttype
43	Can delete fragment type	11	delete_fragmenttype
44	Can view fragment type	11	view_fragmenttype
45	Can add match dscp	12	add_matchdscp
46	Can change match dscp	12	change_matchdscp
47	Can delete match dscp	12	delete_matchdscp
48	Can view match dscp	12	view_matchdscp
49	Can add match port	13	add_matchport
50	Can change match port	13	change_matchport
51	Can delete match port	13	delete_matchport
52	Can view match port	13	view_matchport
53	Can add match protocol	14	add_matchprotocol
54	Can change match protocol	14	change_matchprotocol
55	Can delete match protocol	14	delete_matchprotocol
56	Can view match protocol	14	view_matchprotocol
57	Can add webhook message	15	add_webhookmessage
58	Can change webhook message	15	change_webhookmessage
59	Can delete webhook message	15	delete_webhookmessage
60	Can view webhook message	15	view_webhookmessage
61	Can add validation	16	add_validation
62	Can change validation	16	change_validation
63	Can delete validation	16	delete_validation
64	Can view validation	16	view_validation
65	Can add then action	17	add_thenaction
66	Can change then action	17	change_thenaction
67	Can delete then action	17	delete_thenaction
68	Can view then action	17	view_thenaction
69	Can add Rule	18	add_route
70	Can change Rule	18	change_route
71	Can delete Rule	18	delete_route
72	Can view Rule	18	view_route
73	Can add graph	19	add_graph
74	Can change graph	19	change_graph
75	Can delete graph	19	delete_graph
76	Can view graph	19	view_graph
77	Can add geni events	20	add_genievents
78	Can change geni events	20	change_genievents
79	Can delete geni events	20	delete_genievents
80	Can view geni events	20	view_genievents
81	Can add attack event	21	add_attackevent
82	Can change attack event	21	change_attackevent
83	Can delete attack event	21	delete_attackevent
84	Can view attack event	21	view_attackevent
85	Can add backup_signal	22	add_backup_signal
86	Can change backup_signal	22	change_backup_signal
87	Can delete backup_signal	22	delete_backup_signal
88	Can view backup_signal	22	view_backup_signal
89	Can add peer	23	add_peer
90	Can change peer	23	change_peer
91	Can delete peer	23	delete_peer
92	Can view peer	23	view_peer
93	Can add peer range	24	add_peerrange
94	Can change peer range	24	change_peerrange
95	Can delete peer range	24	delete_peerrange
96	Can view peer range	24	view_peerrange
97	Can add techc email	25	add_techcemail
98	Can change techc email	25	change_techcemail
99	Can delete techc email	25	delete_techcemail
100	Can view techc email	25	view_techcemail
101	Can add peer notify	26	add_peernotify
102	Can change peer notify	26	change_peernotify
103	Can delete peer notify	26	delete_peernotify
104	Can view peer notify	26	view_peernotify
105	Can add user profile	27	add_userprofile
106	Can change user profile	27	change_userprofile
107	Can delete user profile	27	delete_userprofile
108	Can view user profile	27	view_userprofile
109	Can see registered users and rules	27	overview
110	Can add email address	28	add_emailaddress
111	Can change email address	28	change_emailaddress
112	Can delete email address	28	delete_emailaddress
113	Can view email address	28	view_emailaddress
114	Can add email confirmation	29	add_emailconfirmation
115	Can change email confirmation	29	change_emailconfirmation
116	Can delete email confirmation	29	delete_emailconfirmation
117	Can view email confirmation	29	view_emailconfirmation
118	Can add social account	30	add_socialaccount
119	Can change social account	30	change_socialaccount
120	Can delete social account	30	delete_socialaccount
121	Can view social account	30	view_socialaccount
122	Can add social application	31	add_socialapp
123	Can change social application	31	change_socialapp
124	Can delete social application	31	delete_socialapp
125	Can view social application	31	view_socialapp
126	Can add social application token	32	add_socialtoken
127	Can change social application token	32	change_socialtoken
128	Can delete social application token	32	delete_socialtoken
129	Can view social application token	32	view_socialtoken
130	Can add historical golem attack	33	add_historicalgolemattack
131	Can change historical golem attack	33	change_historicalgolemattack
132	Can delete historical golem attack	33	delete_historicalgolemattack
133	Can view historical golem attack	33	view_historicalgolemattack
134	Can add golem attack	34	add_golemattack
135	Can change golem attack	34	change_golemattack
136	Can delete golem attack	34	delete_golemattack
137	Can view golem attack	34	view_golemattack
138	Can add historical Rule	35	add_historicalroute
139	Can change historical Rule	35	change_historicalroute
140	Can delete historical Rule	35	delete_historicalroute
141	Can view historical Rule	35	view_historicalroute
142	Can add Rule IMDEA	36	add_route_imdea
143	Can change Rule IMDEA	36	change_route_imdea
144	Can delete Rule IMDEA	36	delete_route_imdea
145	Can view Rule IMDEA	36	view_route_imdea
146	Can add historical Rule IMDEA	37	add_historicalroute_imdea
147	Can change historical Rule IMDEA	37	change_historicalroute_imdea
148	Can delete historical Rule IMDEA	37	delete_historicalroute_imdea
149	Can view historical Rule IMDEA	37	view_historicalroute_imdea
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
4	pbkdf2_sha256$216000$qixgLO762J1d$tnVSiG+62YxsvzvtCBP8imXEbfP1wQbaH2nIpEdepFg=	2022-02-28 08:21:34.213326+00	t	drincon	David	Rincón	david.rincon@imdea.org	t	t	2022-01-31 11:09:13+00
3	pbkdf2_sha256$216000$4KXGLlFfxQpq$R447FvjnlvchdyAo9bnk6m0VAkpI1m4r6WJhix0JfBk=	2022-02-28 16:17:56.619599+00	f	Alicia	Alicia	Sánchez	alicarsan@gmail.com	f	t	2022-01-18 15:23:26+00
2	pbkdf2_sha256$216000$skQBge6RYJCU$sptVK0sHqc9YnwlDcZXQZckeEZhuvR6y1sQPOm/Yeyg=	2022-03-01 13:50:52.310801+00	t	root			root@root.com	t	t	2022-01-18 13:52:57.520828+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2022-01-18 13:55:59.853584+00	1	Administrador	3		3	2
2	2022-01-18 13:59:24.627816+00	1	1.1.1.1/32	1	[{"added": {}}]	24	2
3	2022-01-18 13:59:47.131018+00	2	2.2.2.2/32	1	[{"added": {}}]	24	2
4	2022-01-18 13:59:59.987056+00	1	UDP	1	[{"added": {}}]	14	2
5	2022-01-18 14:00:34.363229+00	2	TCP	1	[{"added": {}}]	14	2
6	2022-01-18 14:00:46.219057+00	3	ICMP	1	[{"added": {}}]	14	2
7	2022-01-18 14:00:53.02026+00	1	accept	1	[{"added": {}}]	17	2
8	2022-01-18 14:00:56.830005+00	2	discard	1	[{"added": {}}]	17	2
9	2022-01-18 14:01:05.442735+00	3	rate-limit:1GB	1	[{"added": {}}]	17	2
10	2022-01-18 14:01:16.65774+00	4	rate-limit:2G	1	[{"added": {}}]	17	2
11	2022-01-18 14:01:23.209966+00	3	rate-limit:1G	2	[{"changed": {"fields": ["Action Value"]}}]	17	2
12	2022-01-18 14:01:53.948138+00	5	rate-limit:3G	1	[{"added": {}}]	17	2
13	2022-01-18 14:03:10.547006+00	1	IMDEA	1	[{"added": {}}]	23	2
14	2022-01-18 14:03:49.149198+00	2	UAH	1	[{"added": {}}]	23	2
15	2022-01-18 14:12:19.062195+00	1	redifod.redimadrid.es	2	[{"changed": {"fields": ["Domain name", "Display name"]}}]	6	2
16	2022-01-18 14:28:19.252086+00	2	root@root.com	2	[{"changed": {"fields": ["Verified"]}}]	28	2
17	2022-01-18 14:28:41.42205+00	1	root	1	[{"added": {}}]	27	2
18	2022-01-18 14:28:51.870939+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
19	2022-01-18 14:46:07.828424+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
20	2022-01-18 14:46:22.696537+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
21	2022-01-18 15:29:07.204254+00	2	Alicia	1	[{"added": {}}]	27	2
22	2022-01-18 15:29:27.751061+00	3	Alicia	2	[{"changed": {"fields": ["First name", "Last name"]}}]	3	2
23	2022-01-18 15:39:07.475277+00	5	tcp	1	[{"added": {}}]	14	2
24	2022-01-18 15:39:12.326853+00	2	TCP	3		14	2
25	2022-01-18 15:39:17.535763+00	1	UDP	3		14	2
26	2022-01-18 15:39:22.120199+00	6	icmp	1	[{"added": {}}]	14	2
27	2022-01-18 15:39:26.813745+00	3	ICMP	3		14	2
28	2022-01-24 12:49:08.77234+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
29	2022-01-31 11:09:13.869448+00	4	drincon	1	[{"added": {}}, {"added": {"name": "user profile", "object": "drincon"}}]	3	2
30	2022-01-31 11:09:30.657927+00	4	drincon	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "Superuser status"]}}]	3	2
31	2022-01-31 11:09:59.650359+00	4	david.rincon@imdea.org	1	[{"added": {}}]	28	2
32	2022-01-31 11:18:55.690094+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
33	2022-01-31 11:19:31.261798+00	1	root	2	[]	27	2
34	2022-02-10 11:05:49.091023+00	3	193.145.15.29/32	1	[{"added": {}}]	24	2
35	2022-02-10 11:06:01.285885+00	1	IMDEA	2	[{"changed": {"fields": ["networks"]}}]	23	2
36	2022-02-24 10:50:09.869612+00	None	GolemAttack object (None)	1	[{"added": {}}]	34	2
37	2022-02-24 10:51:21.568557+00	1	GolemAttack object (1)	1	[{"added": {}}]	34	2
38	2022-02-25 11:02:10.792883+00	3	drincon	2	[]	27	2
39	2022-02-25 11:02:45.205172+00	4	drincon	2	[{"changed": {"fields": ["Staff status"]}}]	3	2
40	2022-02-25 11:06:21.755958+00	1	REM_IMDEA	2	[{"changed": {"fields": ["Peer name"]}}]	23	2
41	2022-02-25 11:06:28.44615+00	1	REM_IMDEA	2	[]	23	2
42	2022-02-25 11:07:17.978095+00	4	193.145.14.0/23	1	[{"added": {}}]	24	2
43	2022-02-25 11:07:32.815422+00	5	193.147.106.0/23	1	[{"added": {}}]	24	2
44	2022-02-25 11:07:52.339577+00	1	REM_IMDEA	2	[{"changed": {"fields": ["networks"]}}]	23	2
45	2022-02-25 11:09:12.892969+00	6	193.146.182.0/24	1	[{"added": {}}]	24	2
46	2022-02-25 11:09:29.521687+00	7	193.147.239.0/24	1	[{"added": {}}]	24	2
47	2022-02-25 11:09:43.639485+00	8	193.146.228.0/24	1	[{"added": {}}]	24	2
48	2022-02-25 11:10:05.852092+00	2	UEM	2	[{"changed": {"fields": ["Peer name", "networks"]}}]	23	2
49	2022-02-25 11:10:51.429944+00	3	CEU	1	[{"added": {}}]	23	2
50	2022-02-25 11:24:54.606629+00	9	193.147.107.24/32	1	[{"added": {}}]	24	2
51	2022-02-25 11:25:13.897173+00	4	Punch	1	[{"added": {}}]	23	2
52	2022-02-25 11:25:32.481748+00	3	drincon	2	[{"changed": {"fields": ["Peers"]}}]	27	2
53	2022-02-28 15:13:29.453691+00	2	Alicia	2	[]	27	2
54	2022-02-28 15:16:10.397314+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	admin	logentry
8	flatpages	flatpage
9	authtoken	token
10	authtoken	tokenproxy
11	flowspec	fragmenttype
12	flowspec	matchdscp
13	flowspec	matchport
14	flowspec	matchprotocol
15	flowspec	webhookmessage
16	flowspec	validation
17	flowspec	thenaction
18	flowspec	route
19	flowspec	graph
20	flowspec	genievents
21	flowspec	attackevent
22	flowspec	backup_signal
23	peers	peer
24	peers	peerrange
25	peers	techcemail
26	peers	peernotify
27	accounts	userprofile
28	account	emailaddress
29	account	emailconfirmation
30	socialaccount	socialaccount
31	socialaccount	socialapp
32	socialaccount	socialtoken
33	golem	historicalgolemattack
34	golem	golemattack
35	flowspec	historicalroute
36	flowspec	route_imdea
37	flowspec	historicalroute_imdea
\.


--
-- Data for Name: django_flatpage; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage (id, url, title, content, enable_comments, template_name, registration_required) FROM stdin;
\.


--
-- Data for Name: django_flatpage_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage_sites (id, flatpage_id, site_id) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2022-01-18 12:16:06.334675+00
2	auth	0001_initial	2022-01-18 12:16:08.874608+00
3	account	0001_initial	2022-01-18 12:16:13.814197+00
4	account	0002_email_max_length	2022-01-18 12:16:15.121677+00
5	peers	0001_initial	2022-01-18 12:16:16.937367+00
6	accounts	0001_initial	2022-01-18 12:16:19.25335+00
7	admin	0001_initial	2022-01-18 12:16:20.575582+00
8	admin	0002_logentry_remove_auto_add	2022-01-18 12:16:21.188746+00
9	admin	0003_logentry_add_action_flag_choices	2022-01-18 12:16:21.271551+00
10	contenttypes	0002_remove_content_type_name	2022-01-18 12:16:21.379424+00
11	auth	0002_alter_permission_name_max_length	2022-01-18 12:16:21.479843+00
12	auth	0003_alter_user_email_max_length	2022-01-18 12:16:21.574004+00
13	auth	0004_alter_user_username_opts	2022-01-18 12:16:21.66642+00
14	auth	0005_alter_user_last_login_null	2022-01-18 12:16:21.770757+00
15	auth	0006_require_contenttypes_0002	2022-01-18 12:16:21.867556+00
16	auth	0007_alter_validators_add_error_messages	2022-01-18 12:16:21.973758+00
17	auth	0008_alter_user_username_max_length	2022-01-18 12:16:22.357401+00
18	auth	0009_alter_user_last_name_max_length	2022-01-18 12:16:22.532069+00
19	auth	0010_alter_group_name_max_length	2022-01-18 12:16:22.629333+00
20	auth	0011_update_proxy_permissions	2022-01-18 12:16:22.730616+00
21	auth	0012_alter_user_first_name_max_length	2022-01-18 12:16:22.825093+00
22	auth	0013_auto_20220118_1216	2022-01-18 12:16:22.925686+00
23	authtoken	0001_initial	2022-01-18 12:16:24.0087+00
24	authtoken	0002_auto_20160226_1747	2022-01-18 12:16:24.87128+00
25	authtoken	0003_tokenproxy	2022-01-18 12:16:25.359798+00
26	sites	0001_initial	2022-01-18 12:16:26.226463+00
27	flatpages	0001_initial	2022-01-18 12:16:27.738351+00
28	flowspec	0001_initial	2022-01-18 12:16:36.312495+00
29	flowspec	0002_auto_20211027_1621	2022-01-18 12:16:41.089766+00
30	flowspec	0003_genievents	2022-01-18 12:16:41.416075+00
31	flowspec	0004_auto_20211125_1159	2022-01-18 12:16:41.575289+00
32	flowspec	0005_attackevent	2022-01-18 12:16:42.214191+00
33	flowspec	0006_auto_20211201_1616	2022-01-18 12:16:42.623546+00
34	flowspec	0007_auto_20211213_1627	2022-01-18 12:16:43.423325+00
35	flowspec	0008_auto_20211215_1043	2022-01-18 12:16:44.557033+00
36	flowspec	0009_backup_signal	2022-01-18 12:16:44.852711+00
37	flowspec	0010_auto_20220118_1211	2022-01-18 12:16:44.991552+00
38	longerusername	0001_initial	2022-01-18 12:16:45.081851+00
39	peers	0002_auto_20210603_1642	2022-01-18 12:16:45.225382+00
40	sessions	0001_initial	2022-01-18 12:16:46.188097+00
41	sites	0002_alter_domain_unique	2022-01-18 12:16:47.161043+00
42	socialaccount	0001_initial	2022-01-18 12:16:49.544317+00
43	socialaccount	0002_token_max_lengths	2022-01-18 12:16:52.245192+00
44	socialaccount	0003_extra_data_default_dict	2022-01-18 12:16:52.438119+00
45	auth	0013_auto_20220131_1107	2022-01-31 11:07:39.639712+00
46	auth	0013_auto_20220202_1647	2022-02-02 16:47:25.898329+00
47	auth	0013_auto_20220204_1056	2022-02-04 10:56:48.963474+00
48	flowspec	0011_auto_20220215_1100	2022-02-15 11:00:40.845645+00
49	auth	0013_auto_20220224_0926	2022-02-24 09:26:44.3857+00
50	golem	0001_initial	2022-02-24 09:26:44.5501+00
51	golem	0002_auto_20220224_1114	2022-02-24 11:15:49.497317+00
52	flowspec	0012_auto_20220224_1448	2022-02-24 14:48:40.289223+00
53	golem	0003_auto_20220225_1007	2022-02-25 10:07:49.585152+00
54	flowspec	0013_historicalroute	2022-02-25 10:27:22.258882+00
55	flowspec	0014_historicalroute_imdea_route_imdea	2022-02-28 10:10:20.488725+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
52an711e7xjpaqlpl8zpr6i90zz69ue2	eyJhY2NvdW50X3ZlcmlmaWVkX2VtYWlsIjpudWxsLCJhY2NvdW50X3VzZXIiOiIzIn0:1n9qKV:zPC7X9Fdx--IgAAOdTlwybTM36s3u5CyVUC2Y60l4kU	2022-02-01 15:23:27.865031+00
qfdqqr7osgm6q5gwd8be2admhdrruml3	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nD8Sw:z54uet9-WtnC8_3vJE2QI66_xTak556uuWaf7A6p-H0	2022-02-10 17:21:46.143965+00
n7lc5yutwg043emnrwh9nwqov3s7kpjx	.eJxVjMsKwjAUBf8lawlNmpcu3fsNIfdRG5VEmhYU8d-10IVuz8yZl4hpmce4NJ5iJnEQRux-N0h45bICuqRyrhJrmacMclXkRps8VeLbcXP_AmNq4_fdh9RrazV04II1QAqBnAreIytinZTCQAMhBLB7YxV6VCY5z0PQtndrtHFruZbIj3uenuLQvT-QLz88:1nObHi:vz3K8vM3fDy6onu36_GM2_9aPbXzuJfJBNek2L6lUSE	2022-03-14 08:21:34.308287+00
k3qqlsgpw2nrxjxy7rz8yyocqy7ofkxa	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nOjG6:HBqm6awcPlyxTHT3w2q1OkvSyV8P0WMnazuY51KgJX0	2022-03-14 16:52:26.874536+00
ml7nl4jpck6z1ffp87ftmbzp58vk01n1	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nP2tw:hFjQ8XXUp1FEpJpy4WHeLbYTZWHTUM26qYdz-Oy4fPg	2022-03-15 13:50:52.42591+00
l3k9wtdnuz8ur2o6y7v1w8sngdeiu9sj	.eJxVjMsKwjAUBf8lawlNmpcu3fsNIfdRG5VEmhYU8d-10IVuz8yZl4hpmce4NJ5iJnEQRux-N0h45bICuqRyrhJrmacMclXkRps8VeLbcXP_AmNq4_fdh9RrazV04II1QAqBnAreIytinZTCQAMhBLB7YxV6VCY5z0PQtndrtHFruZbIj3uenuLQvT-QLz88:1nEV08:YRZkdpO-PVdgbgfX3NKN5S4raT-fxqTFIJRs-1DE9g8	2022-02-14 11:37:40.353165+00
k6rwj4mpz5zrjldyj9gqpbs8fzann7q7	.eJxVjMsOwiAQRf-FtSHT8mq7dO83kAEGixow0CYa479rky50e8-558Usrsts10bVpsAmJtjhd3Por5Q3EC6Yz4X7kpeaHN8UvtPGTyXQ7bi7f4EZ2_x9k4mjj7p3EsEY752OXgVQUgkNMoJzCNB1IoAeUUghQuh6lAMOhggUbtFGraWSLT3uqT7ZBO8PmHo_IQ:1nEtzu:OomMlaqaTLlNmtl_YpAgb7d4kBH_2nlzcmdECtoc1M4	2022-02-15 14:19:06.295233+00
7u1bisa55ca0mcubtkf3r4t21hd8i01q	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nFaJX:uNLRa2MhMD8k6hRRtdWBIAcFlZtYYjip9XyzqtQcD-A	2022-02-17 11:30:11.195145+00
kcr9j15m0ab3x4nxmtsprs8e980qqr55	.eJxVjMsKwjAUBf8lawlNmpcu3fsNIfdRG5VEmhYU8d-10IVuz8yZl4hpmce4NJ5iJnEQRux-N0h45bICuqRyrhJrmacMclXkRps8VeLbcXP_AmNq4_fdh9RrazV04II1QAqBnAreIytinZTCQAMhBLB7YxV6VCY5z0PQtndrtHFruZbIj3uenuLQvT-QLz88:1nFvUy:cRID00nja0XLB2fIiwGrUishYf-iMq-YwZt8WExTGjI	2022-02-18 10:07:24.269462+00
8ibjdfhf5lgeyayxlh1db3acufbrttot	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nFx7G:ZuJBl4kZjjdcOHP3vqhl1HwmqumbjI5cE8wbdgzw55k	2022-02-18 11:51:02.275892+00
hupaov7bhmimv0z26b3mul2njf6zechw	.eJxVjMsOwiAQRf-FtSHT8mq7dO83kAEGixow0CYa479rky50e8-558Usrsts10bVpsAmJtjhd3Por5Q3EC6Yz4X7kpeaHN8UvtPGTyXQ7bi7f4EZ2_x9k4mjj7p3EsEY752OXgVQUgkNMoJzCNB1IoAeUUghQuh6lAMOhggUbtFGraWSLT3uqT7ZBO8PmHo_IQ:1nH5oc:mIS41sTrlrUTlyHhJCj3Vov7tZQjd_OWJxNFR7v9sXo	2022-02-21 15:20:30.93147+00
5bsu6r2p1obiifae5frwf1k7x4g4rbix	.eJxVjMsOwiAQRf-FtSHT8mq7dO83kAEGixow0CYa479rky50e8-558Usrsts10bVpsAmJtjhd3Por5Q3EC6Yz4X7kpeaHN8UvtPGTyXQ7bi7f4EZ2_x9k4mjj7p3EsEY752OXgVQUgkNMoJzCNB1IoAeUUghQuh6lAMOhggUbtFGraWSLT3uqT7ZBO8PmHo_IQ:1nH60m:MQL17n3UILVMvFQei-aCp9PNUeswhR1cG3X8zLo6Izo	2022-02-21 15:33:04.395547+00
xj22ex69gdqkekmyw1f8so2660a9jd6k	.eJxVjMsOwiAQRf-FtSHT8mq7dO83kAEGixow0CYa479rky50e8-558Usrsts10bVpsAmJtjhd3Por5Q3EC6Yz4X7kpeaHN8UvtPGTyXQ7bi7f4EZ2_x9k4mjj7p3EsEY752OXgVQUgkNMoJzCNB1IoAeUUghQuh6lAMOhggUbtFGraWSLT3uqT7ZBO8PmHo_IQ:1nHjKO:CqxN6gkSQLINMiJ6Ev9QIPiiihbSPaQxGeJR6ro-RQE	2022-02-23 09:31:56.512635+00
bbfqlc08x13bw6arovu5ijwq4l6ikvrz	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nJXLn:AK_ixQVyUuSfC5SDUPGeR6sBHIV1e8XxlGl09wJjbPc	2022-02-28 09:08:51.834743+00
f741l2jnj6lb2ku6i1jrtbxdgfqfwl3p	.eJxVjMsKwjAUBf8lawlNmpcu3fsNIfdRG5VEmhYU8d-10IVuz8yZl4hpmce4NJ5iJnEQRux-N0h45bICuqRyrhJrmacMclXkRps8VeLbcXP_AmNq4_fdh9RrazV04II1QAqBnAreIytinZTCQAMhBLB7YxV6VCY5z0PQtndrtHFruZbIj3uenuLQvT-QLz88:1nKzDn:7A1atsMa2Hf0ZbjkRKzepnYqEdTxE84rUeQoYX91niI	2022-03-04 09:06:35.337723+00
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_site (id, domain, name) FROM stdin;
1	redifod.redimadrid.es	RediFod
\.


--
-- Data for Name: flowspec_backup_signal; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_backup_signal (id, "boolean") FROM stdin;
1	f
\.


--
-- Data for Name: flowspec_fragmenttype; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_fragmenttype (id, fragmenttype) FROM stdin;
\.


--
-- Data for Name: flowspec_graph; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_graph (id, graph_img, route_id) FROM stdin;
\.


--
-- Data for Name: flowspec_historicalroute; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_historicalroute (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, tcpflag, filed, last_updated, expires, response, comments, requesters_address, status, history_id, history_date, history_change_reason, history_type, applier_id, history_user_id) FROM stdin;
6	tempty_field_IMDEA	193.145.15.29/32		0.0.0.0/32		\N	\N	\N	\N	\N	2022-02-15 11:01:38.279565+00	2022-02-28 06:01:06.198068+00	2022-02-16	Caught edit exception: statement not found: route tempty_field_IMDEA None		2a0c:5a80:3b0b:3400:413b:1b4f:e602:1081	INACTIVE	1	2022-02-28 09:50:55.727394+00	\N	-	3	2
4	fprueba_IMDEA	1.1.1.1/32	80	2.2.2.2/32	8080	\N	\N	\N	\N	\N	2022-02-07 15:24:05.088006+00	2022-02-28 06:01:02.018545+00	2022-02-10	Caught edit exception: statement not found: route fprueba_IMDEA None		2a0c:5a80:3b0b:3400:6183:fb0e:9df8:5412	INACTIVE	2	2022-02-28 09:50:55.731987+00	\N	-	3	2
3	Prueba-borra-4-2_IMDEA	1.1.1.1/32	80	2.2.2.2/32	80	\N	\N	\N	\N	\N	2022-02-03 08:22:08.396846+00	2022-02-28 06:01:00.983489+00	2022-02-04	Caught edit exception: statement not found: route Prueba-borra-4-2_IMDEA None		193.147.107.57	INACTIVE	3	2022-02-28 09:50:55.735429+00	\N	-	4	2
7	imcptest_UAH	0.0.0.0/32	40,80-100,200	1.1.1.1/32	80	\N	\N	\N	\N	\N	2022-02-22 10:12:44.992852+00	2022-02-28 15:07:11.111414+00	2022-02-28	Deactivating		188.26.223.37	INACTIVE	4	2022-02-28 15:07:11.200885+00	\N	~	3	2
7	imcptest_UAH	0.0.0.0/32	40,80-100,200	1.1.1.1/32	80	\N	\N	\N	\N	\N	2022-02-22 10:12:44.992852+00	2022-02-28 15:07:13.913444+00	2022-02-28	Successfully committed		188.26.223.37	INACTIVE	5	2022-02-28 15:07:14.022059+00	\N	~	3	2
8	ntestpuertos_IMDEA	0.0.0.0/32	80,8080	1.1.1.1/32	8080	\N	\N	\N	\N	\N	2022-02-22 10:47:25.669718+00	2022-03-01 06:01:00.957292+00	2022-02-23	Successfully committed		193.147.107.212	INACTIVE	6	2022-03-01 13:51:17.660191+00	\N	-	3	2
7	imcptest_UAH	0.0.0.0/32	40,80-100,200	1.1.1.1/32	80	\N	\N	\N	\N	\N	2022-02-22 10:12:44.992852+00	2022-03-01 06:01:02.07109+00	2022-02-28	Successfully committed		188.26.223.37	INACTIVE	7	2022-03-01 13:51:17.664312+00	\N	-	3	2
5	Prueba-Gafotas_IMDEA	0.0.0.0/0		193.145.15.29/32	22	\N	\N	\N	\N	\N	2022-02-10 11:08:22.416557+00	2022-03-01 06:01:03.201141+00	2022-02-26	Successfully committed		193.147.107.212	INACTIVE	8	2022-03-01 13:51:17.666641+00	\N	-	4	2
2	ntams_IMDEA	193.145.15.29/32	8080	1.1.1.1/32	443	\N	\N	\N	346	fin	2022-01-18 15:40:39.778491+00	2022-03-01 06:01:04.313396+00	2022-02-24	Successfully committed		193.147.107.212	INACTIVE	9	2022-03-01 13:51:17.669021+00	\N	-	3	2
\.


--
-- Data for Name: flowspec_historicalroute_imdea; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_historicalroute_imdea (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, tcpflag, filed, last_updated, expires, response, comments, requesters_address, status, history_id, history_date, history_change_reason, history_type, applier_id, history_user_id) FROM stdin;
1	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-02-28 15:43:58.612609+00	2022-02-28 15:43:58.612629+00	2022-03-02	Applying		188.26.223.37	PENDING	1	2022-02-28 15:43:58.723698+00	\N	+	3	2
2	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-02-28 16:05:16.990976+00	2022-02-28 16:05:16.990999+00	2022-03-02	Applying		188.26.223.37	PENDING	2	2022-02-28 16:05:17.080272+00	\N	+	3	2
2	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-02-28 16:05:16.990976+00	2022-02-28 16:05:16.990999+00	2022-03-02	Applying		188.26.223.37	PENDING	3	2022-02-28 16:06:14.753711+00	\N	-	3	2
1	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-02-28 15:43:58.612609+00	2022-02-28 15:43:58.612629+00	2022-03-02	Applying		188.26.223.37	PENDING	4	2022-02-28 16:06:14.755106+00	\N	-	3	2
3	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32	8080	\N	\N	\N	\N	\N	2022-02-28 16:19:31.995188+00	2022-02-28 16:19:31.995211+00	\N	Applying		188.26.223.37	PENDING	5	2022-02-28 16:19:32.093638+00	\N	+	3	3
3	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32	8080	\N	\N	\N	\N	\N	2022-02-28 16:19:31.995188+00	2022-02-28 16:19:34.904993+00	\N	Successfully committed		188.26.223.37	ACTIVE	6	2022-02-28 16:19:34.989226+00	\N	~	3	3
3	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32	8080	\N	\N	\N	\N	\N	2022-02-28 16:19:31.995188+00	2022-03-01 12:00:34.079145+00	2022-03-03	Applying		193.147.107.212	ACTIVE	7	2022-03-01 12:00:34.350338+00	\N	~	3	3
3	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32	8080	\N	\N	\N	\N	\N	2022-02-28 16:19:31.995188+00	2022-03-01 12:00:37.053888+00	2022-03-03	Successfully committed		193.147.107.212	ACTIVE	8	2022-03-01 12:00:37.139357+00	\N	~	3	3
4	test2_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-03-01 12:01:34.896915+00	2022-03-01 12:01:34.896936+00	2022-03-02	Applying		193.147.107.212	PENDING	9	2022-03-01 12:01:34.982666+00	\N	+	3	3
4	test2_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-03-01 12:01:34.896915+00	2022-03-01 12:01:37.892939+00	2022-03-02	Successfully committed		193.147.107.212	ACTIVE	10	2022-03-01 12:01:37.978648+00	\N	~	3	3
4	test2_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-03-01 12:01:34.896915+00	2022-03-01 12:04:36.099167+00	2022-03-01	Deactivating		193.147.107.212	INACTIVE	11	2022-03-01 12:04:36.203393+00	\N	~	3	3
4	test2_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-03-01 12:01:34.896915+00	2022-03-01 12:04:38.742475+00	2022-03-01	Successfully committed		193.147.107.212	INACTIVE	12	2022-03-01 12:04:38.837091+00	\N	~	3	3
4	test2_REM_IMDEA	0.0.0.0/32		193.145.15.29/32		\N	\N	\N	\N	\N	2022-03-01 12:01:34.896915+00	2022-03-01 12:04:38.742475+00	2022-03-01	Successfully committed		193.147.107.212	INACTIVE	13	2022-03-01 13:51:25.955364+00	\N	-	3	2
\.


--
-- Data for Name: flowspec_validation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_validation (id, value, created_date, user_id) FROM stdin;
71	kGRnk2	2022-03-01	3
72	c97VAg	2022-03-01	3
73	XWDMAX	2022-03-01	3
74	TjZ8Xj	2022-03-01	3
75	WCQt3w	2022-03-01	3
76	I36UQi	2022-03-01	3
77	SXJSFb	2022-03-01	3
78	rSY9VG	2022-03-01	3
79	R22ADJ	2022-03-01	3
80	UNCjbr	2022-03-01	3
81	tuYKnd	2022-03-01	3
82	EMsZwn	2022-03-01	3
83	kLtXm7	2022-03-01	3
84	Y3VJsU	2022-03-01	3
85	rWCYh8	2022-03-01	3
86	GCMVPT	2022-03-01	3
87	M3fw1Q	2022-03-01	3
88	XtkYZ9	2022-03-01	3
89	KKLuYx	2022-03-01	3
90	6w9Ra8	2022-03-01	3
91	kCDbbK	2022-03-01	3
92	IaWrpG	2022-03-01	3
93	bvzQSm	2022-03-01	3
94	b7UarU	2022-03-01	3
95	Xdhcp0	2022-03-01	3
96	zGXUXA	2022-03-01	3
97	QIZAsW	2022-03-01	3
98	74F4x5	2022-03-01	3
99	PTLaEJ	2022-03-01	3
100	k5M3hn	2022-03-01	3
101	60lxen	2022-03-01	3
102	HrrHJ6	2022-03-01	3
103	X1cWXb	2022-03-01	3
104	JLF4hh	2022-03-01	3
105	5M0j6H	2022-03-01	3
106	L6aFcL	2022-03-01	3
107	tBFw73	2022-03-01	3
108	MCzM5W	2022-03-01	3
109	M7act2	2022-03-01	3
110	nKEMj8	2022-03-01	3
111	hJQnsO	2022-03-01	3
112	WnuJtC	2022-03-01	3
113	kr9cPy	2022-03-01	3
114	KnlwHQ	2022-03-01	3
115	Fkk2fO	2022-03-01	3
116	fKaKGJ	2022-03-01	3
117	8dbv87	2022-03-01	3
118	4NX3ye	2022-03-01	3
119	5I9lUc	2022-03-01	3
120	HMa5IX	2022-03-01	3
121	sBo10K	2022-03-01	3
122	4rZzZv	2022-03-01	3
\.


--
-- Data for Name: golem_golemattack; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.golem_golemattack (id, id_name, source, status, max_value, threshold_value, peer_id, route_id, received_at) FROM stdin;
\.


--
-- Data for Name: golem_historicalgolemattack; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.golem_historicalgolemattack (id, id_name, source, status, max_value, threshold_value, history_id, history_date, history_change_reason, history_type, history_user_id, peer_id, route_id, received_at) FROM stdin;
1	A377936	193.146.58.180	Ongoing	264235306.66667	203800000	1	2022-02-24 10:51:21.565956+00	\N	+	2	2	7	\N
1	A377936	193.146.58.180	Ongoing	264235306.66667	203800000	2	2022-02-25 10:12:43.103899+00	\N	-	\N	2	7	2022-02-25 10:07:49.559827+00
\.


--
-- Data for Name: match_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_dscp (id, dscp) FROM stdin;
\.


--
-- Data for Name: match_port; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_port (id, port) FROM stdin;
\.


--
-- Data for Name: match_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_protocol (id, protocol) FROM stdin;
4	udp
5	tcp
6	icmp
\.


--
-- Data for Name: peer; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer (peer_id, peer_name, peer_as, peer_tag, domain_name) FROM stdin;
1	REM_IMDEA	\N	IMDEA SOFTWARE	\N
2	UEM	\N	Universidad Autónoma de Madrid	\N
3	CEU	\N	San Pablo, CEU	\N
4	Punch	\N	Testing	\N
\.


--
-- Data for Name: peer_networks; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_networks (id, peer_id, peerrange_id) FROM stdin;
1	1	1
2	1	2
3	2	1
4	2	2
5	1	3
6	1	4
7	1	5
8	2	6
9	2	7
10	3	8
11	4	9
\.


--
-- Data for Name: peer_range; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_range (id, network) FROM stdin;
1	1.1.1.1/32
2	2.2.2.2/32
3	193.145.15.29/32
4	193.145.14.0/23
5	193.147.106.0/23
6	193.146.182.0/24
7	193.147.239.0/24
8	193.146.228.0/24
9	193.147.107.24/32
\.


--
-- Data for Name: peer_techc_emails; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_techc_emails (id, peer_id, techcemail_id) FROM stdin;
\.


--
-- Data for Name: peers_peernotify; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peers_peernotify (id, peer_activation_notified, peer_id, user_id) FROM stdin;
\.


--
-- Data for Name: route; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, filed, last_updated, expires, response, comments, requesters_address, status, applier_id, tcpflag) FROM stdin;
\.


--
-- Data for Name: route_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_dscp (id, route_id, matchdscp_id) FROM stdin;
\.


--
-- Data for Name: route_imdea; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_imdea (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, tcpflag, filed, last_updated, expires, response, comments, requesters_address, status, applier_id) FROM stdin;
3	ttable_REM_IMDEA	0.0.0.0/32		193.145.15.29/32	8080	\N	\N	\N	\N	\N	2022-02-28 16:19:31.995188+00	2022-03-01 12:00:37.053888+00	2022-03-03	Successfully committed		193.147.107.212	ACTIVE	3
\.


--
-- Data for Name: route_imdea_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_imdea_dscp (id, route_imdea_id, matchdscp_id) FROM stdin;
\.


--
-- Data for Name: route_imdea_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_imdea_protocol (id, route_imdea_id, matchprotocol_id) FROM stdin;
3	3	5
\.


--
-- Data for Name: route_imdea_then; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_imdea_then (id, route_imdea_id, thenaction_id) FROM stdin;
3	3	2
\.


--
-- Data for Name: route_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_protocol (id, route_id, matchprotocol_id) FROM stdin;
\.


--
-- Data for Name: route_then; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_then (id, route_id, thenaction_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- Data for Name: techc_email; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.techc_email (id, email) FROM stdin;
\.


--
-- Data for Name: then_action; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.then_action (id, action, action_value) FROM stdin;
1	accept	\N
2	discard	\N
4	rate-limit	2G
3	rate-limit	1G
5	rate-limit	3G
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 4, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 3, true);


--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_peers_id_seq', 8, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 149, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 54, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 37, true);


--
-- Name: django_flatpage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_id_seq', 1, false);


--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_sites_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 55, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_backup_signal_id_seq', 1, true);


--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_fragmenttype_id_seq', 1, false);


--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_graph_id_seq', 86, true);


--
-- Name: flowspec_historicalroute_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_historicalroute_history_id_seq', 9, true);


--
-- Name: flowspec_historicalroute_imdea_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_historicalroute_imdea_history_id_seq', 13, true);


--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_validation_id_seq', 122, true);


--
-- Name: golem_golemattack_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.golem_golemattack_id_seq', 1, true);


--
-- Name: golem_historicalgolemattack_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.golem_historicalgolemattack_history_id_seq', 2, true);


--
-- Name: match_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_dscp_id_seq', 1, false);


--
-- Name: match_port_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_port_id_seq', 1, false);


--
-- Name: match_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_protocol_id_seq', 6, true);


--
-- Name: peer_networks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_networks_id_seq', 11, true);


--
-- Name: peer_peer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_peer_id_seq', 4, true);


--
-- Name: peer_range_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_range_id_seq', 9, true);


--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_techc_emails_id_seq', 1, false);


--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peers_peernotify_id_seq', 1, false);


--
-- Name: route_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_dscp_id_seq', 1, false);


--
-- Name: route_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_id_seq', 8, true);


--
-- Name: route_imdea_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_imdea_dscp_id_seq', 1, false);


--
-- Name: route_imdea_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_imdea_id_seq', 4, true);


--
-- Name: route_imdea_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_imdea_protocol_id_seq', 4, true);


--
-- Name: route_imdea_then_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_imdea_then_id_seq', 4, true);


--
-- Name: route_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_protocol_id_seq', 10, true);


--
-- Name: route_then_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_then_id_seq', 8, true);


--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_sites_id_seq', 1, false);


--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- Name: techc_email_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.techc_email_id_seq', 1, false);


--
-- Name: then_action_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.then_action_id_seq', 5, true);


--
-- Name: account_emailaddress account_emailaddress_email_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_email_key UNIQUE (email);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq UNIQUE (userprofile_id, peer_id);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage django_flatpage_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage
    ADD CONSTRAINT django_flatpage_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage_sites django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq UNIQUE (flatpage_id, site_id);


--
-- Name: django_flatpage_sites django_flatpage_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: flowspec_backup_signal flowspec_backup_signal_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_backup_signal
    ADD CONSTRAINT flowspec_backup_signal_pkey PRIMARY KEY (id);


--
-- Name: flowspec_fragmenttype flowspec_fragmenttype_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype
    ADD CONSTRAINT flowspec_fragmenttype_pkey PRIMARY KEY (id);


--
-- Name: flowspec_graph flowspec_graph_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_pkey PRIMARY KEY (id);


--
-- Name: flowspec_historicalroute_imdea flowspec_historicalroute_imdea_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute_imdea
    ADD CONSTRAINT flowspec_historicalroute_imdea_pkey PRIMARY KEY (history_id);


--
-- Name: flowspec_historicalroute flowspec_historicalroute_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute
    ADD CONSTRAINT flowspec_historicalroute_pkey PRIMARY KEY (history_id);


--
-- Name: flowspec_validation flowspec_validation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_pkey PRIMARY KEY (id);


--
-- Name: golem_golemattack golem_golemattack_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_golemattack
    ADD CONSTRAINT golem_golemattack_pkey PRIMARY KEY (id);


--
-- Name: golem_historicalgolemattack golem_historicalgolemattack_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_historicalgolemattack
    ADD CONSTRAINT golem_historicalgolemattack_pkey PRIMARY KEY (history_id);


--
-- Name: match_dscp match_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp
    ADD CONSTRAINT match_dscp_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_port_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_port_key UNIQUE (port);


--
-- Name: match_protocol match_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_pkey PRIMARY KEY (id);


--
-- Name: match_protocol match_protocol_protocol_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_protocol_key UNIQUE (protocol);


--
-- Name: peer_networks peer_networks_peer_id_peerrange_id_1404e3fe_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq UNIQUE (peer_id, peerrange_id);


--
-- Name: peer_networks peer_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_pkey PRIMARY KEY (id);


--
-- Name: peer peer_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer
    ADD CONSTRAINT peer_pkey PRIMARY KEY (peer_id);


--
-- Name: peer_range peer_range_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range
    ADD CONSTRAINT peer_range_pkey PRIMARY KEY (id);


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq UNIQUE (peer_id, techcemail_id);


--
-- Name: peer_techc_emails peer_techc_emails_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_pkey PRIMARY KEY (id);


--
-- Name: peers_peernotify peers_peernotify_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_route_id_matchdscp_id_bbb43797_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq UNIQUE (route_id, matchdscp_id);


--
-- Name: route_imdea_dscp route_imdea_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_dscp
    ADD CONSTRAINT route_imdea_dscp_pkey PRIMARY KEY (id);


--
-- Name: route_imdea_dscp route_imdea_dscp_route_imdea_id_matchdscp_id_8ec26931_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_dscp
    ADD CONSTRAINT route_imdea_dscp_route_imdea_id_matchdscp_id_8ec26931_uniq UNIQUE (route_imdea_id, matchdscp_id);


--
-- Name: route_imdea route_imdea_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea
    ADD CONSTRAINT route_imdea_pkey PRIMARY KEY (id);


--
-- Name: route_imdea_protocol route_imdea_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_protocol
    ADD CONSTRAINT route_imdea_protocol_pkey PRIMARY KEY (id);


--
-- Name: route_imdea_protocol route_imdea_protocol_route_imdea_id_matchprot_3b559be5_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_protocol
    ADD CONSTRAINT route_imdea_protocol_route_imdea_id_matchprot_3b559be5_uniq UNIQUE (route_imdea_id, matchprotocol_id);


--
-- Name: route_imdea_then route_imdea_then_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_then
    ADD CONSTRAINT route_imdea_then_pkey PRIMARY KEY (id);


--
-- Name: route_imdea_then route_imdea_then_route_imdea_id_thenaction_id_6f2b3467_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_then
    ADD CONSTRAINT route_imdea_then_route_imdea_id_thenaction_id_6f2b3467_uniq UNIQUE (route_imdea_id, thenaction_id);


--
-- Name: route route_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_route_id_matchprotocol_id_85c69018_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq UNIQUE (route_id, matchprotocol_id);


--
-- Name: route_then route_then_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_pkey PRIMARY KEY (id);


--
-- Name: route_then route_then_route_id_thenaction_id_82a54a0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq UNIQUE (route_id, thenaction_id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: techc_email techc_email_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email
    ADD CONSTRAINT techc_email_pkey PRIMARY KEY (id);


--
-- Name: then_action then_action_action_action_value_2bfee264_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_action_action_value_2bfee264_uniq UNIQUE (action, action_value);


--
-- Name: then_action then_action_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: accounts_userprofile_peers_peer_id_84acb941; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_peer_id_84acb941 ON public.accounts_userprofile_peers USING btree (peer_id);


--
-- Name: accounts_userprofile_peers_userprofile_id_2159c80a; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_userprofile_id_2159c80a ON public.accounts_userprofile_peers USING btree (userprofile_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_flatpage_sites_flatpage_id_078bbc8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_flatpage_id_078bbc8b ON public.django_flatpage_sites USING btree (flatpage_id);


--
-- Name: django_flatpage_sites_site_id_bfd8ea84; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_site_id_bfd8ea84 ON public.django_flatpage_sites USING btree (site_id);


--
-- Name: django_flatpage_url_41612362; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362 ON public.django_flatpage USING btree (url);


--
-- Name: django_flatpage_url_41612362_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362_like ON public.django_flatpage USING btree (url varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: flowspec_graph_route_id_3841b1c2; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_graph_route_id_3841b1c2 ON public.flowspec_graph USING btree (route_id);


--
-- Name: flowspec_historicalroute_applier_id_f1af9f7f; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_applier_id_f1af9f7f ON public.flowspec_historicalroute USING btree (applier_id);


--
-- Name: flowspec_historicalroute_history_user_id_07aaa509; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_history_user_id_07aaa509 ON public.flowspec_historicalroute USING btree (history_user_id);


--
-- Name: flowspec_historicalroute_id_5d2f4a71; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_id_5d2f4a71 ON public.flowspec_historicalroute USING btree (id);


--
-- Name: flowspec_historicalroute_imdea_applier_id_5ed5ad5e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_imdea_applier_id_5ed5ad5e ON public.flowspec_historicalroute_imdea USING btree (applier_id);


--
-- Name: flowspec_historicalroute_imdea_history_user_id_d81af5c3; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_imdea_history_user_id_d81af5c3 ON public.flowspec_historicalroute_imdea USING btree (history_user_id);


--
-- Name: flowspec_historicalroute_imdea_id_d97c965c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_imdea_id_d97c965c ON public.flowspec_historicalroute_imdea USING btree (id);


--
-- Name: flowspec_historicalroute_imdea_name_0a8da657; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_imdea_name_0a8da657 ON public.flowspec_historicalroute_imdea USING btree (name);


--
-- Name: flowspec_historicalroute_imdea_name_0a8da657_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_imdea_name_0a8da657_like ON public.flowspec_historicalroute_imdea USING btree (name varchar_pattern_ops);


--
-- Name: flowspec_historicalroute_name_a3aeed1a; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_name_a3aeed1a ON public.flowspec_historicalroute USING btree (name);


--
-- Name: flowspec_historicalroute_name_a3aeed1a_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_historicalroute_name_a3aeed1a_like ON public.flowspec_historicalroute USING btree (name varchar_pattern_ops);


--
-- Name: flowspec_validation_user_id_68741edf; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_validation_user_id_68741edf ON public.flowspec_validation USING btree (user_id);


--
-- Name: golem_golemattack_peer_id_f8a3a3d9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_golemattack_peer_id_f8a3a3d9 ON public.golem_golemattack USING btree (peer_id);


--
-- Name: golem_golemattack_route_id_d40f292e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_golemattack_route_id_d40f292e ON public.golem_golemattack USING btree (route_id);


--
-- Name: golem_historicalgolemattack_history_user_id_f62e504e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_historicalgolemattack_history_user_id_f62e504e ON public.golem_historicalgolemattack USING btree (history_user_id);


--
-- Name: golem_historicalgolemattack_id_ebdbd399; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_historicalgolemattack_id_ebdbd399 ON public.golem_historicalgolemattack USING btree (id);


--
-- Name: golem_historicalgolemattack_peer_id_f90e24c5; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_historicalgolemattack_peer_id_f90e24c5 ON public.golem_historicalgolemattack USING btree (peer_id);


--
-- Name: golem_historicalgolemattack_route_id_adede7d0; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX golem_historicalgolemattack_route_id_adede7d0 ON public.golem_historicalgolemattack USING btree (route_id);


--
-- Name: match_port_port_9d50baf9_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_port_port_9d50baf9_like ON public.match_port USING btree (port varchar_pattern_ops);


--
-- Name: match_protocol_protocol_6d7860e7_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_protocol_protocol_6d7860e7_like ON public.match_protocol USING btree (protocol varchar_pattern_ops);


--
-- Name: peer_networks_peer_id_9b1e48f9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peer_id_9b1e48f9 ON public.peer_networks USING btree (peer_id);


--
-- Name: peer_networks_peerrange_id_2647ea6f; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peerrange_id_2647ea6f ON public.peer_networks USING btree (peerrange_id);


--
-- Name: peer_techc_emails_peer_id_3c925438; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_peer_id_3c925438 ON public.peer_techc_emails USING btree (peer_id);


--
-- Name: peer_techc_emails_techcemail_id_a0dac283; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_techcemail_id_a0dac283 ON public.peer_techc_emails USING btree (techcemail_id);


--
-- Name: peers_peernotify_peer_id_b87bf62e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_peer_id_b87bf62e ON public.peers_peernotify USING btree (peer_id);


--
-- Name: peers_peernotify_user_id_0f09946d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_user_id_0f09946d ON public.peers_peernotify USING btree (user_id);


--
-- Name: route_applier_id_51f87ff7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_applier_id_51f87ff7 ON public.route USING btree (applier_id);


--
-- Name: route_dscp_matchdscp_id_f3e2c070; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_matchdscp_id_f3e2c070 ON public.route_dscp USING btree (matchdscp_id);


--
-- Name: route_dscp_route_id_3c9f515e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_route_id_3c9f515e ON public.route_dscp USING btree (route_id);


--
-- Name: route_imdea_applier_id_762f1ada; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_applier_id_762f1ada ON public.route_imdea USING btree (applier_id);


--
-- Name: route_imdea_dscp_matchdscp_id_f600254f; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_dscp_matchdscp_id_f600254f ON public.route_imdea_dscp USING btree (matchdscp_id);


--
-- Name: route_imdea_dscp_route_imdea_id_e6ca81f3; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_dscp_route_imdea_id_e6ca81f3 ON public.route_imdea_dscp USING btree (route_imdea_id);


--
-- Name: route_imdea_name_a510b6c6; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_name_a510b6c6 ON public.route_imdea USING btree (name);


--
-- Name: route_imdea_name_a510b6c6_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_name_a510b6c6_like ON public.route_imdea USING btree (name varchar_pattern_ops);


--
-- Name: route_imdea_protocol_matchprotocol_id_19f5ad1c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_protocol_matchprotocol_id_19f5ad1c ON public.route_imdea_protocol USING btree (matchprotocol_id);


--
-- Name: route_imdea_protocol_route_imdea_id_89f70c50; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_protocol_route_imdea_id_89f70c50 ON public.route_imdea_protocol USING btree (route_imdea_id);


--
-- Name: route_imdea_then_route_imdea_id_b8810d07; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_then_route_imdea_id_b8810d07 ON public.route_imdea_then USING btree (route_imdea_id);


--
-- Name: route_imdea_then_thenaction_id_443e7007; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_imdea_then_thenaction_id_443e7007 ON public.route_imdea_then USING btree (thenaction_id);


--
-- Name: route_name_d990cc6c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c ON public.route USING btree (name);


--
-- Name: route_name_d990cc6c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c_like ON public.route USING btree (name varchar_pattern_ops);


--
-- Name: route_protocol_matchprotocol_id_da93afcc; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_matchprotocol_id_da93afcc ON public.route_protocol USING btree (matchprotocol_id);


--
-- Name: route_protocol_route_id_de983cfe; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_route_id_de983cfe ON public.route_protocol USING btree (route_id);


--
-- Name: route_then_route_id_9ffa5b34; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_route_id_9ffa5b34 ON public.route_then USING btree (route_id);


--
-- Name: route_then_thenaction_id_584c41c9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_thenaction_id_584c41c9 ON public.route_then USING btree (thenaction_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_userprofile_id_2159c80a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_ FOREIGN KEY (userprofile_id) REFERENCES public.accounts_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl FOREIGN KEY (flatpage_id) REFERENCES public.django_flatpage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_graph flowspec_graph_route_id_3841b1c2_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_historicalroute flowspec_historicalr_history_user_id_07aaa509_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute
    ADD CONSTRAINT flowspec_historicalr_history_user_id_07aaa509_fk_auth_user FOREIGN KEY (history_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_historicalroute_imdea flowspec_historicalr_history_user_id_d81af5c3_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_historicalroute_imdea
    ADD CONSTRAINT flowspec_historicalr_history_user_id_d81af5c3_fk_auth_user FOREIGN KEY (history_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_validation flowspec_validation_user_id_68741edf_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: golem_golemattack golem_golemattack_peer_id_f8a3a3d9_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_golemattack
    ADD CONSTRAINT golem_golemattack_peer_id_f8a3a3d9_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: golem_golemattack golem_golemattack_route_id_d40f292e_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_golemattack
    ADD CONSTRAINT golem_golemattack_route_id_d40f292e_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: golem_historicalgolemattack golem_historicalgole_history_user_id_f62e504e_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.golem_historicalgolemattack
    ADD CONSTRAINT golem_historicalgole_history_user_id_f62e504e_fk_auth_user FOREIGN KEY (history_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peer_id_9b1e48f9_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peerrange_id_2647ea6f_fk_peer_range_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id FOREIGN KEY (peerrange_id) REFERENCES public.peer_range(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_3c925438_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id FOREIGN KEY (techcemail_id) REFERENCES public.techc_email(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_user_id_0f09946d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route route_applier_id_51f87ff7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id FOREIGN KEY (applier_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id FOREIGN KEY (matchdscp_id) REFERENCES public.match_dscp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_route_id_3c9f515e_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea route_imdea_applier_id_762f1ada_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea
    ADD CONSTRAINT route_imdea_applier_id_762f1ada_fk_auth_user_id FOREIGN KEY (applier_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_dscp route_imdea_dscp_matchdscp_id_f600254f_fk_match_dscp_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_dscp
    ADD CONSTRAINT route_imdea_dscp_matchdscp_id_f600254f_fk_match_dscp_id FOREIGN KEY (matchdscp_id) REFERENCES public.match_dscp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_dscp route_imdea_dscp_route_imdea_id_e6ca81f3_fk_route_imdea_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_dscp
    ADD CONSTRAINT route_imdea_dscp_route_imdea_id_e6ca81f3_fk_route_imdea_id FOREIGN KEY (route_imdea_id) REFERENCES public.route_imdea(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_protocol route_imdea_protocol_matchprotocol_id_19f5ad1c_fk_match_pro; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_protocol
    ADD CONSTRAINT route_imdea_protocol_matchprotocol_id_19f5ad1c_fk_match_pro FOREIGN KEY (matchprotocol_id) REFERENCES public.match_protocol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_protocol route_imdea_protocol_route_imdea_id_89f70c50_fk_route_imdea_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_protocol
    ADD CONSTRAINT route_imdea_protocol_route_imdea_id_89f70c50_fk_route_imdea_id FOREIGN KEY (route_imdea_id) REFERENCES public.route_imdea(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_then route_imdea_then_route_imdea_id_b8810d07_fk_route_imdea_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_then
    ADD CONSTRAINT route_imdea_then_route_imdea_id_b8810d07_fk_route_imdea_id FOREIGN KEY (route_imdea_id) REFERENCES public.route_imdea(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_imdea_then route_imdea_then_thenaction_id_443e7007_fk_then_action_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_imdea_then
    ADD CONSTRAINT route_imdea_then_thenaction_id_443e7007_fk_then_action_id FOREIGN KEY (thenaction_id) REFERENCES public.then_action(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id FOREIGN KEY (matchprotocol_id) REFERENCES public.match_protocol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_route_id_de983cfe_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_route_id_9ffa5b34_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_thenaction_id_584c41c9_fk_then_action_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id FOREIGN KEY (thenaction_id) REFERENCES public.then_action(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

