--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4 (Debian 13.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.1 (Debian 14.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id;
DROP INDEX public.socialaccount_socialtoken_app_id_636a42d7;
DROP INDEX public.socialaccount_socialtoken_account_id_951f210e;
DROP INDEX public.socialaccount_socialapp_sites_socialapp_id_97fb6e7d;
DROP INDEX public.socialaccount_socialapp_sites_site_id_2579dee5;
DROP INDEX public.socialaccount_socialaccount_user_id_8146e70c;
DROP INDEX public.route_then_thenaction_id_584c41c9;
DROP INDEX public.route_then_route_id_9ffa5b34;
DROP INDEX public.route_protocol_route_id_de983cfe;
DROP INDEX public.route_protocol_matchprotocol_id_da93afcc;
DROP INDEX public.route_name_d990cc6c_like;
DROP INDEX public.route_name_d990cc6c;
DROP INDEX public.route_dscp_route_id_3c9f515e;
DROP INDEX public.route_dscp_matchdscp_id_f3e2c070;
DROP INDEX public.route_applier_id_51f87ff7;
DROP INDEX public.peers_peernotify_user_id_0f09946d;
DROP INDEX public.peers_peernotify_peer_id_b87bf62e;
DROP INDEX public.peer_techc_emails_techcemail_id_a0dac283;
DROP INDEX public.peer_techc_emails_peer_id_3c925438;
DROP INDEX public.peer_networks_peerrange_id_2647ea6f;
DROP INDEX public.peer_networks_peer_id_9b1e48f9;
DROP INDEX public.match_protocol_protocol_6d7860e7_like;
DROP INDEX public.match_port_port_9d50baf9_like;
DROP INDEX public.flowspec_validation_user_id_68741edf;
DROP INDEX public.flowspec_graph_route_id_3841b1c2;
DROP INDEX public.flowspec_attackevent_id_attack_3b1c922c_like;
DROP INDEX public.django_site_domain_a2e37b91_like;
DROP INDEX public.django_session_session_key_c0390e0f_like;
DROP INDEX public.django_session_expire_date_a5c62663;
DROP INDEX public.django_flatpage_url_41612362_like;
DROP INDEX public.django_flatpage_url_41612362;
DROP INDEX public.django_flatpage_sites_site_id_bfd8ea84;
DROP INDEX public.django_flatpage_sites_flatpage_id_078bbc8b;
DROP INDEX public.django_admin_log_user_id_c564eba6;
DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX public.authtoken_token_key_10f0b77e_like;
DROP INDEX public.auth_user_username_6821ab7c_like;
DROP INDEX public.auth_user_user_permissions_user_id_a95ead1b;
DROP INDEX public.auth_user_user_permissions_permission_id_1fbb5f2c;
DROP INDEX public.auth_user_groups_user_id_6a12ed8b;
DROP INDEX public.auth_user_groups_group_id_97559544;
DROP INDEX public.auth_permission_content_type_id_2f476e4b;
DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX public.auth_group_name_a6ea08ec_like;
DROP INDEX public.accounts_userprofile_peers_userprofile_id_2159c80a;
DROP INDEX public.accounts_userprofile_peers_peer_id_84acb941;
DROP INDEX public.account_emailconfirmation_key_f43612bd_like;
DROP INDEX public.account_emailconfirmation_email_address_id_5b7f8c58;
DROP INDEX public.account_emailaddress_user_id_2c513194;
DROP INDEX public.account_emailaddress_email_03be32b2_like;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_pkey;
ALTER TABLE ONLY public.then_action DROP CONSTRAINT then_action_action_action_value_2bfee264_uniq;
ALTER TABLE ONLY public.techc_email DROP CONSTRAINT techc_email_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_pkey;
ALTER TABLE ONLY public.socialaccount_socialtoken DROP CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp_sites_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp DROP CONSTRAINT socialaccount_socialapp_pkey;
ALTER TABLE ONLY public.socialaccount_socialapp_sites DROP CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq;
ALTER TABLE ONLY public.socialaccount_socialaccount DROP CONSTRAINT socialaccount_socialaccount_pkey;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq;
ALTER TABLE ONLY public.route_then DROP CONSTRAINT route_then_pkey;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq;
ALTER TABLE ONLY public.route_protocol DROP CONSTRAINT route_protocol_pkey;
ALTER TABLE ONLY public.route DROP CONSTRAINT route_pkey;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq;
ALTER TABLE ONLY public.route_dscp DROP CONSTRAINT route_dscp_pkey;
ALTER TABLE ONLY public.peers_peernotify DROP CONSTRAINT peers_peernotify_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_pkey;
ALTER TABLE ONLY public.peer_techc_emails DROP CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq;
ALTER TABLE ONLY public.peer_range DROP CONSTRAINT peer_range_pkey;
ALTER TABLE ONLY public.peer DROP CONSTRAINT peer_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_pkey;
ALTER TABLE ONLY public.peer_networks DROP CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_protocol_key;
ALTER TABLE ONLY public.match_protocol DROP CONSTRAINT match_protocol_pkey;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_port_key;
ALTER TABLE ONLY public.match_port DROP CONSTRAINT match_port_pkey;
ALTER TABLE ONLY public.match_dscp DROP CONSTRAINT match_dscp_pkey;
ALTER TABLE ONLY public.flowspec_webhookmessage DROP CONSTRAINT flowspec_webhookmessage_pkey;
ALTER TABLE ONLY public.flowspec_validation DROP CONSTRAINT flowspec_validation_pkey;
ALTER TABLE ONLY public.flowspec_graph DROP CONSTRAINT flowspec_graph_pkey;
ALTER TABLE ONLY public.flowspec_genievents DROP CONSTRAINT flowspec_genievents_pkey;
ALTER TABLE ONLY public.flowspec_fragmenttype DROP CONSTRAINT flowspec_fragmenttype_pkey;
ALTER TABLE ONLY public.flowspec_backup_signal DROP CONSTRAINT flowspec_backup_signal_pkey;
ALTER TABLE ONLY public.flowspec_attackevent DROP CONSTRAINT flowspec_attackevent_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_pkey;
ALTER TABLE ONLY public.django_site DROP CONSTRAINT django_site_domain_a2e37b91_uniq;
ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_pkey;
ALTER TABLE ONLY public.django_flatpage_sites DROP CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq;
ALTER TABLE ONLY public.django_flatpage DROP CONSTRAINT django_flatpage_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_key;
ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_username_key;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq;
ALTER TABLE ONLY public.auth_user_user_permissions DROP CONSTRAINT auth_user_user_permissions_pkey;
ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_pkey;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq;
ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_user_id_key;
ALTER TABLE ONLY public.accounts_userprofile DROP CONSTRAINT accounts_userprofile_pkey;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq;
ALTER TABLE ONLY public.accounts_userprofile_peers DROP CONSTRAINT accounts_userprofile_peers_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_pkey;
ALTER TABLE ONLY public.account_emailconfirmation DROP CONSTRAINT account_emailconfirmation_key_key;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_pkey;
ALTER TABLE ONLY public.account_emailaddress DROP CONSTRAINT account_emailaddress_email_key;
ALTER TABLE public.then_action ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.techc_email ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_then ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.route ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peers_peernotify ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_techc_emails ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_range ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer_networks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.peer ALTER COLUMN peer_id DROP DEFAULT;
ALTER TABLE public.match_protocol ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_port ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.match_dscp ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_webhookmessage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_validation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_graph ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_genievents ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_fragmenttype ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flowspec_backup_signal ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_site ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_migrations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage_sites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_flatpage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_content_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_admin_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_user ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_permission ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile_peers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.accounts_userprofile ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailconfirmation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.account_emailaddress ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.then_action_id_seq;
DROP TABLE public.then_action;
DROP SEQUENCE public.techc_email_id_seq;
DROP TABLE public.techc_email;
DROP SEQUENCE public.socialaccount_socialtoken_id_seq;
DROP TABLE public.socialaccount_socialtoken;
DROP SEQUENCE public.socialaccount_socialapp_sites_id_seq;
DROP TABLE public.socialaccount_socialapp_sites;
DROP SEQUENCE public.socialaccount_socialapp_id_seq;
DROP TABLE public.socialaccount_socialapp;
DROP SEQUENCE public.socialaccount_socialaccount_id_seq;
DROP TABLE public.socialaccount_socialaccount;
DROP SEQUENCE public.route_then_id_seq;
DROP TABLE public.route_then;
DROP SEQUENCE public.route_protocol_id_seq;
DROP TABLE public.route_protocol;
DROP SEQUENCE public.route_id_seq;
DROP SEQUENCE public.route_dscp_id_seq;
DROP TABLE public.route_dscp;
DROP TABLE public.route;
DROP SEQUENCE public.peers_peernotify_id_seq;
DROP TABLE public.peers_peernotify;
DROP SEQUENCE public.peer_techc_emails_id_seq;
DROP TABLE public.peer_techc_emails;
DROP SEQUENCE public.peer_range_id_seq;
DROP TABLE public.peer_range;
DROP SEQUENCE public.peer_peer_id_seq;
DROP SEQUENCE public.peer_networks_id_seq;
DROP TABLE public.peer_networks;
DROP TABLE public.peer;
DROP SEQUENCE public.match_protocol_id_seq;
DROP TABLE public.match_protocol;
DROP SEQUENCE public.match_port_id_seq;
DROP TABLE public.match_port;
DROP SEQUENCE public.match_dscp_id_seq;
DROP TABLE public.match_dscp;
DROP SEQUENCE public.flowspec_webhookmessage_id_seq;
DROP TABLE public.flowspec_webhookmessage;
DROP SEQUENCE public.flowspec_validation_id_seq;
DROP TABLE public.flowspec_validation;
DROP SEQUENCE public.flowspec_graph_id_seq;
DROP TABLE public.flowspec_graph;
DROP SEQUENCE public.flowspec_genievents_id_seq;
DROP TABLE public.flowspec_genievents;
DROP SEQUENCE public.flowspec_fragmenttype_id_seq;
DROP TABLE public.flowspec_fragmenttype;
DROP SEQUENCE public.flowspec_backup_signal_id_seq;
DROP TABLE public.flowspec_backup_signal;
DROP TABLE public.flowspec_attackevent;
DROP SEQUENCE public.django_site_id_seq;
DROP TABLE public.django_site;
DROP TABLE public.django_session;
DROP SEQUENCE public.django_migrations_id_seq;
DROP TABLE public.django_migrations;
DROP SEQUENCE public.django_flatpage_sites_id_seq;
DROP TABLE public.django_flatpage_sites;
DROP SEQUENCE public.django_flatpage_id_seq;
DROP TABLE public.django_flatpage;
DROP SEQUENCE public.django_content_type_id_seq;
DROP TABLE public.django_content_type;
DROP SEQUENCE public.django_admin_log_id_seq;
DROP TABLE public.django_admin_log;
DROP TABLE public.authtoken_token;
DROP SEQUENCE public.auth_user_user_permissions_id_seq;
DROP TABLE public.auth_user_user_permissions;
DROP SEQUENCE public.auth_user_id_seq;
DROP SEQUENCE public.auth_user_groups_id_seq;
DROP TABLE public.auth_user_groups;
DROP TABLE public.auth_user;
DROP SEQUENCE public.auth_permission_id_seq;
DROP TABLE public.auth_permission;
DROP SEQUENCE public.auth_group_permissions_id_seq;
DROP TABLE public.auth_group_permissions;
DROP SEQUENCE public.auth_group_id_seq;
DROP TABLE public.auth_group;
DROP SEQUENCE public.accounts_userprofile_peers_id_seq;
DROP TABLE public.accounts_userprofile_peers;
DROP SEQUENCE public.accounts_userprofile_id_seq;
DROP TABLE public.accounts_userprofile;
DROP SEQUENCE public.account_emailconfirmation_id_seq;
DROP TABLE public.account_emailconfirmation;
DROP SEQUENCE public.account_emailaddress_id_seq;
DROP TABLE public.account_emailaddress;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailaddress_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailaddress_id_seq OWNER TO fod;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailaddress_id_seq OWNED BY public.account_emailaddress.id;


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.account_emailconfirmation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_emailconfirmation_id_seq OWNER TO fod;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.account_emailconfirmation_id_seq OWNED BY public.account_emailconfirmation.id;


--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile (
    id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_id_seq OWNED BY public.accounts_userprofile.id;


--
-- Name: accounts_userprofile_peers; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.accounts_userprofile_peers (
    id integer NOT NULL,
    userprofile_id integer NOT NULL,
    peer_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile_peers OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.accounts_userprofile_peers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.accounts_userprofile_peers_id_seq OWNER TO fod;

--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.accounts_userprofile_peers_id_seq OWNED BY public.accounts_userprofile_peers.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO fod;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO fod;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO fod;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(255) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO fod;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_groups_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_groups_id_seq OWNER TO fod;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_groups_id_seq OWNED BY public.auth_user_groups.id;


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_id_seq OWNER TO fod;

--
-- Name: auth_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_id_seq OWNED BY public.auth_user.id;


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.auth_user_user_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_user_permissions_id_seq OWNER TO fod;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.auth_user_user_permissions_id_seq OWNED BY public.auth_user_user_permissions.id;


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO fod;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_admin_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO fod;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_content_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO fod;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_flatpage; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage (
    id integer NOT NULL,
    url character varying(100) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    enable_comments boolean NOT NULL,
    template_name character varying(70) NOT NULL,
    registration_required boolean NOT NULL
);


ALTER TABLE public.django_flatpage OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_id_seq OWNER TO fod;

--
-- Name: django_flatpage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_id_seq OWNED BY public.django_flatpage.id;


--
-- Name: django_flatpage_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_flatpage_sites (
    id integer NOT NULL,
    flatpage_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.django_flatpage_sites OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_flatpage_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_flatpage_sites_id_seq OWNER TO fod;

--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_flatpage_sites_id_seq OWNED BY public.django_flatpage_sites.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO fod;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fod;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.django_site_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_site_id_seq OWNER TO fod;

--
-- Name: django_site_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.django_site_id_seq OWNED BY public.django_site.id;


--
-- Name: flowspec_attackevent; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_attackevent (
    id_attack character varying(10) NOT NULL,
    name_attack character varying(35) NOT NULL,
    status character varying(35) NOT NULL,
    max_value character varying(50) NOT NULL,
    threshold_value character varying(50) NOT NULL,
    severity character varying(35),
    traffic_characteristics jsonb,
    network_characteristics jsonb,
    received_at timestamp with time zone NOT NULL,
    institution_name character varying(50),
    ip_attacked character varying(50)
);


ALTER TABLE public.flowspec_attackevent OWNER TO fod;

--
-- Name: flowspec_backup_signal; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_backup_signal (
    id integer NOT NULL,
    "boolean" boolean NOT NULL
);


ALTER TABLE public.flowspec_backup_signal OWNER TO fod;

--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_backup_signal_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_backup_signal_id_seq OWNER TO fod;

--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_backup_signal_id_seq OWNED BY public.flowspec_backup_signal.id;


--
-- Name: flowspec_fragmenttype; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_fragmenttype (
    id integer NOT NULL,
    fragmenttype character varying(20) NOT NULL
);


ALTER TABLE public.flowspec_fragmenttype OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_fragmenttype_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_fragmenttype_id_seq OWNER TO fod;

--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_fragmenttype_id_seq OWNED BY public.flowspec_fragmenttype.id;


--
-- Name: flowspec_genievents; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_genievents (
    id integer NOT NULL,
    received_at timestamp with time zone NOT NULL,
    event jsonb,
    network_characteristics jsonb,
    traffic_characteristics jsonb
);


ALTER TABLE public.flowspec_genievents OWNER TO fod;

--
-- Name: flowspec_genievents_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_genievents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_genievents_id_seq OWNER TO fod;

--
-- Name: flowspec_genievents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_genievents_id_seq OWNED BY public.flowspec_genievents.id;


--
-- Name: flowspec_graph; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_graph (
    id integer NOT NULL,
    graph_img character varying(200) NOT NULL,
    route_id integer NOT NULL
);


ALTER TABLE public.flowspec_graph OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_graph_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_graph_id_seq OWNER TO fod;

--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_graph_id_seq OWNED BY public.flowspec_graph.id;


--
-- Name: flowspec_validation; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_validation (
    id integer NOT NULL,
    value character varying(10) NOT NULL,
    created_date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.flowspec_validation OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_validation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_validation_id_seq OWNER TO fod;

--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_validation_id_seq OWNED BY public.flowspec_validation.id;


--
-- Name: flowspec_webhookmessage; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.flowspec_webhookmessage (
    id integer NOT NULL,
    received_at timestamp with time zone NOT NULL,
    message jsonb
);


ALTER TABLE public.flowspec_webhookmessage OWNER TO fod;

--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.flowspec_webhookmessage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flowspec_webhookmessage_id_seq OWNER TO fod;

--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.flowspec_webhookmessage_id_seq OWNED BY public.flowspec_webhookmessage.id;


--
-- Name: match_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_dscp (
    id integer NOT NULL,
    dscp character varying(24) NOT NULL
);


ALTER TABLE public.match_dscp OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_dscp_id_seq OWNER TO fod;

--
-- Name: match_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_dscp_id_seq OWNED BY public.match_dscp.id;


--
-- Name: match_port; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_port (
    id integer NOT NULL,
    port character varying(24)
);


ALTER TABLE public.match_port OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_port_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_port_id_seq OWNER TO fod;

--
-- Name: match_port_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_port_id_seq OWNED BY public.match_port.id;


--
-- Name: match_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.match_protocol (
    id integer NOT NULL,
    protocol character varying(24) NOT NULL
);


ALTER TABLE public.match_protocol OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.match_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.match_protocol_id_seq OWNER TO fod;

--
-- Name: match_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.match_protocol_id_seq OWNED BY public.match_protocol.id;


--
-- Name: peer; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer (
    peer_id integer NOT NULL,
    peer_name character varying(128) NOT NULL,
    peer_as integer,
    peer_tag character varying(64) NOT NULL,
    domain_name character varying(128)
);


ALTER TABLE public.peer OWNER TO fod;

--
-- Name: peer_networks; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_networks (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    peerrange_id integer NOT NULL
);


ALTER TABLE public.peer_networks OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_networks_id_seq OWNER TO fod;

--
-- Name: peer_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_networks_id_seq OWNED BY public.peer_networks.id;


--
-- Name: peer_peer_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_peer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_peer_id_seq OWNER TO fod;

--
-- Name: peer_peer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_peer_id_seq OWNED BY public.peer.peer_id;


--
-- Name: peer_range; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_range (
    id integer NOT NULL,
    network character varying(128) NOT NULL
);


ALTER TABLE public.peer_range OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_range_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_range_id_seq OWNER TO fod;

--
-- Name: peer_range_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_range_id_seq OWNED BY public.peer_range.id;


--
-- Name: peer_techc_emails; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peer_techc_emails (
    id integer NOT NULL,
    peer_id integer NOT NULL,
    techcemail_id integer NOT NULL
);


ALTER TABLE public.peer_techc_emails OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peer_techc_emails_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peer_techc_emails_id_seq OWNER TO fod;

--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peer_techc_emails_id_seq OWNED BY public.peer_techc_emails.id;


--
-- Name: peers_peernotify; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.peers_peernotify (
    id integer NOT NULL,
    peer_activation_notified boolean NOT NULL,
    peer_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.peers_peernotify OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.peers_peernotify_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.peers_peernotify_id_seq OWNER TO fod;

--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.peers_peernotify_id_seq OWNED BY public.peers_peernotify.id;


--
-- Name: route; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    source character varying(32) NOT NULL,
    sourceport character varying(65535),
    destination character varying(32) NOT NULL,
    destinationport character varying(65535),
    port character varying(65535),
    icmpcode character varying(32),
    icmptype character varying(32),
    packetlength character varying(65535),
    filed timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    expires date,
    response character varying(512),
    comments text,
    requesters_address character varying(255),
    status character varying(20),
    applier_id integer,
    tcpflag character varying(50)
);


ALTER TABLE public.route OWNER TO fod;

--
-- Name: route_dscp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_dscp (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchdscp_id integer NOT NULL
);


ALTER TABLE public.route_dscp OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_dscp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_dscp_id_seq OWNER TO fod;

--
-- Name: route_dscp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_dscp_id_seq OWNED BY public.route_dscp.id;


--
-- Name: route_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_id_seq OWNER TO fod;

--
-- Name: route_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_id_seq OWNED BY public.route.id;


--
-- Name: route_protocol; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_protocol (
    id integer NOT NULL,
    route_id integer NOT NULL,
    matchprotocol_id integer NOT NULL
);


ALTER TABLE public.route_protocol OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_protocol_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_protocol_id_seq OWNER TO fod;

--
-- Name: route_protocol_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_protocol_id_seq OWNED BY public.route_protocol.id;


--
-- Name: route_then; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.route_then (
    id integer NOT NULL,
    route_id integer NOT NULL,
    thenaction_id integer NOT NULL
);


ALTER TABLE public.route_then OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.route_then_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.route_then_id_seq OWNER TO fod;

--
-- Name: route_then_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.route_then_id_seq OWNED BY public.route_then.id;


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialaccount_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialaccount_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialaccount_id_seq OWNED BY public.socialaccount_socialaccount.id;


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_id_seq OWNED BY public.socialaccount_socialapp.id;


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id integer NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialapp_sites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialapp_sites_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialapp_sites_id_seq OWNED BY public.socialaccount_socialapp_sites.id;


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.socialaccount_socialtoken_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.socialaccount_socialtoken_id_seq OWNER TO fod;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.socialaccount_socialtoken_id_seq OWNED BY public.socialaccount_socialtoken.id;


--
-- Name: techc_email; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.techc_email (
    id integer NOT NULL,
    email character varying(352) NOT NULL
);


ALTER TABLE public.techc_email OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.techc_email_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.techc_email_id_seq OWNER TO fod;

--
-- Name: techc_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.techc_email_id_seq OWNED BY public.techc_email.id;


--
-- Name: then_action; Type: TABLE; Schema: public; Owner: fod
--

CREATE TABLE public.then_action (
    id integer NOT NULL,
    action character varying(60) NOT NULL,
    action_value character varying(255)
);


ALTER TABLE public.then_action OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE; Schema: public; Owner: fod
--

CREATE SEQUENCE public.then_action_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.then_action_id_seq OWNER TO fod;

--
-- Name: then_action_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fod
--

ALTER SEQUENCE public.then_action_id_seq OWNED BY public.then_action.id;


--
-- Name: account_emailaddress id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress ALTER COLUMN id SET DEFAULT nextval('public.account_emailaddress_id_seq'::regclass);


--
-- Name: account_emailconfirmation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation ALTER COLUMN id SET DEFAULT nextval('public.account_emailconfirmation_id_seq'::regclass);


--
-- Name: accounts_userprofile id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_id_seq'::regclass);


--
-- Name: accounts_userprofile_peers id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers ALTER COLUMN id SET DEFAULT nextval('public.accounts_userprofile_peers_id_seq'::regclass);


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: auth_user id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user ALTER COLUMN id SET DEFAULT nextval('public.auth_user_id_seq'::regclass);


--
-- Name: auth_user_groups id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups ALTER COLUMN id SET DEFAULT nextval('public.auth_user_groups_id_seq'::regclass);


--
-- Name: auth_user_user_permissions id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_user_user_permissions_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_flatpage id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_id_seq'::regclass);


--
-- Name: django_flatpage_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites ALTER COLUMN id SET DEFAULT nextval('public.django_flatpage_sites_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: django_site id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site ALTER COLUMN id SET DEFAULT nextval('public.django_site_id_seq'::regclass);


--
-- Name: flowspec_backup_signal id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_backup_signal ALTER COLUMN id SET DEFAULT nextval('public.flowspec_backup_signal_id_seq'::regclass);


--
-- Name: flowspec_fragmenttype id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype ALTER COLUMN id SET DEFAULT nextval('public.flowspec_fragmenttype_id_seq'::regclass);


--
-- Name: flowspec_genievents id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_genievents ALTER COLUMN id SET DEFAULT nextval('public.flowspec_genievents_id_seq'::regclass);


--
-- Name: flowspec_graph id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph ALTER COLUMN id SET DEFAULT nextval('public.flowspec_graph_id_seq'::regclass);


--
-- Name: flowspec_validation id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation ALTER COLUMN id SET DEFAULT nextval('public.flowspec_validation_id_seq'::regclass);


--
-- Name: flowspec_webhookmessage id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_webhookmessage ALTER COLUMN id SET DEFAULT nextval('public.flowspec_webhookmessage_id_seq'::regclass);


--
-- Name: match_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp ALTER COLUMN id SET DEFAULT nextval('public.match_dscp_id_seq'::regclass);


--
-- Name: match_port id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port ALTER COLUMN id SET DEFAULT nextval('public.match_port_id_seq'::regclass);


--
-- Name: match_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol ALTER COLUMN id SET DEFAULT nextval('public.match_protocol_id_seq'::regclass);


--
-- Name: peer peer_id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer ALTER COLUMN peer_id SET DEFAULT nextval('public.peer_peer_id_seq'::regclass);


--
-- Name: peer_networks id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks ALTER COLUMN id SET DEFAULT nextval('public.peer_networks_id_seq'::regclass);


--
-- Name: peer_range id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range ALTER COLUMN id SET DEFAULT nextval('public.peer_range_id_seq'::regclass);


--
-- Name: peer_techc_emails id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails ALTER COLUMN id SET DEFAULT nextval('public.peer_techc_emails_id_seq'::regclass);


--
-- Name: peers_peernotify id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify ALTER COLUMN id SET DEFAULT nextval('public.peers_peernotify_id_seq'::regclass);


--
-- Name: route id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route ALTER COLUMN id SET DEFAULT nextval('public.route_id_seq'::regclass);


--
-- Name: route_dscp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp ALTER COLUMN id SET DEFAULT nextval('public.route_dscp_id_seq'::regclass);


--
-- Name: route_protocol id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol ALTER COLUMN id SET DEFAULT nextval('public.route_protocol_id_seq'::regclass);


--
-- Name: route_then id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then ALTER COLUMN id SET DEFAULT nextval('public.route_then_id_seq'::regclass);


--
-- Name: socialaccount_socialaccount id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialaccount_id_seq'::regclass);


--
-- Name: socialaccount_socialapp id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_id_seq'::regclass);


--
-- Name: socialaccount_socialapp_sites id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialapp_sites_id_seq'::regclass);


--
-- Name: socialaccount_socialtoken id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken ALTER COLUMN id SET DEFAULT nextval('public.socialaccount_socialtoken_id_seq'::regclass);


--
-- Name: techc_email id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email ALTER COLUMN id SET DEFAULT nextval('public.techc_email_id_seq'::regclass);


--
-- Name: then_action id; Type: DEFAULT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action ALTER COLUMN id SET DEFAULT nextval('public.then_action_id_seq'::regclass);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
2	root@root.com	t	f	2
3	alicarsan@gmail.com	t	t	3
4	david.rincon@imdea.org	t	f	4
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile (id, user_id) FROM stdin;
2	3
1	2
3	4
\.


--
-- Data for Name: accounts_userprofile_peers; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.accounts_userprofile_peers (id, userprofile_id, peer_id) FROM stdin;
1	1	1
4	2	1
5	3	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add log entry	7	add_logentry
26	Can change log entry	7	change_logentry
27	Can delete log entry	7	delete_logentry
28	Can view log entry	7	view_logentry
29	Can add flat page	8	add_flatpage
30	Can change flat page	8	change_flatpage
31	Can delete flat page	8	delete_flatpage
32	Can view flat page	8	view_flatpage
33	Can add Token	9	add_token
34	Can change Token	9	change_token
35	Can delete Token	9	delete_token
36	Can view Token	9	view_token
37	Can add token	10	add_tokenproxy
38	Can change token	10	change_tokenproxy
39	Can delete token	10	delete_tokenproxy
40	Can view token	10	view_tokenproxy
41	Can add fragment type	11	add_fragmenttype
42	Can change fragment type	11	change_fragmenttype
43	Can delete fragment type	11	delete_fragmenttype
44	Can view fragment type	11	view_fragmenttype
45	Can add match dscp	12	add_matchdscp
46	Can change match dscp	12	change_matchdscp
47	Can delete match dscp	12	delete_matchdscp
48	Can view match dscp	12	view_matchdscp
49	Can add match port	13	add_matchport
50	Can change match port	13	change_matchport
51	Can delete match port	13	delete_matchport
52	Can view match port	13	view_matchport
53	Can add match protocol	14	add_matchprotocol
54	Can change match protocol	14	change_matchprotocol
55	Can delete match protocol	14	delete_matchprotocol
56	Can view match protocol	14	view_matchprotocol
57	Can add webhook message	15	add_webhookmessage
58	Can change webhook message	15	change_webhookmessage
59	Can delete webhook message	15	delete_webhookmessage
60	Can view webhook message	15	view_webhookmessage
61	Can add validation	16	add_validation
62	Can change validation	16	change_validation
63	Can delete validation	16	delete_validation
64	Can view validation	16	view_validation
65	Can add then action	17	add_thenaction
66	Can change then action	17	change_thenaction
67	Can delete then action	17	delete_thenaction
68	Can view then action	17	view_thenaction
69	Can add Rule	18	add_route
70	Can change Rule	18	change_route
71	Can delete Rule	18	delete_route
72	Can view Rule	18	view_route
73	Can add graph	19	add_graph
74	Can change graph	19	change_graph
75	Can delete graph	19	delete_graph
76	Can view graph	19	view_graph
77	Can add geni events	20	add_genievents
78	Can change geni events	20	change_genievents
79	Can delete geni events	20	delete_genievents
80	Can view geni events	20	view_genievents
81	Can add attack event	21	add_attackevent
82	Can change attack event	21	change_attackevent
83	Can delete attack event	21	delete_attackevent
84	Can view attack event	21	view_attackevent
85	Can add backup_signal	22	add_backup_signal
86	Can change backup_signal	22	change_backup_signal
87	Can delete backup_signal	22	delete_backup_signal
88	Can view backup_signal	22	view_backup_signal
89	Can add peer	23	add_peer
90	Can change peer	23	change_peer
91	Can delete peer	23	delete_peer
92	Can view peer	23	view_peer
93	Can add peer range	24	add_peerrange
94	Can change peer range	24	change_peerrange
95	Can delete peer range	24	delete_peerrange
96	Can view peer range	24	view_peerrange
97	Can add techc email	25	add_techcemail
98	Can change techc email	25	change_techcemail
99	Can delete techc email	25	delete_techcemail
100	Can view techc email	25	view_techcemail
101	Can add peer notify	26	add_peernotify
102	Can change peer notify	26	change_peernotify
103	Can delete peer notify	26	delete_peernotify
104	Can view peer notify	26	view_peernotify
105	Can add user profile	27	add_userprofile
106	Can change user profile	27	change_userprofile
107	Can delete user profile	27	delete_userprofile
108	Can view user profile	27	view_userprofile
109	Can see registered users and rules	27	overview
110	Can add email address	28	add_emailaddress
111	Can change email address	28	change_emailaddress
112	Can delete email address	28	delete_emailaddress
113	Can view email address	28	view_emailaddress
114	Can add email confirmation	29	add_emailconfirmation
115	Can change email confirmation	29	change_emailconfirmation
116	Can delete email confirmation	29	delete_emailconfirmation
117	Can view email confirmation	29	view_emailconfirmation
118	Can add social account	30	add_socialaccount
119	Can change social account	30	change_socialaccount
120	Can delete social account	30	delete_socialaccount
121	Can view social account	30	view_socialaccount
122	Can add social application	31	add_socialapp
123	Can change social application	31	change_socialapp
124	Can delete social application	31	delete_socialapp
125	Can view social application	31	view_socialapp
126	Can add social application token	32	add_socialtoken
127	Can change social application token	32	change_socialtoken
128	Can delete social application token	32	delete_socialtoken
129	Can view social application token	32	view_socialtoken
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	pbkdf2_sha256$216000$4KXGLlFfxQpq$R447FvjnlvchdyAo9bnk6m0VAkpI1m4r6WJhix0JfBk=	2022-01-27 08:18:07.495676+00	f	Alicia	Alicia	Sánchez	alicarsan@gmail.com	f	t	2022-01-18 15:23:26+00
2	pbkdf2_sha256$216000$skQBge6RYJCU$sptVK0sHqc9YnwlDcZXQZckeEZhuvR6y1sQPOm/Yeyg=	2022-01-31 11:08:22.169858+00	t	root			root@root.com	t	t	2022-01-18 13:52:57.520828+00
4	pbkdf2_sha256$216000$iDdcMRLRtExq$8WKGeFUDMEmDOqUT0xVp4NlVSgMUl/R4WdwiNYhA0hY=	2022-01-31 11:10:13.709448+00	t	drincon	David	Rincón	david.rincon@imdea.org	f	t	2022-01-31 11:09:13+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2022-01-18 13:55:59.853584+00	1	Administrador	3		3	2
2	2022-01-18 13:59:24.627816+00	1	1.1.1.1/32	1	[{"added": {}}]	24	2
3	2022-01-18 13:59:47.131018+00	2	2.2.2.2/32	1	[{"added": {}}]	24	2
4	2022-01-18 13:59:59.987056+00	1	UDP	1	[{"added": {}}]	14	2
5	2022-01-18 14:00:34.363229+00	2	TCP	1	[{"added": {}}]	14	2
6	2022-01-18 14:00:46.219057+00	3	ICMP	1	[{"added": {}}]	14	2
7	2022-01-18 14:00:53.02026+00	1	accept	1	[{"added": {}}]	17	2
8	2022-01-18 14:00:56.830005+00	2	discard	1	[{"added": {}}]	17	2
9	2022-01-18 14:01:05.442735+00	3	rate-limit:1GB	1	[{"added": {}}]	17	2
10	2022-01-18 14:01:16.65774+00	4	rate-limit:2G	1	[{"added": {}}]	17	2
11	2022-01-18 14:01:23.209966+00	3	rate-limit:1G	2	[{"changed": {"fields": ["Action Value"]}}]	17	2
12	2022-01-18 14:01:53.948138+00	5	rate-limit:3G	1	[{"added": {}}]	17	2
13	2022-01-18 14:03:10.547006+00	1	IMDEA	1	[{"added": {}}]	23	2
14	2022-01-18 14:03:49.149198+00	2	UAH	1	[{"added": {}}]	23	2
15	2022-01-18 14:12:19.062195+00	1	redifod.redimadrid.es	2	[{"changed": {"fields": ["Domain name", "Display name"]}}]	6	2
16	2022-01-18 14:28:19.252086+00	2	root@root.com	2	[{"changed": {"fields": ["Verified"]}}]	28	2
17	2022-01-18 14:28:41.42205+00	1	root	1	[{"added": {}}]	27	2
18	2022-01-18 14:28:51.870939+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
19	2022-01-18 14:46:07.828424+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
20	2022-01-18 14:46:22.696537+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
21	2022-01-18 15:29:07.204254+00	2	Alicia	1	[{"added": {}}]	27	2
22	2022-01-18 15:29:27.751061+00	3	Alicia	2	[{"changed": {"fields": ["First name", "Last name"]}}]	3	2
23	2022-01-18 15:39:07.475277+00	5	tcp	1	[{"added": {}}]	14	2
24	2022-01-18 15:39:12.326853+00	2	TCP	3		14	2
25	2022-01-18 15:39:17.535763+00	1	UDP	3		14	2
26	2022-01-18 15:39:22.120199+00	6	icmp	1	[{"added": {}}]	14	2
27	2022-01-18 15:39:26.813745+00	3	ICMP	3		14	2
28	2022-01-24 12:49:08.77234+00	1	root	2	[{"changed": {"fields": ["Peers"]}}]	27	2
29	2022-01-31 11:09:13.869448+00	4	drincon	1	[{"added": {}}, {"added": {"name": "user profile", "object": "drincon"}}]	3	2
30	2022-01-31 11:09:30.657927+00	4	drincon	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "Superuser status"]}}]	3	2
31	2022-01-31 11:09:59.650359+00	4	david.rincon@imdea.org	1	[{"added": {}}]	28	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	admin	logentry
8	flatpages	flatpage
9	authtoken	token
10	authtoken	tokenproxy
11	flowspec	fragmenttype
12	flowspec	matchdscp
13	flowspec	matchport
14	flowspec	matchprotocol
15	flowspec	webhookmessage
16	flowspec	validation
17	flowspec	thenaction
18	flowspec	route
19	flowspec	graph
20	flowspec	genievents
21	flowspec	attackevent
22	flowspec	backup_signal
23	peers	peer
24	peers	peerrange
25	peers	techcemail
26	peers	peernotify
27	accounts	userprofile
28	account	emailaddress
29	account	emailconfirmation
30	socialaccount	socialaccount
31	socialaccount	socialapp
32	socialaccount	socialtoken
\.


--
-- Data for Name: django_flatpage; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage (id, url, title, content, enable_comments, template_name, registration_required) FROM stdin;
\.


--
-- Data for Name: django_flatpage_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_flatpage_sites (id, flatpage_id, site_id) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2022-01-18 12:16:06.334675+00
2	auth	0001_initial	2022-01-18 12:16:08.874608+00
3	account	0001_initial	2022-01-18 12:16:13.814197+00
4	account	0002_email_max_length	2022-01-18 12:16:15.121677+00
5	peers	0001_initial	2022-01-18 12:16:16.937367+00
6	accounts	0001_initial	2022-01-18 12:16:19.25335+00
7	admin	0001_initial	2022-01-18 12:16:20.575582+00
8	admin	0002_logentry_remove_auto_add	2022-01-18 12:16:21.188746+00
9	admin	0003_logentry_add_action_flag_choices	2022-01-18 12:16:21.271551+00
10	contenttypes	0002_remove_content_type_name	2022-01-18 12:16:21.379424+00
11	auth	0002_alter_permission_name_max_length	2022-01-18 12:16:21.479843+00
12	auth	0003_alter_user_email_max_length	2022-01-18 12:16:21.574004+00
13	auth	0004_alter_user_username_opts	2022-01-18 12:16:21.66642+00
14	auth	0005_alter_user_last_login_null	2022-01-18 12:16:21.770757+00
15	auth	0006_require_contenttypes_0002	2022-01-18 12:16:21.867556+00
16	auth	0007_alter_validators_add_error_messages	2022-01-18 12:16:21.973758+00
17	auth	0008_alter_user_username_max_length	2022-01-18 12:16:22.357401+00
18	auth	0009_alter_user_last_name_max_length	2022-01-18 12:16:22.532069+00
19	auth	0010_alter_group_name_max_length	2022-01-18 12:16:22.629333+00
20	auth	0011_update_proxy_permissions	2022-01-18 12:16:22.730616+00
21	auth	0012_alter_user_first_name_max_length	2022-01-18 12:16:22.825093+00
22	auth	0013_auto_20220118_1216	2022-01-18 12:16:22.925686+00
23	authtoken	0001_initial	2022-01-18 12:16:24.0087+00
24	authtoken	0002_auto_20160226_1747	2022-01-18 12:16:24.87128+00
25	authtoken	0003_tokenproxy	2022-01-18 12:16:25.359798+00
26	sites	0001_initial	2022-01-18 12:16:26.226463+00
27	flatpages	0001_initial	2022-01-18 12:16:27.738351+00
28	flowspec	0001_initial	2022-01-18 12:16:36.312495+00
29	flowspec	0002_auto_20211027_1621	2022-01-18 12:16:41.089766+00
30	flowspec	0003_genievents	2022-01-18 12:16:41.416075+00
31	flowspec	0004_auto_20211125_1159	2022-01-18 12:16:41.575289+00
32	flowspec	0005_attackevent	2022-01-18 12:16:42.214191+00
33	flowspec	0006_auto_20211201_1616	2022-01-18 12:16:42.623546+00
34	flowspec	0007_auto_20211213_1627	2022-01-18 12:16:43.423325+00
35	flowspec	0008_auto_20211215_1043	2022-01-18 12:16:44.557033+00
36	flowspec	0009_backup_signal	2022-01-18 12:16:44.852711+00
37	flowspec	0010_auto_20220118_1211	2022-01-18 12:16:44.991552+00
38	longerusername	0001_initial	2022-01-18 12:16:45.081851+00
39	peers	0002_auto_20210603_1642	2022-01-18 12:16:45.225382+00
40	sessions	0001_initial	2022-01-18 12:16:46.188097+00
41	sites	0002_alter_domain_unique	2022-01-18 12:16:47.161043+00
42	socialaccount	0001_initial	2022-01-18 12:16:49.544317+00
43	socialaccount	0002_token_max_lengths	2022-01-18 12:16:52.245192+00
44	socialaccount	0003_extra_data_default_dict	2022-01-18 12:16:52.438119+00
45	auth	0013_auto_20220131_1107	2022-01-31 11:07:39.639712+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
52an711e7xjpaqlpl8zpr6i90zz69ue2	eyJhY2NvdW50X3ZlcmlmaWVkX2VtYWlsIjpudWxsLCJhY2NvdW50X3VzZXIiOiIzIn0:1n9qKV:zPC7X9Fdx--IgAAOdTlwybTM36s3u5CyVUC2Y60l4kU	2022-02-01 15:23:27.865031+00
qfdqqr7osgm6q5gwd8be2admhdrruml3	.eJxVjDsOwjAQBe_iGlmO_0lJzxksr3dDDMhGcSKBEHeHSCmgfTNvXizEdZnC2mgOGdnAJDv8bhDTlcoG8BLLufJUyzJn4JvCd9r4qSLdjrv7F5him75vcMmICISkHXRKOgOjBiOsA4k9YPSdsNZIY8EmSQ61Gkkkq_oRvfdqizZqLdcS6HHP85MN4v0Bn_w_RA:1nD8Sw:z54uet9-WtnC8_3vJE2QI66_xTak556uuWaf7A6p-H0	2022-02-10 17:21:46.143965+00
3lajpfy6snjf8q3glcubocx4c8nzuyiu	.eJxVjMEOwiAQRP-FsyHQkkJ79O43kGV3a1EDBtpEY_x3W9ODniaZefNewsMyT36pXHwkMQgjDr9dALxy2ga6QDpniTnNJQa5IXJfqzxl4ttxZ_8EE9RpfbcEPXZutGCY2CFZ3bALoEKvSLXaAvaM2rQjmQ6bzrJb0yJrYxnpK61ca8zJ8-Mey1MM6v0Byv1AOg:1nEUZZ:a-TEwKAK1F3CuUX-4E9n2wyjvmR-pfyWtPXjpOEtgzk	2022-02-14 11:10:13.721319+00
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.django_site (id, domain, name) FROM stdin;
1	redifod.redimadrid.es	RediFod
\.


--
-- Data for Name: flowspec_attackevent; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_attackevent (id_attack, name_attack, status, max_value, threshold_value, severity, traffic_characteristics, network_characteristics, received_at, institution_name, ip_attacked) FROM stdin;
A377338	['Host TCP Traffic']	Ongoing	513952226.66667	246700000	yellow	\N	\N	2022-01-18 12:29:35.413954+00	UEM	193.147.239.138
A377341	['Host TCP Traffic']	Ongoing	361728066.66667	246700000	yellow	\N	\N	2022-01-18 13:04:35.838118+00	UEM	193.147.239.138
A377343	['Host TCP Traffic']	Ongoing	326885120	246700000	yellow	\N	\N	2022-01-18 13:35:35.610827+00	UEM	193.147.239.138
A377347	['Host TCP Traffic']	Ongoing	381377560	246700000	yellow	\N	\N	2022-01-18 13:54:35.376677+00	UEM	193.147.239.138
A377350	['Host TCP Traffic']	Ongoing	311877613.33333	246700000	yellow	\N	\N	2022-01-18 14:08:35.699787+00	UEM	193.147.239.138
A377351	['Host TCP Traffic']	Ongoing	391465426.66667	246700000	yellow	\N	\N	2022-01-18 14:13:35.387652+00	UEM	193.147.239.138
A377355	['Host TCP Traffic']	Ongoing	448441293.33333	246700000	yellow	\N	\N	2022-01-18 15:05:36.610702+00	UEM	193.147.239.138
A377356	['Host TCP Traffic']	Ongoing	394059826.66667	246700000	yellow	\N	\N	2022-01-18 15:27:35.912779+00	UEM	193.147.239.138
A377358	['Host TCP Traffic']	Ongoing	258503400	187360000	yellow	\N	\N	2022-01-18 16:02:36.033043+00	UAH	193.146.58.180
A377360	['Host TCP Traffic']	Ongoing	299158426.66667	187360000	yellow	\N	\N	2022-01-18 16:38:34.638338+00	UAH	193.146.58.180
A377361	['Host TCP Traffic']	Ongoing	361760853.33333	246700000	yellow	\N	\N	2022-01-18 16:42:35.558664+00	UEM	193.147.239.138
A377362	['Host TCP Traffic']	Ongoing	367017160	246700000	yellow	\N	\N	2022-01-18 17:15:36.022185+00	UEM	193.147.239.138
A377363	['Host TCP Traffic']	Ongoing	299936293.33333	187360000	yellow	\N	\N	2022-01-18 17:32:36.512709+00	UAH	193.146.58.180
A377364	['Host TCP Traffic']	Ongoing	305260733.33333	246700000	yellow	\N	\N	2022-01-18 17:35:35.55198+00	UEM	193.147.239.138
A377365	['Host TCP Traffic']	Ongoing	251976546.66667	187360000	yellow	\N	\N	2022-01-18 17:45:36.15752+00	UAH	193.146.58.180
A377371	['Host TCP Traffic']	Ongoing	305509280	187360000	yellow	\N	\N	2022-01-18 18:07:36.125723+00	UAH	193.146.58.180
A377374	['Host TCP Traffic']	Ongoing	430682280	246700000	yellow	\N	\N	2022-01-18 19:39:36.201774+00	UEM	193.147.239.138
A377375	['Host TCP Traffic']	Ongoing	367111706.66667	246700000	yellow	\N	\N	2022-01-18 19:48:36.754322+00	UEM	193.147.239.138
A377376	['Host TCP Traffic']	Ongoing	255965786.66667	246700000	yellow	\N	\N	2022-01-18 20:01:36.06048+00	UEM	193.147.239.138
A377377	['Host TCP Traffic']	Ongoing	306726213.33333	246700000	yellow	\N	\N	2022-01-18 20:07:36.841588+00	UEM	193.147.239.138
A377384	['Host TCP Traffic']	Ongoing	291978986.66667	187360000	yellow	\N	\N	2022-01-18 21:34:35.75393+00	UAH	193.146.58.180
A377385	['Host TCP Traffic']	Ongoing	341291440	187360000	yellow	\N	\N	2022-01-18 21:51:35.407423+00	UAH	193.146.58.180
A377388	['Host TCP Traffic']	Ongoing	281911546.66667	187360000	yellow	\N	\N	2022-01-18 22:11:35.175673+00	UAH	193.146.58.180
A377389	['Host TCP Traffic']	Ongoing	347187373.33333	187360000	yellow	\N	\N	2022-01-18 22:32:36.909704+00	UAH	193.146.58.180
A377392	['Host TCP Traffic']	Ongoing	267569880	187360000	yellow	\N	\N	2022-01-18 22:45:37.016882+00	UAH	193.146.58.180
A377395	['Host TCP Traffic']	Ongoing	270715146.66667	246700000	yellow	\N	\N	2022-01-18 23:05:36.117477+00	UEM	193.147.239.138
A377397	['Host TCP Traffic']	Ongoing	312020640	246700000	yellow	\N	\N	2022-01-18 23:37:35.275253+00	UEM	193.147.239.138
A377402	['Host TCP Traffic']	Ongoing	529143040	246700000	yellow	\N	\N	2022-01-19 09:12:36.957451+00	UEM	193.147.239.138
A377403	['Host TCP Traffic']	Ongoing	535506906.66667	246700000	yellow	\N	\N	2022-01-19 09:46:35.762063+00	UEM	193.147.239.138
A377406	['Host TCP Traffic']	Ongoing	527865973.33333	246700000	yellow	\N	\N	2022-01-19 10:19:34.893101+00	UEM	193.147.239.138
A377407	['Host TCP Traffic']	Ongoing	528698066.66667	432130000	yellow	\N	\N	2022-01-19 11:20:35.494233+00	UNED	62.204.192.205
A377410	['Host TCP Traffic']	Ongoing	455222426.66667	246700000	yellow	\N	\N	2022-01-19 12:09:36.15473+00	UEM	193.147.239.138
A377417	['Host TCP Traffic']	Ongoing	279207613.33333	187360000	yellow	\N	\N	2022-01-19 14:28:35.177653+00	UAH	193.146.58.180
A377421	['Host TCP Traffic']	Ongoing	340772573.33333	246700000	yellow	\N	\N	2022-01-19 15:14:36.131237+00	UEM	193.147.239.138
A377422	['HTTP Flooding']	Ongoing	209461600	148280000	yellow	\N	\N	2022-01-19 15:31:35.576195+00	URJC	212.128.240.26
A377431	['HTTP Flooding']	Ongoing	174336986.66667	148280000	yellow	\N	\N	2022-01-19 17:23:35.603086+00	URJC	212.128.240.26
A377430	['Host TCP Traffic']	Ongoing	504300386.66667	246700000	yellow	\N	\N	2022-01-19 17:22:36.856935+00	UEM	193.147.239.138
A377437	['Host TCP Traffic']	Ongoing	385838506.66667	187360000	yellow	\N	\N	2022-01-19 20:34:37.075651+00	UAH	193.146.58.180
A377438	['Host TCP Traffic']	Ongoing	332117906.66667	187360000	yellow	\N	\N	2022-01-19 20:41:36.122651+00	UAH	193.146.58.180
A377440	['Host TCP Traffic']	Ongoing	275230546.66667	187360000	yellow	\N	\N	2022-01-19 21:12:36.303964+00	UAH	193.146.58.180
A377442	['Host TCP Traffic']	Ongoing	290416266.66667	187360000	yellow	\N	\N	2022-01-19 21:53:36.060538+00	UAH	193.146.58.180
A377458	['Host TCP Traffic']	Ongoing	356389520	246700000	yellow	\N	\N	2022-01-20 08:49:36.457389+00	UEM	193.147.239.138
A377461	['Host TCP Traffic']	Ongoing	370729920	246700000	yellow	\N	\N	2022-01-20 09:03:35.985191+00	UEM	193.147.239.138
A377466	['Host TCP Traffic']	Ongoing	422787640	187360000	yellow	\N	\N	2022-01-20 09:41:35.039144+00	UAH	193.146.58.205
A377467	['Host TCP Traffic']	Ongoing	470239026.66667	246700000	yellow	\N	\N	2022-01-20 09:48:35.614965+00	UEM	193.147.239.138
A377468	['Host TCP Traffic']	Ongoing	388073386.66667	246700000	yellow	\N	\N	2022-01-20 09:53:35.849325+00	UEM	193.147.239.138
A377469	['Host TCP Traffic']	Ongoing	401463560	246700000	yellow	\N	\N	2022-01-20 10:02:34.922542+00	UEM	193.147.239.138
A377470	['Host TCP Traffic']	Ongoing	637174746.66667	208980000	yellow	\N	\N	2022-01-20 10:10:35.484297+00	CEU(2)	193.146.228.60
A377472	['Host TCP Traffic']	Ongoing	443393506.66667	299320000	yellow	\N	\N	2022-01-20 10:48:34.64057+00	UPM	138.100.71.99
A377473	['Host TCP Traffic']	Ongoing	396030480	246700000	yellow	\N	\N	2022-01-20 10:58:35.961337+00	UEM	193.147.239.138
A377475	['Host TCP Traffic']	Ongoing	230683626.66667	208980000	yellow	\N	\N	2022-01-20 11:16:37.147603+00	CEU(2)	193.146.228.60
A377478	['Host TCP Traffic']	Ongoing	375404960	246700000	yellow	\N	\N	2022-01-20 11:30:36.667134+00	UEM	193.147.239.138
A377479	['Host TCP Traffic']	Ongoing	1169818453.3333	430310000	yellow	\N	\N	2022-01-20 11:32:35.831921+00	CASA VELAZQUEZ	193.146.142.68
A377480	['Host TCP Traffic']	Ongoing	308279626.66667	208980000	yellow	\N	\N	2022-01-20 11:42:35.048436+00	CEU(2)	193.146.228.60
A377481	['Host TCP Traffic']	Ongoing	597529186.66667	246700000	yellow	\N	\N	2022-01-20 11:44:36.358789+00	UEM	193.147.239.138
A377485	['Host TCP Traffic']	Ongoing	311843746.66667	187360000	yellow	\N	\N	2022-01-20 12:13:36.453401+00	UAH	193.146.58.180
A377486	['Host TCP Traffic']	Ongoing	379258093.33333	299320000	yellow	\N	\N	2022-01-20 12:23:36.930864+00	UPM	138.100.71.99
A377487	['Host TCP Traffic']	Ongoing	270069026.66667	208980000	yellow	\N	\N	2022-01-20 12:29:35.976951+00	CEU(2)	193.146.228.60
A377491	['Host TCP Traffic']	Ongoing	363871706.66667	299320000	yellow	\N	\N	2022-01-20 12:55:36.232913+00	UPM	138.100.71.99
A377494	['Host TCP Traffic']	Ongoing	387899586.66667	299320000	yellow	\N	\N	2022-01-20 13:09:36.628179+00	UPM	138.100.71.99
A377502	['Host TCP Traffic']	Ongoing	258728426.66667	187360000	yellow	\N	\N	2022-01-20 14:18:35.280634+00	UAH	193.146.58.180
A377503	['Host TCP Traffic']	Ongoing	230974640	187360000	yellow	\N	\N	2022-01-20 14:37:35.387181+00	UAH	193.146.58.180
A377505	['Host TCP Traffic']	Ongoing	374424466.66667	246700000	yellow	\N	\N	2022-01-20 14:53:35.841045+00	UEM	193.147.239.138
A377508	['Host TCP Traffic']	Ongoing	361396453.33333	246700000	yellow	\N	\N	2022-01-20 15:37:36.575214+00	UEM	193.147.239.138
A377511	['Host TCP Traffic']	Ongoing	548648653.33333	208980000	yellow	\N	\N	2022-01-20 15:54:36.406201+00	CEU(2)	193.146.228.60
A377514	['Host TCP Traffic']	Ongoing	366277160	246700000	yellow	\N	\N	2022-01-20 16:08:36.855208+00	UEM	193.147.239.138
A377519	['Host TCP Traffic']	Ongoing	596634040	246700000	yellow	\N	\N	2022-01-20 17:47:35.475454+00	UEM	193.147.239.138
A377524	['Host TCP Traffic']	Ongoing	248381853.33333	187360000	yellow	\N	\N	2022-01-20 19:13:35.807443+00	UAH	193.146.58.180
A377528	['Host TCP Traffic']	Ongoing	281941680	187360000	yellow	\N	\N	2022-01-20 19:38:36.815249+00	UAH	193.146.58.180
A377529	['Host TCP Traffic']	Ongoing	265231120	187360000	yellow	\N	\N	2022-01-20 19:48:36.111175+00	UAH	193.146.58.180
A377530	['Host TCP Traffic']	Ongoing	244871440	187360000	yellow	\N	\N	2022-01-20 19:59:35.15128+00	UAH	193.146.58.180
A377533	['Host TCP Traffic']	Ongoing	398975000	187360000	yellow	\N	\N	2022-01-20 20:22:35.362555+00	UAH	193.146.58.180
A377536	['Host TCP Traffic']	Ongoing	289536133.33333	187360000	yellow	\N	\N	2022-01-20 20:47:35.269232+00	UAH	193.146.58.180
A377537	['Host TCP Traffic']	Ongoing	265293480	187360000	yellow	\N	\N	2022-01-20 22:44:36.487378+00	UAH	193.146.58.180
A377538	['Host TCP Traffic']	Ongoing	303542733.33333	187360000	yellow	\N	\N	2022-01-20 23:01:37.519491+00	UAH	193.146.58.180
A377539	['Host TCP Traffic']	Ongoing	277677346.66667	187360000	yellow	\N	\N	2022-01-20 23:07:35.455688+00	UAH	193.146.58.180
A377541	['Host TCP Traffic']	Ongoing	525595106.66667	432130000	yellow	\N	\N	2022-01-21 08:11:36.183642+00	UNED	62.204.192.200
A377547	['Host TCP Traffic']	Ongoing	334677413.33333	246700000	yellow	\N	\N	2022-01-21 09:07:36.245997+00	UEM	193.147.239.138
A377555	['Host TCP Traffic']	Ongoing	398307360	246700000	yellow	\N	\N	2022-01-21 09:36:36.35187+00	UEM	193.147.239.138
A377559	['Host TCP Traffic']	Ongoing	452325666.66667	299320000	yellow	\N	\N	2022-01-21 10:18:35.672808+00	UPM	138.100.4.11
A377563	['Host TCP Traffic']	Ongoing	371597426.66667	246700000	yellow	\N	\N	2022-01-21 10:33:35.240852+00	UEM	193.147.239.138
A377566	['Host TCP Traffic']	Ongoing	477385520	299320000	yellow	\N	\N	2022-01-21 10:43:36.62041+00	UPM	138.100.4.11
A377567	['Host TCP Traffic']	Ongoing	407944560	246700000	yellow	\N	\N	2022-01-21 10:45:35.953988+00	UEM	193.147.239.138
A377569	['Host TCP Traffic']	Ongoing	337062626.66667	246700000	yellow	\N	\N	2022-01-21 10:59:36.480829+00	UEM	193.147.239.138
A377571	['Host TCP Traffic']	Ongoing	380861666.66667	246700000	yellow	\N	\N	2022-01-21 11:04:35.557391+00	UEM	193.147.239.138
A377572	['Host TCP Traffic']	Ongoing	438576853.33333	208980000	yellow	\N	\N	2022-01-21 11:08:35.905221+00	CEU(2)	193.146.228.60
A377575	['Host TCP Traffic']	Ongoing	361647693.33333	246700000	yellow	\N	\N	2022-01-21 11:31:34.650183+00	UEM	193.147.239.138
A377576	['Host TCP Traffic']	Ongoing	239030666.66667	208980000	yellow	\N	\N	2022-01-21 11:31:35.236659+00	CEU(2)	193.146.228.60
A377581	['Host TCP Traffic']	Ongoing	390551080	299320000	yellow	\N	\N	2022-01-21 11:52:35.57058+00	UPM	138.100.4.11
A377584	['Host TCP Traffic']	Ongoing	313069320	246700000	yellow	\N	\N	2022-01-21 12:02:35.981105+00	UEM	193.147.239.138
A377589	['Host TCP Traffic']	Ongoing	488810173.33333	432130000	yellow	\N	\N	2022-01-21 12:19:35.73714+00	UNED	62.204.192.200
A377591	['Host TCP Traffic']	Ongoing	333661306.66667	246700000	yellow	\N	\N	2022-01-21 12:28:34.867326+00	UEM	193.147.239.138
A377594	['HTTP Flooding']	Ongoing	82434240	60280000	yellow	\N	\N	2022-01-21 12:43:37.053737+00	UNED	62.204.213.51
A377598	['Host TCP Traffic']	Ongoing	328230026.66667	246700000	yellow	\N	\N	2022-01-21 13:09:36.484234+00	UEM	193.147.239.138
A377599	['Host TCP Traffic']	Ongoing	326952906.66667	246700000	yellow	\N	\N	2022-01-21 13:16:35.937718+00	UEM	193.147.239.138
A377604	['Host TCP Traffic']	Ongoing	259968920	187360000	yellow	\N	\N	2022-01-21 14:06:35.714556+00	UAH	193.146.58.180
A377607	['Host TCP Traffic']	Ongoing	350466333.33333	246700000	yellow	\N	\N	2022-01-21 15:21:35.502271+00	UEM	193.147.239.138
A377611	['Host TCP Traffic']	Ongoing	349098440	246700000	yellow	\N	\N	2022-01-21 16:25:35.886527+00	UEM	193.147.239.138
A377612	['Host TCP Traffic']	Ongoing	262877080	208980000	yellow	\N	\N	2022-01-21 16:26:35.907888+00	CEU(2)	193.146.228.60
A377614	['HTTP Flooding']	Ongoing	240943653.33333	135540000	yellow	\N	\N	2022-01-21 16:36:36.249422+00	URJC	212.128.240.26
A377617	['Host TCP Traffic']	Ongoing	257374760	187360000	yellow	\N	\N	2022-01-21 18:51:36.222071+00	UAH	193.146.58.180
A377619	['Host TCP Traffic']	Ongoing	256551333.33333	187360000	yellow	\N	\N	2022-01-21 20:37:36.216941+00	UAH	193.146.58.180
A377626	['Host TCP Traffic']	Ongoing	251389213.33333	187360000	yellow	\N	\N	2022-01-21 21:05:36.175665+00	UAH	193.146.58.180
A377632	['Host TCP Traffic']	Ongoing	296924613.33333	187360000	yellow	\N	\N	2022-01-21 22:02:35.314103+00	UAH	193.146.58.180
A377634	['Host TCP Traffic']	Ongoing	272226693.33333	187360000	yellow	\N	\N	2022-01-21 22:25:35.311427+00	UAH	193.146.58.180
A377636	['Host TCP Traffic']	Ongoing	292616373.33333	187360000	yellow	\N	\N	2022-01-21 22:53:36.072907+00	UAH	193.146.58.180
A377637	['Host TCP Traffic']	Ongoing	272358786.66667	187360000	yellow	\N	\N	2022-01-21 23:00:36.265176+00	UAH	193.146.58.180
A377638	['Host TCP Traffic']	Ongoing	317201173.33333	187360000	yellow	\N	\N	2022-01-21 23:08:36.52758+00	UAH	193.146.58.180
A377639	['Host TCP Traffic']	Ongoing	433920120	187360000	yellow	\N	\N	2022-01-21 23:18:34.982823+00	UAH	193.146.58.180
A377644	['Host TCP Traffic']	Ongoing	270329306.66667	187360000	yellow	\N	\N	2022-01-22 12:30:35.989466+00	UAH	193.146.58.180
A377645	['Host TCP Traffic']	Ongoing	278812773.33333	187360000	yellow	\N	\N	2022-01-22 12:40:34.953276+00	UAH	193.146.58.180
A377647	['Host TCP Traffic']	Ongoing	329075053.33333	246700000	yellow	\N	\N	2022-01-22 13:08:35.120395+00	UEM	193.147.239.138
A377656	['Host TCP Traffic']	Ongoing	293541666.66667	187360000	yellow	\N	\N	2022-01-22 21:24:35.759331+00	UAH	193.146.58.180
A377672	['Host TCP Traffic']	Ongoing	256476120	187360000	yellow	\N	\N	2022-01-23 14:09:35.673036+00	UAH	193.146.58.180
A377675	['Host TCP Traffic']	Ongoing	260440360	187360000	yellow	\N	\N	2022-01-23 16:19:36.321032+00	UAH	193.146.58.180
A377688	['Host TCP Traffic']	Ongoing	287283173.33333	187360000	yellow	\N	\N	2022-01-23 20:40:35.689884+00	UAH	193.146.58.180
A377691	['Host TCP Traffic']	Ongoing	294931840	187360000	yellow	\N	\N	2022-01-23 21:26:36.41717+00	UAH	193.146.58.180
A377695	['Host TCP Traffic']	Ongoing	239431506.66667	187360000	yellow	\N	\N	2022-01-23 23:24:40.878864+00	UAH	193.146.58.180
A377700	['Host TCP Traffic']	Ongoing	301191386.66667	246700000	yellow	\N	\N	2022-01-24 08:18:34.944464+00	UEM	193.147.239.138
A377704	['Host TCP Traffic']	Ongoing	324505200	246700000	yellow	\N	\N	2022-01-24 08:41:35.764716+00	UEM	193.147.239.138
A377705	['Host TCP Traffic']	Ongoing	250772826.66667	208980000	yellow	\N	\N	2022-01-24 08:48:35.026886+00	CEU	193.146.228.27
A377707	['Host TCP Traffic']	Ongoing	367630520	246700000	yellow	\N	\N	2022-01-24 08:58:36.288224+00	UEM	193.147.239.138
A377709	['Host TCP Traffic']	Ongoing	244722640	208980000	yellow	\N	\N	2022-01-24 09:25:35.706293+00	CEU(2)	193.146.228.60
A377715	['Host TCP Traffic']	Ongoing	235153773.33333	208980000	yellow	\N	\N	2022-01-24 10:00:36.010861+00	CEU(2)	193.146.228.60
A377717	['Host TCP Traffic']	Ongoing	247112480	208980000	yellow	\N	\N	2022-01-24 10:26:36.113203+00	CEU(2)	193.146.228.60
A377719	['Host TCP Traffic']	Ongoing	295513533.33333	208980000	yellow	\N	\N	2022-01-24 10:50:36.609927+00	CEU(2)	193.146.228.60
A377721	['Host TCP Traffic']	Ongoing	326137826.66667	246700000	yellow	\N	\N	2022-01-24 10:55:36.416224+00	UEM	193.147.239.138
A377723	['Host TCP Traffic']	Ongoing	334963880	246700000	yellow	\N	\N	2022-01-24 11:00:35.553749+00	UEM	193.147.239.138
A377724	['Host TCP Traffic']	Ongoing	319298120	208980000	yellow	\N	\N	2022-01-24 11:03:36.909362+00	CEU(2)	193.146.228.60
A377732	['Host TCP Traffic']	Ongoing	520886640	432130000	yellow	\N	\N	2022-01-24 11:47:36.82705+00	UNED	62.204.192.200
A377735	['Host TCP Traffic']	Ongoing	416862226.66667	246700000	yellow	\N	\N	2022-01-24 12:00:35.957663+00	UEM	193.147.239.138
A377737	['Host TCP Traffic']	Ongoing	283754653.33333	187360000	yellow	\N	\N	2022-01-24 12:51:36.794219+00	UAH	193.146.58.180
A377739	['Host TCP Traffic']	Ongoing	1119102173.3333	430310000	yellow	\N	\N	2022-01-24 12:54:35.997466+00	CASA VELAZQUEZ	193.146.142.68
A377750	['Host TCP Traffic']	Ongoing	281400373.33333	187360000	yellow	\N	\N	2022-01-24 13:43:35.810291+00	UAH	193.146.58.180
A377752	['Host TCP Traffic']	Ongoing	306387626.66667	246700000	yellow	\N	\N	2022-01-24 13:45:36.04591+00	UEM	193.147.239.138
A377754	['Host TCP Traffic']	Ongoing	275024240	187360000	yellow	\N	\N	2022-01-24 13:54:36.555567+00	UAH	193.146.58.180
A377759	['Host TCP Traffic']	Ongoing	310205973.33333	246700000	yellow	\N	\N	2022-01-24 14:06:35.999263+00	UEM	193.147.239.138
A377763	['Host TCP Traffic']	Ongoing	345011533.33333	246700000	yellow	\N	\N	2022-01-24 14:33:36.062514+00	UEM	193.147.239.138
A377767	['Host TCP Traffic']	Ongoing	250362706.66667	187360000	yellow	\N	\N	2022-01-24 15:07:35.345965+00	UAH	193.146.58.180
A377769	['Host TCP Traffic']	Ongoing	510003680	246700000	yellow	\N	\N	2022-01-24 15:20:35.808734+00	UEM	193.147.239.138
A377771	['Host TCP Traffic']	Ongoing	392137240	246700000	yellow	\N	\N	2022-01-24 15:31:34.871339+00	UEM	193.147.239.138
A377782	['Host TCP Traffic']	Ongoing	320041773.33333	246700000	yellow	\N	\N	2022-01-24 16:29:36.368155+00	UEM	193.147.239.138
A377784	['HTTP Flooding']	Ongoing	228710306.66667	135540000	yellow	\N	\N	2022-01-24 16:59:34.249104+00	URJC	212.128.240.26
A377786	['Host TCP Traffic']	Ongoing	313007520	246700000	yellow	\N	\N	2022-01-24 17:22:36.218744+00	UEM	193.147.239.138
A377787	['Host TCP Traffic']	Ongoing	246496226.66667	187360000	yellow	\N	\N	2022-01-24 17:43:39.238999+00	UAH	193.146.58.180
A377789	['Host TCP Traffic']	Ongoing	465314333.33333	299320000	yellow	\N	\N	2022-01-24 18:13:34.952897+00	UPM	138.100.4.11
A377797	['Host TCP Traffic']	Ongoing	281090880	187360000	yellow	\N	\N	2022-01-24 20:30:35.321494+00	UAH	193.146.58.180
A377799	['Host TCP Traffic']	Ongoing	284400413.33333	187360000	yellow	\N	\N	2022-01-24 20:53:36.029518+00	UAH	193.146.58.180
A377804	['Host TCP Traffic']	Ongoing	387696640	187360000	yellow	\N	\N	2022-01-24 21:14:36.911134+00	UAH	193.146.58.180
A377812	['Host TCP Traffic']	Ongoing	286055813.33333	246700000	yellow	\N	\N	2022-01-25 08:30:35.768085+00	UEM	193.147.239.138
A377815	['Host TCP Traffic']	Ongoing	429609253.33333	246700000	yellow	\N	\N	2022-01-25 09:34:36.310451+00	UEM	193.147.239.138
A377818	['Host TCP Traffic']	Ongoing	387104933.33333	246700000	yellow	\N	\N	2022-01-25 09:56:35.02327+00	UEM	193.147.239.138
A377819	['Host TCP Traffic']	Ongoing	380105613.33333	246700000	yellow	\N	\N	2022-01-25 10:01:35.970387+00	UEM	193.147.239.138
A377820	['Host TCP Traffic']	Ongoing	395264306.66667	246700000	yellow	\N	\N	2022-01-25 10:14:35.566845+00	UEM	193.147.239.138
A377825	['Host TCP Traffic']	Ongoing	503592146.66667	246700000	yellow	\N	\N	2022-01-25 10:39:36.774026+00	UEM	193.147.239.138
A377832	['Host TCP Traffic']	Ongoing	353283560	246700000	yellow	\N	\N	2022-01-25 11:40:35.740705+00	UEM	193.147.239.138
A377833	['Host TCP Traffic']	Ongoing	376448266.66667	246700000	yellow	\N	\N	2022-01-25 11:45:35.318256+00	UEM	193.147.239.138
A377835	['Host TCP Traffic']	Ongoing	387932066.66667	299320000	yellow	\N	\N	2022-01-25 11:55:34.807485+00	UPM	138.100.4.11
A377836	['Host TCP Traffic']	Ongoing	381668040	246700000	yellow	\N	\N	2022-01-25 11:59:38.959399+00	UEM	193.147.239.138
A377842	['Host TCP Traffic']	Ongoing	428619360	299320000	yellow	\N	\N	2022-01-25 14:27:36.371632+00	UPM	138.100.4.11
A377856	['Host TCP Traffic']	Ongoing	342419666.66667	246700000	yellow	\N	\N	2022-01-25 17:27:36.602161+00	UEM	193.147.239.138
A377858	['Host TCP Traffic']	Ongoing	328552146.66667	203800000	yellow	\N	\N	2022-01-25 19:20:34.895826+00	UAH	193.146.58.180
A377861	['Host TCP Traffic']	Ongoing	417439866.66667	203800000	yellow	\N	\N	2022-01-25 19:42:38.712952+00	UAH	193.146.58.180
A377862	['Host TCP Traffic']	Ongoing	300933786.66667	203800000	yellow	\N	\N	2022-01-25 19:51:37.100821+00	UAH	193.146.58.180
A377863	['Host TCP Traffic']	Ongoing	405032213.33333	203800000	yellow	\N	\N	2022-01-25 20:06:35.470234+00	UAH	193.146.58.180
A377865	['Host TCP Traffic']	Ongoing	286090840	203800000	yellow	\N	\N	2022-01-25 20:36:35.546915+00	UAH	193.146.58.180
A377866	['Host TCP Traffic']	Ongoing	282358626.66667	203800000	yellow	\N	\N	2022-01-25 20:41:34.884716+00	UAH	193.146.58.180
A377869	['Host TCP Traffic']	Ongoing	383239053.33333	203800000	yellow	\N	\N	2022-01-25 21:00:35.363424+00	UAH	193.146.58.180
A377874	['Host TCP Traffic']	Ongoing	291463373.33333	203800000	yellow	\N	\N	2022-01-25 21:38:35.982268+00	UAH	193.146.58.180
A377875	['Host TCP Traffic']	Ongoing	307756253.33333	203800000	yellow	\N	\N	2022-01-25 21:45:35.188487+00	UAH	193.146.58.180
A377878	['Host TCP Traffic']	Ongoing	289113946.66667	203800000	yellow	\N	\N	2022-01-25 22:37:36.206041+00	UAH	193.146.58.180
A377879	['Host TCP Traffic']	Ongoing	270248573.33333	203800000	yellow	\N	\N	2022-01-25 22:48:36.584953+00	UAH	193.146.58.180
A377880	['Host TCP Traffic']	Ongoing	280162386.66667	203800000	yellow	\N	\N	2022-01-25 23:05:36.357003+00	UAH	193.146.58.180
A377901	['Host TCP Traffic']	Ongoing	332218293.33333	208980000	yellow	\N	\N	2022-01-26 08:45:35.091236+00	CEU(2)	193.146.228.60
A377907	['Host TCP Traffic']	Ongoing	233143813.33333	208980000	yellow	\N	\N	2022-01-26 09:44:37.195026+00	CEU(2)	193.146.228.60
A377908	['Host TCP Traffic']	Ongoing	236303173.33333	208980000	yellow	\N	\N	2022-01-26 09:56:37.484218+00	CEU(2)	193.146.228.60
A377911	['Host TCP Traffic']	Ongoing	1130885786.6667	430310000	yellow	\N	\N	2022-01-26 10:33:36.180279+00	CASA VELAZQUEZ	193.146.142.68
A377912	['Host TCP Traffic']	Ongoing	483094120	246700000	yellow	\N	\N	2022-01-26 11:04:36.317713+00	UEM	193.147.239.138
A377914	['HTTP Flooding']	Ongoing	183028760	135540000	yellow	\N	\N	2022-01-26 11:21:35.616495+00	URJC	212.128.240.26
A377915	['HTTP Flooding']	Ongoing	184352173.33333	135540000	yellow	\N	\N	2022-01-26 11:27:34.700544+00	URJC	212.128.240.26
A377920	['Host TCP Traffic']	Ongoing	1115267680	430310000	yellow	\N	\N	2022-01-26 15:53:35.321077+00	CASA VELAZQUEZ	193.146.142.68
A377921	['Host TCP Traffic']	Ongoing	1083822333.3333	430310000	yellow	\N	\N	2022-01-26 15:58:35.489452+00	CASA VELAZQUEZ	193.146.142.68
A377922	['Host TCP Traffic']	Ongoing	1123028120	430310000	yellow	\N	\N	2022-01-26 16:05:35.936824+00	CASA VELAZQUEZ	193.146.142.68
A377929	['Host TCP Traffic']	Ongoing	544073653.33333	432130000	yellow	\N	\N	2022-01-27 08:39:35.462534+00	UNED	62.204.192.200
A377930	['Host TCP Traffic']	Ongoing	1019405906.6667	430310000	yellow	\N	\N	2022-01-27 08:53:35.765625+00	CASA VELAZQUEZ	193.146.142.68
A377936	['Host TCP Traffic']	Ongoing	264235306.66667	203800000	yellow	\N	\N	2022-01-27 14:05:36.281437+00	UAH	193.146.58.180
A377937	['Host TCP Traffic']	Ongoing	283504653.33333	208980000	yellow	\N	\N	2022-01-27 14:49:34.570815+00	CEU(2)	193.146.228.60
A377939	['Host TCP Traffic']	Ongoing	277373840	203800000	yellow	\N	\N	2022-01-27 15:24:35.056092+00	UAH	193.146.58.180
\.


--
-- Data for Name: flowspec_backup_signal; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_backup_signal (id, "boolean") FROM stdin;
1	f
\.


--
-- Data for Name: flowspec_fragmenttype; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_fragmenttype (id, fragmenttype) FROM stdin;
\.


--
-- Data for Name: flowspec_genievents; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_genievents (id, received_at, event, network_characteristics, traffic_characteristics) FROM stdin;
\.


--
-- Data for Name: flowspec_graph; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_graph (id, graph_img, route_id) FROM stdin;
86	/srv/redifod/zabbix_items-192469-from-now-1d-to-now_20220124-162430.png	2
\.


--
-- Data for Name: flowspec_validation; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_validation (id, value, created_date, user_id) FROM stdin;
8	hUKFjs	2022-01-27	2
\.


--
-- Data for Name: flowspec_webhookmessage; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.flowspec_webhookmessage (id, received_at, message) FROM stdin;
\.


--
-- Data for Name: match_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_dscp (id, dscp) FROM stdin;
\.


--
-- Data for Name: match_port; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_port (id, port) FROM stdin;
\.


--
-- Data for Name: match_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.match_protocol (id, protocol) FROM stdin;
4	udp
5	tcp
6	icmp
\.


--
-- Data for Name: peer; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer (peer_id, peer_name, peer_as, peer_tag, domain_name) FROM stdin;
1	IMDEA	\N	IMDEA SOFTWARE	\N
2	UAH	\N	Universidad Autónoma de Madrid	\N
\.


--
-- Data for Name: peer_networks; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_networks (id, peer_id, peerrange_id) FROM stdin;
1	1	1
2	1	2
3	2	1
4	2	2
\.


--
-- Data for Name: peer_range; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_range (id, network) FROM stdin;
1	1.1.1.1/32
2	2.2.2.2/32
\.


--
-- Data for Name: peer_techc_emails; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peer_techc_emails (id, peer_id, techcemail_id) FROM stdin;
\.


--
-- Data for Name: peers_peernotify; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.peers_peernotify (id, peer_activation_notified, peer_id, user_id) FROM stdin;
\.


--
-- Data for Name: route; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route (id, name, source, sourceport, destination, destinationport, port, icmpcode, icmptype, packetlength, filed, last_updated, expires, response, comments, requesters_address, status, applier_id, tcpflag) FROM stdin;
2	ntams_IMDEA	2.2.2.2/32	8080	1.1.1.1/32	443	\N	\N	\N	345	2022-01-18 15:40:39.778491+00	2022-01-18 15:40:42.64933+00	2022-01-31	Successfully committed		unknown	ACTIVE	3	\N
\.


--
-- Data for Name: route_dscp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_dscp (id, route_id, matchdscp_id) FROM stdin;
\.


--
-- Data for Name: route_protocol; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_protocol (id, route_id, matchprotocol_id) FROM stdin;
2	2	5
\.


--
-- Data for Name: route_then; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.route_then (id, route_id, thenaction_id) FROM stdin;
2	2	4
\.


--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- Data for Name: techc_email; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.techc_email (id, email) FROM stdin;
\.


--
-- Data for Name: then_action; Type: TABLE DATA; Schema: public; Owner: fod
--

COPY public.then_action (id, action, action_value) FROM stdin;
1	accept	\N
2	discard	\N
4	rate-limit	2G
3	rate-limit	1G
5	rate-limit	3G
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 4, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 3, true);


--
-- Name: accounts_userprofile_peers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.accounts_userprofile_peers_id_seq', 5, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 129, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 31, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 32, true);


--
-- Name: django_flatpage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_id_seq', 1, false);


--
-- Name: django_flatpage_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_flatpage_sites_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 45, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: flowspec_backup_signal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_backup_signal_id_seq', 1, true);


--
-- Name: flowspec_fragmenttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_fragmenttype_id_seq', 1, false);


--
-- Name: flowspec_genievents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_genievents_id_seq', 1, false);


--
-- Name: flowspec_graph_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_graph_id_seq', 86, true);


--
-- Name: flowspec_validation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_validation_id_seq', 8, true);


--
-- Name: flowspec_webhookmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.flowspec_webhookmessage_id_seq', 1, false);


--
-- Name: match_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_dscp_id_seq', 1, false);


--
-- Name: match_port_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_port_id_seq', 1, false);


--
-- Name: match_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.match_protocol_id_seq', 6, true);


--
-- Name: peer_networks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_networks_id_seq', 4, true);


--
-- Name: peer_peer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_peer_id_seq', 2, true);


--
-- Name: peer_range_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_range_id_seq', 2, true);


--
-- Name: peer_techc_emails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peer_techc_emails_id_seq', 1, false);


--
-- Name: peers_peernotify_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.peers_peernotify_id_seq', 1, false);


--
-- Name: route_dscp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_dscp_id_seq', 1, false);


--
-- Name: route_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_id_seq', 2, true);


--
-- Name: route_protocol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_protocol_id_seq', 2, true);


--
-- Name: route_then_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.route_then_id_seq', 2, true);


--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_sites_id_seq', 1, false);


--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- Name: techc_email_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.techc_email_id_seq', 1, false);


--
-- Name: then_action_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fod
--

SELECT pg_catalog.setval('public.then_action_id_seq', 5, true);


--
-- Name: account_emailaddress account_emailaddress_email_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_email_key UNIQUE (email);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_userprofile_id_peer_id_1ae7cb42_uniq UNIQUE (userprofile_id, peer_id);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage django_flatpage_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage
    ADD CONSTRAINT django_flatpage_pkey PRIMARY KEY (id);


--
-- Name: django_flatpage_sites django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_flatpage_id_site_id_0d29d9d1_uniq UNIQUE (flatpage_id, site_id);


--
-- Name: django_flatpage_sites django_flatpage_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: flowspec_attackevent flowspec_attackevent_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_attackevent
    ADD CONSTRAINT flowspec_attackevent_pkey PRIMARY KEY (id_attack);


--
-- Name: flowspec_backup_signal flowspec_backup_signal_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_backup_signal
    ADD CONSTRAINT flowspec_backup_signal_pkey PRIMARY KEY (id);


--
-- Name: flowspec_fragmenttype flowspec_fragmenttype_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_fragmenttype
    ADD CONSTRAINT flowspec_fragmenttype_pkey PRIMARY KEY (id);


--
-- Name: flowspec_genievents flowspec_genievents_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_genievents
    ADD CONSTRAINT flowspec_genievents_pkey PRIMARY KEY (id);


--
-- Name: flowspec_graph flowspec_graph_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_pkey PRIMARY KEY (id);


--
-- Name: flowspec_validation flowspec_validation_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_pkey PRIMARY KEY (id);


--
-- Name: flowspec_webhookmessage flowspec_webhookmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_webhookmessage
    ADD CONSTRAINT flowspec_webhookmessage_pkey PRIMARY KEY (id);


--
-- Name: match_dscp match_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_dscp
    ADD CONSTRAINT match_dscp_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_pkey PRIMARY KEY (id);


--
-- Name: match_port match_port_port_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_port
    ADD CONSTRAINT match_port_port_key UNIQUE (port);


--
-- Name: match_protocol match_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_pkey PRIMARY KEY (id);


--
-- Name: match_protocol match_protocol_protocol_key; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.match_protocol
    ADD CONSTRAINT match_protocol_protocol_key UNIQUE (protocol);


--
-- Name: peer_networks peer_networks_peer_id_peerrange_id_1404e3fe_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_peerrange_id_1404e3fe_uniq UNIQUE (peer_id, peerrange_id);


--
-- Name: peer_networks peer_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_pkey PRIMARY KEY (id);


--
-- Name: peer peer_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer
    ADD CONSTRAINT peer_pkey PRIMARY KEY (peer_id);


--
-- Name: peer_range peer_range_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_range
    ADD CONSTRAINT peer_range_pkey PRIMARY KEY (id);


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_techcemail_id_18cd8535_uniq UNIQUE (peer_id, techcemail_id);


--
-- Name: peer_techc_emails peer_techc_emails_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_pkey PRIMARY KEY (id);


--
-- Name: peers_peernotify peers_peernotify_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_pkey PRIMARY KEY (id);


--
-- Name: route_dscp route_dscp_route_id_matchdscp_id_bbb43797_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_matchdscp_id_bbb43797_uniq UNIQUE (route_id, matchdscp_id);


--
-- Name: route route_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_pkey PRIMARY KEY (id);


--
-- Name: route_protocol route_protocol_route_id_matchprotocol_id_85c69018_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_matchprotocol_id_85c69018_uniq UNIQUE (route_id, matchprotocol_id);


--
-- Name: route_then route_then_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_pkey PRIMARY KEY (id);


--
-- Name: route_then route_then_route_id_thenaction_id_82a54a0c_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_thenaction_id_82a54a0c_uniq UNIQUE (route_id, thenaction_id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: techc_email techc_email_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.techc_email
    ADD CONSTRAINT techc_email_pkey PRIMARY KEY (id);


--
-- Name: then_action then_action_action_action_value_2bfee264_uniq; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_action_action_value_2bfee264_uniq UNIQUE (action, action_value);


--
-- Name: then_action then_action_pkey; Type: CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.then_action
    ADD CONSTRAINT then_action_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: accounts_userprofile_peers_peer_id_84acb941; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_peer_id_84acb941 ON public.accounts_userprofile_peers USING btree (peer_id);


--
-- Name: accounts_userprofile_peers_userprofile_id_2159c80a; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX accounts_userprofile_peers_userprofile_id_2159c80a ON public.accounts_userprofile_peers USING btree (userprofile_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_flatpage_sites_flatpage_id_078bbc8b; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_flatpage_id_078bbc8b ON public.django_flatpage_sites USING btree (flatpage_id);


--
-- Name: django_flatpage_sites_site_id_bfd8ea84; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_sites_site_id_bfd8ea84 ON public.django_flatpage_sites USING btree (site_id);


--
-- Name: django_flatpage_url_41612362; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362 ON public.django_flatpage USING btree (url);


--
-- Name: django_flatpage_url_41612362_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_flatpage_url_41612362_like ON public.django_flatpage USING btree (url varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: flowspec_attackevent_id_attack_3b1c922c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_attackevent_id_attack_3b1c922c_like ON public.flowspec_attackevent USING btree (id_attack varchar_pattern_ops);


--
-- Name: flowspec_graph_route_id_3841b1c2; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_graph_route_id_3841b1c2 ON public.flowspec_graph USING btree (route_id);


--
-- Name: flowspec_validation_user_id_68741edf; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX flowspec_validation_user_id_68741edf ON public.flowspec_validation USING btree (user_id);


--
-- Name: match_port_port_9d50baf9_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_port_port_9d50baf9_like ON public.match_port USING btree (port varchar_pattern_ops);


--
-- Name: match_protocol_protocol_6d7860e7_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX match_protocol_protocol_6d7860e7_like ON public.match_protocol USING btree (protocol varchar_pattern_ops);


--
-- Name: peer_networks_peer_id_9b1e48f9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peer_id_9b1e48f9 ON public.peer_networks USING btree (peer_id);


--
-- Name: peer_networks_peerrange_id_2647ea6f; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_networks_peerrange_id_2647ea6f ON public.peer_networks USING btree (peerrange_id);


--
-- Name: peer_techc_emails_peer_id_3c925438; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_peer_id_3c925438 ON public.peer_techc_emails USING btree (peer_id);


--
-- Name: peer_techc_emails_techcemail_id_a0dac283; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peer_techc_emails_techcemail_id_a0dac283 ON public.peer_techc_emails USING btree (techcemail_id);


--
-- Name: peers_peernotify_peer_id_b87bf62e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_peer_id_b87bf62e ON public.peers_peernotify USING btree (peer_id);


--
-- Name: peers_peernotify_user_id_0f09946d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX peers_peernotify_user_id_0f09946d ON public.peers_peernotify USING btree (user_id);


--
-- Name: route_applier_id_51f87ff7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_applier_id_51f87ff7 ON public.route USING btree (applier_id);


--
-- Name: route_dscp_matchdscp_id_f3e2c070; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_matchdscp_id_f3e2c070 ON public.route_dscp USING btree (matchdscp_id);


--
-- Name: route_dscp_route_id_3c9f515e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_dscp_route_id_3c9f515e ON public.route_dscp USING btree (route_id);


--
-- Name: route_name_d990cc6c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c ON public.route USING btree (name);


--
-- Name: route_name_d990cc6c_like; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_name_d990cc6c_like ON public.route USING btree (name varchar_pattern_ops);


--
-- Name: route_protocol_matchprotocol_id_da93afcc; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_matchprotocol_id_da93afcc ON public.route_protocol USING btree (matchprotocol_id);


--
-- Name: route_protocol_route_id_de983cfe; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_protocol_route_id_de983cfe ON public.route_protocol USING btree (route_id);


--
-- Name: route_then_route_id_9ffa5b34; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_route_id_9ffa5b34 ON public.route_then USING btree (route_id);


--
-- Name: route_then_thenaction_id_584c41c9; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX route_then_thenaction_id_584c41c9 ON public.route_then USING btree (thenaction_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: fod
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_peers_peer_id_84acb941_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_peers accounts_userprofile_userprofile_id_2159c80a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.accounts_userprofile_peers
    ADD CONSTRAINT accounts_userprofile_userprofile_id_2159c80a_fk_accounts_ FOREIGN KEY (userprofile_id) REFERENCES public.accounts_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_site_flatpage_id_078bbc8b_fk_django_fl FOREIGN KEY (flatpage_id) REFERENCES public.django_flatpage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_flatpage_sites django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.django_flatpage_sites
    ADD CONSTRAINT django_flatpage_sites_site_id_bfd8ea84_fk_django_site_id FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_graph flowspec_graph_route_id_3841b1c2_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_graph
    ADD CONSTRAINT flowspec_graph_route_id_3841b1c2_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flowspec_validation flowspec_validation_user_id_68741edf_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.flowspec_validation
    ADD CONSTRAINT flowspec_validation_user_id_68741edf_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peer_id_9b1e48f9_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peer_id_9b1e48f9_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_networks peer_networks_peerrange_id_2647ea6f_fk_peer_range_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_networks
    ADD CONSTRAINT peer_networks_peerrange_id_2647ea6f_fk_peer_range_id FOREIGN KEY (peerrange_id) REFERENCES public.peer_range(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_peer_id_3c925438_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_peer_id_3c925438_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peer_techc_emails peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peer_techc_emails
    ADD CONSTRAINT peer_techc_emails_techcemail_id_a0dac283_fk_techc_email_id FOREIGN KEY (techcemail_id) REFERENCES public.techc_email(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_peer_id_b87bf62e_fk_peer_peer_id FOREIGN KEY (peer_id) REFERENCES public.peer(peer_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: peers_peernotify peers_peernotify_user_id_0f09946d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.peers_peernotify
    ADD CONSTRAINT peers_peernotify_user_id_0f09946d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route route_applier_id_51f87ff7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_applier_id_51f87ff7_fk_auth_user_id FOREIGN KEY (applier_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_matchdscp_id_f3e2c070_fk_match_dscp_id FOREIGN KEY (matchdscp_id) REFERENCES public.match_dscp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_dscp route_dscp_route_id_3c9f515e_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_dscp
    ADD CONSTRAINT route_dscp_route_id_3c9f515e_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_matchprotocol_id_da93afcc_fk_match_protocol_id FOREIGN KEY (matchprotocol_id) REFERENCES public.match_protocol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_protocol route_protocol_route_id_de983cfe_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_protocol
    ADD CONSTRAINT route_protocol_route_id_de983cfe_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_route_id_9ffa5b34_fk_route_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_route_id_9ffa5b34_fk_route_id FOREIGN KEY (route_id) REFERENCES public.route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: route_then route_then_thenaction_id_584c41c9_fk_then_action_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.route_then
    ADD CONSTRAINT route_then_thenaction_id_584c41c9_fk_then_action_id FOREIGN KEY (thenaction_id) REFERENCES public.then_action(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fod
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

